package hydra.constants

import hydra.core.*

lazy val debugInference: Boolean = true

lazy val ignoredVariable: scala.Predef.String = "_"

lazy val key_classes: hydra.core.Name = "classes"

lazy val key_debugId: hydra.core.Name = "debugId"

lazy val key_deprecated: hydra.core.Name = "deprecated"

lazy val key_description: hydra.core.Name = "description"

lazy val key_exclude: hydra.core.Name = "exclude"

lazy val key_firstClassType: hydra.core.Name = "firstClassType"

lazy val key_freshTypeVariableCount: hydra.core.Name = "freshTypeVariableCount"

lazy val key_maxLength: hydra.core.Name = "maxLength"

lazy val key_minLength: hydra.core.Name = "minLength"

lazy val key_preserveFieldName: hydra.core.Name = "preserveFieldName"

lazy val key_type: hydra.core.Name = "type"

lazy val maxInt32: Int = 2147483647

lazy val maxTraceDepth: Int = 5000

lazy val warningAutoGeneratedFile: scala.Predef.String = "Note: this is an automatically generated file. Do not edit."
