package hydra.constants

import hydra.core.*

val debugInference: Boolean = true

val ignoredVariable: scala.Predef.String = "_"

val key_classes: hydra.core.Name = "classes"

val key_debugId: hydra.core.Name = "debugId"

val key_deprecated: hydra.core.Name = "deprecated"

val key_description: hydra.core.Name = "description"

val key_exclude: hydra.core.Name = "exclude"

val key_firstClassType: hydra.core.Name = "firstClassType"

val key_maxLength: hydra.core.Name = "maxLength"

val key_minLength: hydra.core.Name = "minLength"

val key_preserveFieldName: hydra.core.Name = "preserveFieldName"

val key_type: hydra.core.Name = "type"

val key_freshTypeVariableCount: hydra.core.Name = "freshTypeVariableCount"

val maxInt32: Int = 2147483647

val maxTraceDepth: Int = 5000

val warningAutoGeneratedFile: scala.Predef.String = "Note: this is an automatically generated file. Do not edit."
