// Note: this is an automatically generated file. Do not edit.

package constants

import "hydra.dev/hydra/core"

var DebugInference = true

var IgnoredVariable = "_"

var Key_classes = core.Name("classes")

var Key_debugId = core.Name("debugId")

var Key_deprecated = core.Name("deprecated")

var Key_description = core.Name("description")

var Key_exclude = core.Name("exclude")

var Key_firstClassType = core.Name("firstClassType")

var Key_maxLength = core.Name("maxLength")

var Key_minLength = core.Name("minLength")

var Key_preserveFieldName = core.Name("preserveFieldName")

var Key_type = core.Name("type")

var Key_freshTypeVariableCount = core.Name("freshTypeVariableCount")

var MaxInt32 = 2147483647

var MaxTraceDepth = 5000

var WarningAutoGeneratedFile = "Note: this is an automatically generated file. Do not edit."
