(defpackage :hydra.ext.java.testing
(:use :cl :hydra.coders :hydra.constants :hydra.context :hydra.core :hydra.ext.java.coder :hydra.ext.java.environment :hydra.ext.java.serde :hydra.formatting :hydra.lexical :hydra.lib.eithers :hydra.lib.equality :hydra.lib.lists :hydra.lib.logic :hydra.lib.maps :hydra.lib.sets :hydra.lib.strings :hydra.module :hydra.rewriting :hydra.serialization :hydra.show.errors :hydra.test.utils :hydra.testing :hydra.util)
(:export :hydra_ext_java_testing_build_java_test_module :hydra_ext_java_testing_find_java_imports :hydra_ext_java_testing_format_java_test_name :hydra_ext_java_testing_generate_assertion :hydra_ext_java_testing_get_assertion_type :hydra_ext_java_testing_is_inference_var :hydra_ext_java_testing_generate_java_test_case :hydra_ext_java_testing_generate_java_test_group_hierarchy :hydra_ext_java_testing_generate_test_file_with_java_codec :hydra_ext_java_testing_java_import_template :hydra_ext_java_testing_java_module_template :hydra_ext_java_testing_java_test_case_template :hydra_ext_java_testing_java_test_group_template :hydra_ext_java_testing_namespace_to_java_class_name :hydra_ext_java_testing_term_to_java :hydra_ext_java_testing_type_to_java :hydra_ext_java_testing_java_test_codec :hydra_ext_java_testing_generate_java_test_file))

(in-package :hydra.ext.java.testing)

(cl:defvar hydra_ext_java_testing_build_java_test_module (cl:lambda (codec) (cl:lambda (test_module) (cl:lambda (test_group) (cl:lambda (test_body) (let* ((ns_ ((cl:lambda (v) (hydra_module_module-namespace v)) test_module)) (parts ((hydra_lib_strings_split_on ".") ((cl:lambda (v) v) ns_))) (class_name_ ((hydra_lib_strings_cat2 (hydra_formatting_capitalize (hydra_lib_lists_last parts))) "Test")) (group_name_ ((cl:lambda (v) (hydra_testing_test_group-name v)) test_group)) (package_name ((hydra_lib_strings_intercalate ".") (hydra_lib_lists_init parts))) (standard_imports (cl:list "import org.junit.jupiter.api.Test;" "import static org.junit.jupiter.api.Assertions.*;" "import java.util.*;" "import hydra.util.*;")) (header (hydra_lib_strings_cat (cl:list ((hydra_lib_strings_cat2 "// ") hydra_constants_warning_auto_generated_file) "
" ((hydra_lib_strings_cat2 "// ") group_name_) "

" (hydra_lib_strings_cat (cl:list "package " package_name ";

")) ((hydra_lib_strings_intercalate "
") standard_imports) "

" (hydra_lib_strings_cat (cl:list "public class " class_name_ " {

")))))) (hydra_lib_strings_cat (cl:list header test_body "
}
"))))))))

(cl:defvar hydra_ext_java_testing_find_java_imports (cl:list "import org.junit.jupiter.api.Test;" "import static org.junit.jupiter.api.Assertions.*;" "import java.util.*;"))

(cl:defvar hydra_ext_java_testing_format_java_test_name (cl:lambda (name) (let* ((replaced ((hydra_lib_strings_intercalate " Neg") ((hydra_lib_strings_split_on "-") ((hydra_lib_strings_intercalate "Dot") ((hydra_lib_strings_split_on ".") ((hydra_lib_strings_intercalate " Plus") ((hydra_lib_strings_split_on "+") ((hydra_lib_strings_intercalate " Div") ((hydra_lib_strings_split_on "/") ((hydra_lib_strings_intercalate " Mul") ((hydra_lib_strings_split_on "*") ((hydra_lib_strings_intercalate " Num") ((hydra_lib_strings_split_on "#") name))))))))))))) (sanitized (hydra_formatting_non_alnum_to_underscores replaced)) (pascal_ (((hydra_formatting_convert_case (list :lower_snake cl:nil)) (list :pascal cl:nil)) sanitized))) ((hydra_lib_strings_cat2 "test") pascal_))))

(cl:defvar hydra_ext_java_testing_generate_assertion (cl:lambda (assert_type) (cl:lambda (output_code) (cl:lambda (input_code) (if ((hydra_lib_equality_equal assert_type) "assertArrayEquals") (cl:list "        assertArrayEquals(" (hydra_lib_strings_cat (cl:list "            " output_code ",")) (hydra_lib_strings_cat (cl:list "            " input_code ");"))) (if ((hydra_lib_equality_equal assert_type) "assertBigDecimalEquals") (cl:list (hydra_lib_strings_cat (cl:list "        assertEquals(0, (" output_code ").compareTo(" input_code "));"))) (if ((hydra_lib_equality_equal assert_type) "assertDoubleEquals") (cl:list "        assertEquals(" (hydra_lib_strings_cat (cl:list "            " output_code ",")) (hydra_lib_strings_cat (cl:list "            " input_code ",")) "            1e-15);") (cl:list "        assertEquals(" (hydra_lib_strings_cat (cl:list "            " output_code ",")) (hydra_lib_strings_cat (cl:list "            " input_code ");"))))))))))

(cl:defvar hydra_ext_java_testing_get_assertion_type (cl:lambda (term) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :literal) ((cl:lambda (lit) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :binary) ((cl:lambda (_b) "assertArrayEquals") match_value)) ((equal (car match_target) :float) ((cl:lambda (fv) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :bigfloat) ((cl:lambda (_bf) "assertBigDecimalEquals") match_value)) (t "assertDoubleEquals"))) (cadr match_target))) fv)) match_value)) (t "assertEquals"))) (cadr match_target))) lit)) match_value)) (t "assertEquals"))) (cadr match_target))) (hydra_rewriting_deannotate_term term))))

(cl:defvar hydra_ext_java_testing_is_inference_var (cl:lambda (n) (let* ((s ((cl:lambda (v) v) n)) (chars (hydra_lib_strings_to_list s))) ((hydra_lib_logic_and ((hydra_lib_equality_equal ((hydra_lib_strings_char_at 0) s)) 116)) ((hydra_lib_logic_and (hydra_lib_logic_not ((hydra_lib_equality_equal (hydra_lib_strings_length s)) 1))) (hydra_lib_lists_null ((hydra_lib_lists_filter (cl:lambda (c) (hydra_lib_logic_not ((hydra_lib_logic_and ((hydra_lib_equality_gte c) 48)) ((hydra_lib_equality_lte c) 57))))) ((hydra_lib_lists_drop 1) chars))))))))

(cl:defvar hydra_ext_java_testing_generate_java_test_case (cl:lambda (g) (cl:lambda (codec) (cl:lambda (group_path) (cl:lambda (tcm) (let* ((name_ ((cl:lambda (v) (hydra_testing_test_case_with_metadata-name v)) tcm)) (tcase ((cl:lambda (v) (hydra_testing_test_case_with_metadata-case v)) tcm))) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :delegated_evaluation) ((cl:lambda (del_case) (let* ((output_ ((cl:lambda (v) (hydra_testing_delegated_evaluation_test_case-output v)) del_case)) (assert_type (hydra_ext_java_testing_get_assertion_type output_)) (full_name (if (hydra_lib_lists_null group_path) name_ ((hydra_lib_strings_intercalate "_") ((hydra_lib_lists_concat2 group_path) (cl:list name_))))) (formatted_name (((cl:lambda (v) (hydra_testing_test_codec-format_test_name v)) codec) full_name)) (input_ ((cl:lambda (v) (hydra_testing_delegated_evaluation_test_case-input v)) del_case))) (let* ((type_vars (hydra_lib_lists_sort ((hydra_lib_lists_filter hydra_ext_java_testing_is_inference_var) (hydra_lib_sets_to_list ((hydra_lib_sets_union (hydra_rewriting_free_type_variables_in_term input_)) (hydra_rewriting_free_type_variables_in_term output_)))))) (type_params_str (if (hydra_lib_lists_null type_vars) "" (hydra_lib_strings_cat (cl:list "<" ((hydra_lib_strings_intercalate ", ") ((hydra_lib_lists_map (cl:lambda (n_) (hydra_formatting_capitalize ((cl:lambda (v) v) n_)))) type_vars)) "> "))))) ((hydra_lib_eithers_bind ((((cl:lambda (v) (hydra_testing_test_codec-encode_term v)) codec) input_) g)) (cl:lambda (input_code) ((hydra_lib_eithers_map (cl:lambda (output_code) (let ((assertion_lines (((hydra_ext_java_testing_generate_assertion assert_type) output_code) input_code))) ((hydra_lib_lists_concat2 (cl:list "    @Test" (hydra_lib_strings_cat (cl:list "    public " type_params_str "void " formatted_name "() {")))) ((hydra_lib_lists_concat2 assertion_lines) (cl:list "    }")))))) ((((cl:lambda (v) (hydra_testing_test_codec-encode_term v)) codec) output_) g))))))) match_value)) (t (list :right (cl:list))))) (cadr match_target))) tcase)))))))

(cl:defvar hydra_ext_java_testing_generate_java_test_group_hierarchy (cl:lambda (g) (cl:lambda (codec) (cl:lambda (group_path) (cl:lambda (test_group) (let* ((cases_ ((cl:lambda (v) (hydra_testing_test_group-cases v)) test_group)) (subgroups ((cl:lambda (v) (hydra_testing_test_group-subgroups v)) test_group))) ((hydra_lib_eithers_bind ((hydra_lib_eithers_map (cl:lambda (lines_) ((hydra_lib_strings_intercalate "

") (hydra_lib_lists_concat lines_)))) ((hydra_lib_eithers_map_list (cl:lambda (tc) ((((hydra_ext_java_testing_generate_java_test_case g) codec) group_path) tc))) cases_))) (cl:lambda (test_cases_str) ((hydra_lib_eithers_map (cl:lambda (subgroups_str) (hydra_lib_strings_cat (cl:list test_cases_str (if ((hydra_lib_logic_or ((hydra_lib_equality_equal test_cases_str) "")) ((hydra_lib_equality_equal subgroups_str) "")) "" "

") subgroups_str)))) ((hydra_lib_eithers_map (cl:lambda (blocks) ((hydra_lib_strings_intercalate "

") blocks))) ((hydra_lib_eithers_map_list (cl:lambda (subgroup) (let* ((group_name ((cl:lambda (v) (hydra_testing_test_group-name v)) subgroup)) (header ((hydra_lib_strings_cat2 "    // ") group_name))) ((hydra_lib_eithers_map (cl:lambda (content) (hydra_lib_strings_cat (cl:list header "

" content)))) ((((hydra_ext_java_testing_generate_java_test_group_hierarchy g) codec) ((hydra_lib_lists_concat2 group_path) (cl:list group_name))) subgroup))))) subgroups)))))))))))

(cl:defvar hydra_ext_java_testing_generate_test_file_with_java_codec (cl:lambda (codec) (cl:lambda (test_module) (cl:lambda (test_group) (cl:lambda (g) ((hydra_lib_eithers_map (cl:lambda (test_body) (let* ((ns_ ((cl:lambda (v) (hydra_module_module-namespace v)) test_module)) (parts ((hydra_lib_strings_split_on ".") ((cl:lambda (v) v) ns_))) (class_name_ ((hydra_lib_strings_cat2 (hydra_formatting_capitalize (hydra_lib_lists_last parts))) "Test")) (dir_parts ((hydra_lib_lists_drop 1) (hydra_lib_lists_init parts))) (file_name ((hydra_lib_strings_cat2 class_name_) ".java")) (file_path (hydra_lib_strings_cat (cl:list ((hydra_lib_strings_intercalate "/") dir_parts) "/" file_name))) (test_module_content ((((hydra_ext_java_testing_build_java_test_module codec) test_module) test_group) test_body))) (cl:list file_path test_module_content)))) ((((hydra_ext_java_testing_generate_java_test_group_hierarchy g) codec) (cl:list)) test_group)))))))

(cl:defvar hydra_ext_java_testing_java_import_template "import {namespace};")

(cl:defvar hydra_ext_java_testing_java_module_template ((hydra_lib_strings_intercalate "
") (cl:list ((hydra_lib_strings_cat2 "// ") hydra_constants_warning_auto_generated_file) "" "package {package};" "" "{imports}" "" "public class {className} {" "    {testCases}" "}")))

(cl:defvar hydra_ext_java_testing_java_test_case_template ((hydra_lib_strings_intercalate "
") (cl:list "    @Test" "    public void {name}() {" "        assertEquals({output}, {input});" "    }")))

(cl:defvar hydra_ext_java_testing_java_test_group_template "// {groupName}")

(cl:defvar hydra_ext_java_testing_namespace_to_java_class_name (cl:lambda (ns_) ((hydra_lib_strings_intercalate ".") ((hydra_lib_lists_map hydra_formatting_capitalize) ((hydra_lib_strings_split_on ".") ((cl:lambda (v) v) ns_))))))

(cl:defvar hydra_ext_java_testing_term_to_java (cl:lambda (term) (cl:lambda (g) (((hydra_lib_eithers_bimap (cl:lambda (ic) (hydra_show_errors_error ((cl:lambda (v) (hydra_context_in_context-object v)) ic)))) (cl:lambda (arg_) ((cl:lambda (arg_) (hydra_serialization_print_expr (hydra_serialization_parenthesize arg_))) (hydra_ext_java_serde_write_expression arg_)))) ((((hydra_ext_java_coder_encode_term (make-hydra_ext_java_environment_java_environment (make-hydra_ext_java_environment_aliases "test" hydra_lib_maps_empty hydra_lib_sets_empty hydra_lib_sets_empty hydra_lib_sets_empty hydra_lib_sets_empty hydra_lib_sets_empty hydra_lib_maps_empty hydra_lib_sets_empty hydra_lib_maps_empty hydra_lib_sets_empty (list :nothing) hydra_lib_sets_empty) g)) term) hydra_lexical_empty_context) g)))))

(cl:defvar hydra_ext_java_testing_type_to_java (cl:lambda (_t) (cl:lambda (_g) (list :right "Object"))))

(cl:defvar hydra_ext_java_testing_java_test_codec (make-hydra_testing_test_codec "java" "java" hydra_ext_java_testing_term_to_java hydra_ext_java_testing_type_to_java hydra_ext_java_testing_format_java_test_name hydra_ext_java_testing_namespace_to_java_class_name hydra_ext_java_testing_java_test_case_template hydra_ext_java_testing_java_test_group_template hydra_ext_java_testing_java_module_template hydra_ext_java_testing_java_import_template (cl:lambda (_names) hydra_ext_java_testing_find_java_imports)))

(cl:defvar hydra_ext_java_testing_generate_java_test_file (cl:lambda (test_module) (cl:lambda (test_group) (cl:lambda (g) ((hydra_lib_eithers_bind ((hydra_test_utils_infer_test_group_terms g) test_group)) (cl:lambda (inferred_test_group) ((((hydra_ext_java_testing_generate_test_file_with_java_codec hydra_ext_java_testing_java_test_codec) test_module) inferred_test_group) g)))))))
