(defpackage :hydra.validate.packaging
(:use :cl :hydra.core :hydra.error.packaging :hydra.formatting :hydra.lib.equality :hydra.lib.lists :hydra.lib.logic :hydra.lib.maps :hydra.lib.maybes :hydra.lib.pairs :hydra.lib.sets :hydra.lib.strings :hydra.module :hydra.names :hydra.packaging)
(:export :hydra_validate_packaging_check_conflicting_module_namespaces :hydra_validate_packaging_definition_name :hydra_validate_packaging_check_conflicting_variant_names :hydra_validate_packaging_check_definition_namespaces :hydra_validate_packaging_check_duplicate_definition_names :hydra_validate_packaging_check_duplicate_module_namespaces :hydra_validate_packaging_module :hydra_validate_packaging_package))

(in-package :hydra.validate.packaging)

(cl:defvar hydra_validate_packaging_check_conflicting_module_namespaces (cl:lambda (pkg) (let ((result (((hydra_lib_lists_foldl (cl:lambda (acc) (cl:lambda (mod) (let ((seen (hydra_lib_pairs_first acc))) (let ((err (hydra_lib_pairs_second acc))) (((hydra_lib_maybes_cases err) (cl:lambda () (let ((ns_ ((cl:lambda (v) (hydra_module_module-namespace v)) mod))) (let ((key (hydra_lib_strings_to_lower ((cl:lambda (v) v) ns_)))) (let ((existing ((hydra_lib_maps_lookup key) seen))) (((hydra_lib_maybes_cases existing) (cl:lambda () (cl:list (((hydra_lib_maps_insert key) ns_) seen) (list :nothing)))) (cl:lambda (first) (cl:list seen (list :just (list :conflicting_module_namespace (make-hydra_error_packaging_conflicting_module_namespace_error first ns_))))))))))) (cl:lambda (_) acc))))))) (cl:list hydra_lib_maps_empty (list :nothing))) ((cl:lambda (v) (hydra_packaging_package-modules v)) pkg)))) (hydra_lib_pairs_second result))))

(cl:defvar hydra_validate_packaging_definition_name (cl:lambda (def_) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :term) ((cl:lambda (td) ((cl:lambda (v) (hydra_module_term_definition-name v)) td)) match_value)) ((equal (car match_target) :type) ((cl:lambda (td) ((cl:lambda (v) (hydra_module_type_definition-name v)) td)) match_value)))) (cadr match_target))) def_)))

(cl:defvar hydra_validate_packaging_check_conflicting_variant_names (cl:lambda (mod) (let ((ns_ ((cl:lambda (v) (hydra_module_module-namespace v)) mod))) (let ((defs ((cl:lambda (v) (hydra_module_module-definitions v)) mod))) (let ((def_names (((hydra_lib_lists_foldl (cl:lambda (acc) (cl:lambda (def_) ((hydra_lib_sets_insert (hydra_names_local_name_of (hydra_validate_packaging_definition_name def_))) acc)))) hydra_lib_sets_empty) defs))) (((hydra_lib_lists_foldl (cl:lambda (acc) (cl:lambda (def_) (((hydra_lib_maybes_cases acc) (cl:lambda () ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :type) ((cl:lambda (td) (let ((type_name ((cl:lambda (v) (hydra_module_type_definition-name v)) td))) (let ((local_type_name (hydra_names_local_name_of type_name))) (let ((typ ((cl:lambda (v) (hydra_module_type_definition-type v)) td))) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :union) ((cl:lambda (fields) (((hydra_lib_lists_foldl (cl:lambda (inner_acc) (cl:lambda (field) (((hydra_lib_maybes_cases inner_acc) (cl:lambda () (let ((field_name ((cl:lambda (v) (hydra_core_field_type-name v)) field))) (let ((local_field_name (hydra_names_local_name_of field_name))) (let ((constructor_name ((hydra_lib_strings_cat2 (hydra_formatting_capitalize local_type_name)) (hydra_formatting_capitalize local_field_name)))) (if ((hydra_lib_sets_member constructor_name) def_names) (list :just (list :conflicting_variant_name (make-hydra_error_packaging_conflicting_variant_name_error ns_ type_name field_name constructor_name))) (list :nothing))))))) (cl:lambda (_) inner_acc))))) (list :nothing)) fields)) match_value)) (t (list :nothing)))) (cadr match_target))) typ))))) match_value)) (t (list :nothing)))) (cadr match_target))) def_))) (cl:lambda (_) acc))))) (list :nothing)) defs))))))

(cl:defvar hydra_validate_packaging_check_definition_namespaces (cl:lambda (mod) (let ((ns_ ((cl:lambda (v) (hydra_module_module-namespace v)) mod))) (let ((prefix ((hydra_lib_strings_cat2 ((cl:lambda (v) v) ns_)) "."))) (let ((prefix_len (hydra_lib_strings_length prefix))) (((hydra_lib_lists_foldl (cl:lambda (acc) (cl:lambda (def_) (((hydra_lib_maybes_cases acc) (cl:lambda () (let ((name (hydra_validate_packaging_definition_name def_))) (let ((name_str ((cl:lambda (v) v) name))) (let ((name_prefix ((hydra_lib_lists_take prefix_len) (hydra_lib_strings_to_list name_str)))) (if ((hydra_lib_equality_equal (hydra_lib_strings_from_list name_prefix)) prefix) (list :nothing) (list :just (list :definition_not_in_module_namespace (make-hydra_error_packaging_definition_not_in_module_namespace_error ns_ name))))))))) (cl:lambda (_) acc))))) (list :nothing)) ((cl:lambda (v) (hydra_module_module-definitions v)) mod)))))))

(cl:defvar hydra_validate_packaging_check_duplicate_definition_names (cl:lambda (mod) (let ((ns_ ((cl:lambda (v) (hydra_module_module-namespace v)) mod))) (let ((result (((hydra_lib_lists_foldl (cl:lambda (acc) (cl:lambda (def_) (let ((seen (hydra_lib_pairs_first acc))) (let ((err (hydra_lib_pairs_second acc))) (((hydra_lib_maybes_cases err) (cl:lambda () (let ((name (hydra_validate_packaging_definition_name def_))) (if ((hydra_lib_sets_member name) seen) (cl:list seen (list :just (list :duplicate_definition_name (make-hydra_error_packaging_duplicate_definition_name_error ns_ name)))) (cl:list ((hydra_lib_sets_insert name) seen) (list :nothing)))))) (cl:lambda (_) acc))))))) (cl:list hydra_lib_sets_empty (list :nothing))) ((cl:lambda (v) (hydra_module_module-definitions v)) mod)))) (hydra_lib_pairs_second result)))))

(cl:defvar hydra_validate_packaging_check_duplicate_module_namespaces (cl:lambda (pkg) (let ((result (((hydra_lib_lists_foldl (cl:lambda (acc) (cl:lambda (mod) (let ((seen (hydra_lib_pairs_first acc))) (let ((err (hydra_lib_pairs_second acc))) (((hydra_lib_maybes_cases err) (cl:lambda () (let ((ns_ ((cl:lambda (v) (hydra_module_module-namespace v)) mod))) (if ((hydra_lib_sets_member ns_) seen) (cl:list seen (list :just (list :duplicate_module_namespace (make-hydra_error_packaging_duplicate_module_namespace_error ns_)))) (cl:list ((hydra_lib_sets_insert ns_) seen) (list :nothing)))))) (cl:lambda (_) acc))))))) (cl:list hydra_lib_sets_empty (list :nothing))) ((cl:lambda (v) (hydra_packaging_package-modules v)) pkg)))) (hydra_lib_pairs_second result))))

(cl:defvar hydra_validate_packaging_module (cl:lambda (mod) (let ((r1 (hydra_validate_packaging_check_definition_namespaces mod))) (((hydra_lib_maybes_cases r1) (cl:lambda () (let ((r2 (hydra_validate_packaging_check_duplicate_definition_names mod))) (((hydra_lib_maybes_cases r2) (cl:lambda () (hydra_validate_packaging_check_conflicting_variant_names mod))) (cl:lambda (_) r2))))) (cl:lambda (_) r1)))))

(cl:defvar hydra_validate_packaging_package (cl:lambda (pkg) (let ((r1 (hydra_validate_packaging_check_duplicate_module_namespaces pkg))) (((hydra_lib_maybes_cases r1) (cl:lambda () (let ((r2 (hydra_validate_packaging_check_conflicting_module_namespaces pkg))) (((hydra_lib_maybes_cases r2) (cl:lambda () (((hydra_lib_lists_foldl (cl:lambda (acc) (cl:lambda (mod) (((hydra_lib_maybes_cases acc) (cl:lambda () ((hydra_lib_maybes_map (cl:lambda (err) (list :invalid_module err))) (hydra_validate_packaging_module mod)))) (cl:lambda (_) acc))))) (list :nothing)) ((cl:lambda (v) (hydra_packaging_package-modules v)) pkg)))) (cl:lambda (_) r2))))) (cl:lambda (_) r1)))))
