(defpackage :hydra.encoding
(:use :cl :hydra.annotations :hydra.context :hydra.core :hydra.decode.core :hydra.error :hydra.formatting :hydra.lib.eithers :hydra.lib.lists :hydra.lib.logic :hydra.lib.maps :hydra.lib.maybes :hydra.lib.sets :hydra.lib.strings :hydra.module :hydra.names :hydra.schemas)
(:export :hydra_encoding_encode_binding_name :hydra_encoding_encode_float_value :hydra_encoding_encode_integer_value :hydra_encoding_encode_literal_type :hydra_encoding_encode_name :hydra_encoding_encode_injection :hydra_encoding_encode_either_type :hydra_encoding_encode_field_value :hydra_encoding_encode_forall_type :hydra_encoding_encode_list_type :hydra_encoding_encode_map_type :hydra_encoding_encode_optional_type :hydra_encoding_encode_pair_type :hydra_encoding_encode_record_type :hydra_encoding_encode_set_type :hydra_encoding_encode_type :hydra_encoding_encode_union_type :hydra_encoding_encode_wrapped_type :hydra_encoding_encoder_collect_forall_variables :hydra_encoding_encoder_collect_type_vars_from_type :hydra_encoding_encoder_collect_ord_vars :hydra_encoding_encoder_full_result_type :hydra_encoding_prepend_forall_encoders :hydra_encoding_encoder_type :hydra_encoding_encoder_type_scheme :hydra_encoding_encode_binding :hydra_encoding_encode_namespace :hydra_encoding_is_encodable_binding :hydra_encoding_filter_type_bindings :hydra_encoding_encode_module :hydra_encoding_is_unit_type))

(in-package :hydra.encoding)

(cl:defvar hydra_encoding_encode_binding_name (cl:lambda (n) (if (hydra_lib_logic_not (hydra_lib_lists_null (hydra_lib_lists_tail ((hydra_lib_strings_split_on ".") ((cl:lambda (v) v) n))))) ((hydra_lib_strings_intercalate ".") ((hydra_lib_lists_concat2 (cl:list "hydra" "encode")) ((hydra_lib_lists_concat2 (hydra_lib_lists_tail (hydra_lib_lists_init ((hydra_lib_strings_split_on ".") ((cl:lambda (v) v) n))))) (cl:list (hydra_formatting_decapitalize (hydra_names_local_name_of n)))))) (hydra_formatting_decapitalize (hydra_names_local_name_of n)))))

(cl:defvar hydra_encoding_encode_float_value (cl:lambda (float_type) (cl:lambda (val_term) (list :union (make-hydra_core_injection "hydra.core.FloatValue" (make-hydra_core_field ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :bigfloat) ((cl:lambda (_) "bigfloat") match_value)) ((equal (car match_target) :float32) ((cl:lambda (_) "float32") match_value)) ((equal (car match_target) :float64) ((cl:lambda (_) "float64") match_value)))) (cadr match_target))) float_type) val_term))))))

(cl:defvar hydra_encoding_encode_integer_value (cl:lambda (int_type) (cl:lambda (val_term) (list :union (make-hydra_core_injection "hydra.core.IntegerValue" (make-hydra_core_field ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :bigint) ((cl:lambda (_) "bigint") match_value)) ((equal (car match_target) :int8) ((cl:lambda (_) "int8") match_value)) ((equal (car match_target) :int16) ((cl:lambda (_) "int16") match_value)) ((equal (car match_target) :int32) ((cl:lambda (_) "int32") match_value)) ((equal (car match_target) :int64) ((cl:lambda (_) "int64") match_value)) ((equal (car match_target) :uint8) ((cl:lambda (_) "uint8") match_value)) ((equal (car match_target) :uint16) ((cl:lambda (_) "uint16") match_value)) ((equal (car match_target) :uint32) ((cl:lambda (_) "uint32") match_value)) ((equal (car match_target) :uint64) ((cl:lambda (_) "uint64") match_value)))) (cadr match_target))) int_type) val_term))))))

(cl:defvar hydra_encoding_encode_literal_type (cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :binary) ((cl:lambda (_) (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "literal" (list :union (make-hydra_core_injection "hydra.core.Literal" (make-hydra_core_field "binary" (list :variable "x"))))))))))) match_value)) ((equal (car match_target) :boolean) ((cl:lambda (_) (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "literal" (list :union (make-hydra_core_injection "hydra.core.Literal" (make-hydra_core_field "boolean" (list :variable "x"))))))))))) match_value)) ((equal (car match_target) :string) ((cl:lambda (_) (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "literal" (list :union (make-hydra_core_injection "hydra.core.Literal" (make-hydra_core_field "string" (list :variable "x"))))))))))) match_value)) ((equal (car match_target) :integer) ((cl:lambda (int_type) (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "literal" (list :union (make-hydra_core_injection "hydra.core.Literal" (make-hydra_core_field "integer" ((hydra_encoding_encode_integer_value int_type) (list :variable "x")))))))))))) match_value)) ((equal (car match_target) :float) ((cl:lambda (float_type) (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "literal" (list :union (make-hydra_core_injection "hydra.core.Literal" (make-hydra_core_field "float" ((hydra_encoding_encode_float_value float_type) (list :variable "x")))))))))))) match_value)) (t (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :variable "x"))))))) (cadr match_target))))

(cl:defvar hydra_encoding_encode_name (cl:lambda (n) (list :wrap (make-hydra_core_wrapped_term "hydra.core.Name" (list :literal (list :string ((cl:lambda (v) v) n)))))))

(cl:defvar hydra_encoding_encode_injection (cl:lambda (type_name) (cl:lambda (field_name) (cl:lambda (field_term) (list :record (make-hydra_core_record "hydra.core.Injection" (cl:list (make-hydra_core_field "typeName" (hydra_encoding_encode_name type_name)) (make-hydra_core_field "field" (((cl:lambda (fname) (cl:lambda (fterm) (list :record (make-hydra_core_record "hydra.core.Field" (cl:list (make-hydra_core_field "name" (hydra_encoding_encode_name fname)) (make-hydra_core_field "term" fterm)))))) field_name) field_term)))))))))

(cl:defvar hydra_encoding_encode_either_type (cl:lambda (et) (list :function (list :lambda (make-hydra_core_lambda "e" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "either" (list :application (make-hydra_core_application (list :application (make-hydra_core_application (list :application (make-hydra_core_application (list :function (list :primitive "hydra.lib.eithers.bimap")) (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_either_type-left v)) et)))) (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_either_type-right v)) et)))) (list :variable "e")))))))))))

(cl:defvar hydra_encoding_encode_field_value (cl:lambda (type_name) (cl:lambda (field_name) (cl:lambda (field_type) (list :function (list :lambda (make-hydra_core_lambda "y" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "union" (((hydra_encoding_encode_injection type_name) field_name) (list :application (make-hydra_core_application (hydra_encoding_encode_type field_type) (list :variable "y"))))))))))))))

(cl:defvar hydra_encoding_encode_forall_type (cl:lambda (ft) (list :function (list :lambda (make-hydra_core_lambda (hydra_encoding_encode_binding_name ((cl:lambda (v) (hydra_core_forall_type-parameter v)) ft)) cl:nil (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_forall_type-body v)) ft)))))))

(cl:defvar hydra_encoding_encode_list_type (cl:lambda (elem_type) (list :function (list :lambda (make-hydra_core_lambda "xs" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "list" (list :application (make-hydra_core_application (list :application (make-hydra_core_application (list :function (list :primitive "hydra.lib.lists.map")) (hydra_encoding_encode_type elem_type))) (list :variable "xs")))))))))))

(cl:defvar hydra_encoding_encode_map_type (cl:lambda (mt) (list :function (list :lambda (make-hydra_core_lambda "m" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "map" (list :application (make-hydra_core_application (list :application (make-hydra_core_application (list :application (make-hydra_core_application (list :function (list :primitive "hydra.lib.maps.bimap")) (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_map_type-keys v)) mt)))) (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_map_type-values v)) mt)))) (list :variable "m")))))))))))

(cl:defvar hydra_encoding_encode_optional_type (cl:lambda (elem_type) (list :function (list :lambda (make-hydra_core_lambda "opt" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "maybe" (list :application (make-hydra_core_application (list :application (make-hydra_core_application (list :function (list :primitive "hydra.lib.maybes.map")) (hydra_encoding_encode_type elem_type))) (list :variable "opt")))))))))))

(cl:defvar hydra_encoding_encode_pair_type (cl:lambda (pt) (list :function (list :lambda (make-hydra_core_lambda "p" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "pair" (list :application (make-hydra_core_application (list :application (make-hydra_core_application (list :application (make-hydra_core_application (list :function (list :primitive "hydra.lib.pairs.bimap")) (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_pair_type-first v)) pt)))) (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_pair_type-second v)) pt)))) (list :variable "p")))))))))))

(cl:defvar hydra_encoding_encode_record_type (cl:lambda (rt) (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "record" (list :record (make-hydra_core_record "hydra.core.Record" (cl:list (make-hydra_core_field "typeName" (hydra_encoding_encode_name ((cl:lambda (v) (hydra_core_row_type-type_name v)) rt))) (make-hydra_core_field "fields" (list :list ((hydra_lib_lists_map ((cl:lambda (rec_type) (cl:lambda (ft) (list :record (make-hydra_core_record "hydra.core.Field" (cl:list (make-hydra_core_field "name" (hydra_encoding_encode_name ((cl:lambda (v) (hydra_core_field_type-name v)) ft))) (make-hydra_core_field "term" (list :application (make-hydra_core_application (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_field_type-type v)) ft)) (list :application (make-hydra_core_application (list :function (list :elimination (list :record (make-hydra_core_projection ((cl:lambda (v) (hydra_core_row_type-type_name v)) rec_type) ((cl:lambda (v) (hydra_core_field_type-name v)) ft))))) (list :variable "x"))))))))))) rt)) ((cl:lambda (v) (hydra_core_row_type-fields v)) rt)))))))))))))))

(cl:defvar hydra_encoding_encode_set_type (cl:lambda (elem_type) (list :function (list :lambda (make-hydra_core_lambda "s" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "set" (list :application (make-hydra_core_application (list :application (make-hydra_core_application (list :function (list :primitive "hydra.lib.sets.map")) (hydra_encoding_encode_type elem_type))) (list :variable "s")))))))))))

(cl:defvar hydra_encoding_encode_type (cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :annotated) ((cl:lambda (at) (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_annotated_type-body v)) at))) match_value)) ((equal (car match_target) :application) ((cl:lambda (app_type) (list :application (make-hydra_core_application (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_application_type-function v)) app_type)) (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_application_type-argument v)) app_type))))) match_value)) ((equal (car match_target) :either) ((cl:lambda (et) (hydra_encoding_encode_either_type et)) match_value)) ((equal (car match_target) :forall) ((cl:lambda (ft) (hydra_encoding_encode_forall_type ft)) match_value)) ((equal (car match_target) :function) ((cl:lambda (_) (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :variable "x"))))) match_value)) ((equal (car match_target) :list) ((cl:lambda (elem_type) (hydra_encoding_encode_list_type elem_type)) match_value)) ((equal (car match_target) :literal) ((cl:lambda (lt) (hydra_encoding_encode_literal_type lt)) match_value)) ((equal (car match_target) :map) ((cl:lambda (mt) (hydra_encoding_encode_map_type mt)) match_value)) ((equal (car match_target) :maybe) ((cl:lambda (elem_type) (hydra_encoding_encode_optional_type elem_type)) match_value)) ((equal (car match_target) :pair) ((cl:lambda (pt) (hydra_encoding_encode_pair_type pt)) match_value)) ((equal (car match_target) :record) ((cl:lambda (rt) (hydra_encoding_encode_record_type rt)) match_value)) ((equal (car match_target) :set) ((cl:lambda (elem_type) (hydra_encoding_encode_set_type elem_type)) match_value)) ((equal (car match_target) :union) ((cl:lambda (rt) (hydra_encoding_encode_union_type rt)) match_value)) ((equal (car match_target) :wrap) ((cl:lambda (wt) (hydra_encoding_encode_wrapped_type wt)) match_value)) ((equal (car match_target) :unit) ((cl:lambda (_) (list :function (list :lambda (make-hydra_core_lambda "_" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "unit" (list :unit cl:nil)))))))) match_value)) ((equal (car match_target) :variable) ((cl:lambda (type_name) (list :variable (hydra_encoding_encode_binding_name type_name))) match_value)) (t (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :variable "x"))))))) (cadr match_target))))

(cl:defvar hydra_encoding_encode_union_type (cl:lambda (rt) (list :function (list :elimination (list :union (make-hydra_core_case_statement ((cl:lambda (v) (hydra_core_row_type-type_name v)) rt) cl:nil ((hydra_lib_lists_map (cl:lambda (ft) (make-hydra_core_field ((cl:lambda (v) (hydra_core_field_type-name v)) ft) (((hydra_encoding_encode_field_value ((cl:lambda (v) (hydra_core_row_type-type_name v)) rt)) ((cl:lambda (v) (hydra_core_field_type-name v)) ft)) ((cl:lambda (v) (hydra_core_field_type-type v)) ft))))) ((cl:lambda (v) (hydra_core_row_type-fields v)) rt))))))))

(cl:defvar hydra_encoding_encode_wrapped_type (cl:lambda (wt) (list :function (list :lambda (make-hydra_core_lambda "x" cl:nil (list :union (make-hydra_core_injection "hydra.core.Term" (make-hydra_core_field "wrap" (list :record (make-hydra_core_record "hydra.core.WrappedTerm" (cl:list (make-hydra_core_field "typeName" (hydra_encoding_encode_name ((cl:lambda (v) (hydra_core_wrapped_type-type_name v)) wt))) (make-hydra_core_field "body" (list :application (make-hydra_core_application (hydra_encoding_encode_type ((cl:lambda (v) (hydra_core_wrapped_type-body v)) wt)) (list :application (make-hydra_core_application (list :function (list :elimination (list :wrap ((cl:lambda (v) (hydra_core_wrapped_type-type_name v)) wt)))) (list :variable "x")))))))))))))))))

(cl:defvar hydra_encoding_encoder_collect_forall_variables (cl:lambda (typ) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :annotated) ((cl:lambda (at) (hydra_encoding_encoder_collect_forall_variables ((cl:lambda (v) (hydra_core_annotated_type-body v)) at))) match_value)) ((equal (car match_target) :forall) ((cl:lambda (ft) ((hydra_lib_lists_cons ((cl:lambda (v) (hydra_core_forall_type-parameter v)) ft)) (hydra_encoding_encoder_collect_forall_variables ((cl:lambda (v) (hydra_core_forall_type-body v)) ft)))) match_value)) (t (cl:list)))) (cadr match_target))) typ)))

(cl:defvar hydra_encoding_encoder_collect_type_vars_from_type (cl:lambda (typ) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :annotated) ((cl:lambda (at) (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_annotated_type-body v)) at))) match_value)) ((equal (car match_target) :application) ((cl:lambda (app_type) ((hydra_lib_lists_concat2 (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_application_type-function v)) app_type))) (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_application_type-argument v)) app_type)))) match_value)) ((equal (car match_target) :forall) ((cl:lambda (ft) (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_forall_type-body v)) ft))) match_value)) ((equal (car match_target) :list) ((cl:lambda (elem_type) (hydra_encoding_encoder_collect_type_vars_from_type elem_type)) match_value)) ((equal (car match_target) :map) ((cl:lambda (mt) ((hydra_lib_lists_concat2 (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_map_type-keys v)) mt))) (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_map_type-values v)) mt)))) match_value)) ((equal (car match_target) :maybe) ((cl:lambda (elem_type) (hydra_encoding_encoder_collect_type_vars_from_type elem_type)) match_value)) ((equal (car match_target) :pair) ((cl:lambda (pt) ((hydra_lib_lists_concat2 (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_pair_type-first v)) pt))) (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_pair_type-second v)) pt)))) match_value)) ((equal (car match_target) :record) ((cl:lambda (rt) (hydra_lib_lists_concat ((hydra_lib_lists_map (cl:lambda (ft) (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_field_type-type v)) ft)))) ((cl:lambda (v) (hydra_core_row_type-fields v)) rt)))) match_value)) ((equal (car match_target) :set) ((cl:lambda (elem_type) (hydra_encoding_encoder_collect_type_vars_from_type elem_type)) match_value)) ((equal (car match_target) :union) ((cl:lambda (rt) (hydra_lib_lists_concat ((hydra_lib_lists_map (cl:lambda (ft) (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_field_type-type v)) ft)))) ((cl:lambda (v) (hydra_core_row_type-fields v)) rt)))) match_value)) ((equal (car match_target) :variable) ((cl:lambda (name) (cl:list name)) match_value)) ((equal (car match_target) :wrap) ((cl:lambda (wt) (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_wrapped_type-body v)) wt))) match_value)) (t (cl:list)))) (cadr match_target))) typ)))

(cl:defvar hydra_encoding_encoder_collect_ord_vars (cl:lambda (typ) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :annotated) ((cl:lambda (at) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_annotated_type-body v)) at))) match_value)) ((equal (car match_target) :application) ((cl:lambda (app_type) ((hydra_lib_lists_concat2 (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_application_type-function v)) app_type))) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_application_type-argument v)) app_type)))) match_value)) ((equal (car match_target) :either) ((cl:lambda (et) ((hydra_lib_lists_concat2 (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_either_type-left v)) et))) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_either_type-right v)) et)))) match_value)) ((equal (car match_target) :forall) ((cl:lambda (ft) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_forall_type-body v)) ft))) match_value)) ((equal (car match_target) :list) ((cl:lambda (elem_type) (hydra_encoding_encoder_collect_ord_vars elem_type)) match_value)) ((equal (car match_target) :map) ((cl:lambda (mt) (hydra_lib_lists_concat (cl:list (hydra_encoding_encoder_collect_type_vars_from_type ((cl:lambda (v) (hydra_core_map_type-keys v)) mt)) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_map_type-keys v)) mt)) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_map_type-values v)) mt))))) match_value)) ((equal (car match_target) :maybe) ((cl:lambda (elem_type) (hydra_encoding_encoder_collect_ord_vars elem_type)) match_value)) ((equal (car match_target) :pair) ((cl:lambda (pt) ((hydra_lib_lists_concat2 (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_pair_type-first v)) pt))) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_pair_type-second v)) pt)))) match_value)) ((equal (car match_target) :record) ((cl:lambda (rt) (hydra_lib_lists_concat ((hydra_lib_lists_map (cl:lambda (ft) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_field_type-type v)) ft)))) ((cl:lambda (v) (hydra_core_row_type-fields v)) rt)))) match_value)) ((equal (car match_target) :set) ((cl:lambda (elem_type) ((hydra_lib_lists_concat2 (hydra_encoding_encoder_collect_type_vars_from_type elem_type)) (hydra_encoding_encoder_collect_ord_vars elem_type))) match_value)) ((equal (car match_target) :union) ((cl:lambda (rt) (hydra_lib_lists_concat ((hydra_lib_lists_map (cl:lambda (ft) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_field_type-type v)) ft)))) ((cl:lambda (v) (hydra_core_row_type-fields v)) rt)))) match_value)) ((equal (car match_target) :wrap) ((cl:lambda (wt) (hydra_encoding_encoder_collect_ord_vars ((cl:lambda (v) (hydra_core_wrapped_type-body v)) wt))) match_value)) (t (cl:list)))) (cadr match_target))) typ)))

(cl:defvar hydra_encoding_encoder_full_result_type (cl:lambda (typ) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :annotated) ((cl:lambda (at) (hydra_encoding_encoder_full_result_type ((cl:lambda (v) (hydra_core_annotated_type-body v)) at))) match_value)) ((equal (car match_target) :application) ((cl:lambda (app_type) (list :application (make-hydra_core_application_type (hydra_encoding_encoder_full_result_type ((cl:lambda (v) (hydra_core_application_type-function v)) app_type)) ((cl:lambda (v) (hydra_core_application_type-argument v)) app_type)))) match_value)) ((equal (car match_target) :either) ((cl:lambda (et) (list :either (make-hydra_core_either_type (hydra_encoding_encoder_full_result_type ((cl:lambda (v) (hydra_core_either_type-left v)) et)) (hydra_encoding_encoder_full_result_type ((cl:lambda (v) (hydra_core_either_type-right v)) et))))) match_value)) ((equal (car match_target) :forall) ((cl:lambda (ft) (list :application (make-hydra_core_application_type (hydra_encoding_encoder_full_result_type ((cl:lambda (v) (hydra_core_forall_type-body v)) ft)) (list :variable ((cl:lambda (v) (hydra_core_forall_type-parameter v)) ft))))) match_value)) ((equal (car match_target) :list) ((cl:lambda (elem_type) (list :list (hydra_encoding_encoder_full_result_type elem_type))) match_value)) ((equal (car match_target) :literal) ((cl:lambda (_) (list :variable "hydra.core.Literal")) match_value)) ((equal (car match_target) :map) ((cl:lambda (mt) (list :map (make-hydra_core_map_type (hydra_encoding_encoder_full_result_type ((cl:lambda (v) (hydra_core_map_type-keys v)) mt)) (hydra_encoding_encoder_full_result_type ((cl:lambda (v) (hydra_core_map_type-values v)) mt))))) match_value)) ((equal (car match_target) :maybe) ((cl:lambda (elem_type) (list :maybe (hydra_encoding_encoder_full_result_type elem_type))) match_value)) ((equal (car match_target) :pair) ((cl:lambda (pt) (list :pair (make-hydra_core_pair_type (hydra_encoding_encoder_full_result_type ((cl:lambda (v) (hydra_core_pair_type-first v)) pt)) (hydra_encoding_encoder_full_result_type ((cl:lambda (v) (hydra_core_pair_type-second v)) pt))))) match_value)) ((equal (car match_target) :record) ((cl:lambda (rt) (list :variable ((cl:lambda (v) (hydra_core_row_type-type_name v)) rt))) match_value)) ((equal (car match_target) :set) ((cl:lambda (elem_type) (list :set (hydra_encoding_encoder_full_result_type elem_type))) match_value)) ((equal (car match_target) :union) ((cl:lambda (rt) (list :variable ((cl:lambda (v) (hydra_core_row_type-type_name v)) rt))) match_value)) ((equal (car match_target) :unit) ((cl:lambda (_) (list :unit cl:nil)) match_value)) ((equal (car match_target) :variable) ((cl:lambda (name) (list :variable name)) match_value)) ((equal (car match_target) :wrap) ((cl:lambda (wt) (list :variable ((cl:lambda (v) (hydra_core_wrapped_type-type_name v)) wt))) match_value)) (t (list :variable "hydra.core.Term")))) (cadr match_target))) typ)))

(cl:defvar hydra_encoding_prepend_forall_encoders (cl:lambda (base_type) (cl:lambda (typ) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :annotated) ((cl:lambda (at) ((hydra_encoding_prepend_forall_encoders base_type) ((cl:lambda (v) (hydra_core_annotated_type-body v)) at))) match_value)) ((equal (car match_target) :forall) ((cl:lambda (ft) (list :function (make-hydra_core_function_type (list :function (make-hydra_core_function_type (list :variable ((cl:lambda (v) (hydra_core_forall_type-parameter v)) ft)) (list :variable "hydra.core.Term"))) ((hydra_encoding_prepend_forall_encoders base_type) ((cl:lambda (v) (hydra_core_forall_type-body v)) ft))))) match_value)) (t base_type))) (cadr match_target))) typ))))

(cl:defvar hydra_encoding_encoder_type (cl:lambda (typ) (let ((result_type (hydra_encoding_encoder_full_result_type typ))) (let ((base_type (list :function (make-hydra_core_function_type result_type (list :variable "hydra.core.Term"))))) ((hydra_encoding_prepend_forall_encoders base_type) typ)))))

(cl:defvar hydra_encoding_encoder_type_scheme (cl:lambda (typ) (let* ((all_ord_vars (hydra_encoding_encoder_collect_ord_vars typ)) (type_vars (hydra_encoding_encoder_collect_forall_variables typ)) (ord_vars ((hydra_lib_lists_filter (cl:lambda (v) ((hydra_lib_lists_elem v) type_vars))) all_ord_vars)) (constraints (if (hydra_lib_lists_null ord_vars) cl:nil (hydra_lib_maps_from_list ((hydra_lib_lists_map (cl:lambda (v) (cl:list v (make-hydra_core_type_variable_metadata (hydra_lib_sets_singleton "ordering"))))) ord_vars)))) (encoder_fun_type (hydra_encoding_encoder_type typ))) (make-hydra_core_type_scheme type_vars encoder_fun_type constraints))))

(cl:defvar hydra_encoding_encode_binding (cl:lambda (cx) (cl:lambda (graph) (cl:lambda (b) ((hydra_lib_eithers_bind (((hydra_lib_eithers_bimap (cl:lambda (_wc_e) (make-hydra_context_in_context _wc_e cx))) (cl:lambda (_wc_a) _wc_a)) ((hydra_decode_core_type graph) ((cl:lambda (v) (hydra_core_binding-term v)) b)))) (cl:lambda (typ) (list :right (make-hydra_core_binding (hydra_encoding_encode_binding_name ((cl:lambda (v) (hydra_core_binding-name v)) b)) (hydra_encoding_encode_type typ) (hydra_encoding_encoder_type_scheme typ)))))))))

(cl:defvar hydra_encoding_encode_namespace (cl:lambda (ns_) (hydra_lib_strings_cat (cl:list "hydra.encode." ((hydra_lib_strings_intercalate ".") (hydra_lib_lists_tail ((hydra_lib_strings_split_on ".") ((cl:lambda (v) v) ns_))))))))

(cl:defvar hydra_encoding_is_encodable_binding (cl:lambda (cx) (cl:lambda (graph) (cl:lambda (b) ((hydra_lib_eithers_bind (((hydra_schemas_is_serializable_by_name cx) graph) ((cl:lambda (v) (hydra_core_binding-name v)) b))) (cl:lambda (serializable) (list :right (if serializable b cl:nil))))))))

(cl:defvar hydra_encoding_filter_type_bindings (cl:lambda (cx) (cl:lambda (graph) (cl:lambda (bindings) ((hydra_lib_eithers_map hydra_lib_maybes_cat) ((hydra_lib_eithers_map_list ((hydra_encoding_is_encodable_binding cx) graph)) ((hydra_lib_lists_filter hydra_annotations_is_native_type) bindings)))))))

(cl:defvar hydra_encoding_encode_module (cl:lambda (cx) (cl:lambda (graph) (cl:lambda (mod) ((hydra_lib_eithers_bind (((hydra_encoding_filter_type_bindings cx) graph) ((cl:lambda (v) (hydra_module_module-elements v)) mod))) (cl:lambda (type_bindings) (if (hydra_lib_lists_null type_bindings) (list :right cl:nil) ((hydra_lib_eithers_bind ((hydra_lib_eithers_map_list (cl:lambda (b) (((hydra_lib_eithers_bimap (cl:lambda (ic) (make-hydra_context_in_context ((cl:lambda (v) v) ((cl:lambda (v) (hydra_context_in_context-object v)) ic)) ((cl:lambda (v) (hydra_context_in_context-context v)) ic)))) (cl:lambda (x) x)) (((hydra_encoding_encode_binding cx) graph) b)))) type_bindings)) (cl:lambda (encoded_bindings) (list :right (make-hydra_module_module (hydra_encoding_encode_namespace ((cl:lambda (v) (hydra_module_module-namespace v)) mod)) encoded_bindings (hydra_lib_lists_nub ((hydra_lib_lists_concat2 ((hydra_lib_lists_map hydra_encoding_encode_namespace) ((cl:lambda (v) (hydra_module_module-type_dependencies v)) mod))) ((hydra_lib_lists_map hydra_encoding_encode_namespace) ((cl:lambda (v) (hydra_module_module-term_dependencies v)) mod)))) (cl:list ((cl:lambda (v) (hydra_module_module-namespace v)) mod)) (hydra_lib_strings_cat (cl:list "Term encoders for " ((cl:lambda (v) v) ((cl:lambda (v) (hydra_module_module-namespace v)) mod)))))))))))))))

(cl:defvar hydra_encoding_is_unit_type (cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :unit) ((cl:lambda (_) cl:t) match_value)) (t cl:nil))) (cadr match_target))))
