package hydra.ext.python.testing

import hydra.packaging.*

import hydra.testing.*

import hydra.lib.chars

import hydra.lib.eithers

import hydra.lib.equality

import hydra.lib.lists

import hydra.lib.logic

import hydra.lib.strings

def buildPythonTestModule[T0](testModule: T0)(testGroup: hydra.testing.TestGroup)(testBody: scala.Predef.String): scala.Predef.String =
  {
  lazy val `groupName_`: scala.Predef.String = (testGroup.name)
  lazy val header: scala.Predef.String = hydra.lib.strings.cat(Seq(hydra.lib.strings.cat2("# ")(hydra.constants.warningAutoGeneratedFile),
     "\n", hydra.lib.strings.cat2("# ")(`groupName_`), "\n\n"))
  hydra.lib.strings.cat(Seq(header, testBody, "\n"))
}

def formatPythonTestName(name: scala.Predef.String): scala.Predef.String =
  hydra.lib.strings.cat2("test_")(hydra.lib.strings.fromList(hydra.lib.lists.map[Int, Int]((c: Int) =>
  hydra.lib.logic.ifElse[Int](hydra.lib.chars.isAlphaNum(c))(hydra.lib.chars.toLower(c))(95))(hydra.lib.strings.toList(name))))

def generatePythonTestCase[T0](groupPath: Seq[scala.Predef.String])(tcm: hydra.testing.TestCaseWithMetadata): Either[T0, Seq[scala.Predef.String]] =
  {
  lazy val `name_`: scala.Predef.String = (tcm.name)
  lazy val tcase: hydra.testing.TestCase = (tcm.`case`)
  tcase match
    case hydra.testing.TestCase.universal(v_TestCase_universal_ucase) => {
      lazy val `actual_`: scala.Predef.String = (v_TestCase_universal_ucase.actual)
      lazy val `expected_`: scala.Predef.String = (v_TestCase_universal_ucase.expected)
      lazy val fullName: scala.Predef.String = hydra.lib.logic.ifElse[scala.Predef.String](hydra.lib.lists.`null`[scala.Predef.String](groupPath))(`name_`)(hydra.lib.strings.intercalate("__")(hydra.lib.lists.concat2[scala.Predef.String](groupPath)(Seq(`name_`))))
      lazy val formattedName: scala.Predef.String = hydra.ext.python.testing.formatPythonTestName(fullName)
      Right(Seq(hydra.lib.strings.cat(Seq("def ", formattedName, "():")), hydra.lib.strings.cat(Seq("    assert (", `actual_`, ") == (", `expected_`, ")"))))
    }
}

def generatePythonTestFile[T0, T1](testModule: hydra.packaging.Module)(testGroup: hydra.testing.TestGroup)(_g: T0): Either[T1,
   Tuple2[scala.Predef.String, scala.Predef.String]] = hydra.ext.python.testing.generateTestFileWithPythonCodec(testModule)(testGroup)

def generatePythonTestGroupHierarchy[T0](groupPath: Seq[scala.Predef.String])(testGroup: hydra.testing.TestGroup): Either[T0, scala.Predef.String] =
  {
  lazy val `cases_`: Seq[hydra.testing.TestCaseWithMetadata] = (testGroup.cases)
  lazy val subgroups: Seq[hydra.testing.TestGroup] = (testGroup.subgroups)
  hydra.lib.eithers.bind[T0, Seq[Seq[scala.Predef.String]], scala.Predef.String](hydra.lib.eithers.mapList[hydra.testing.TestCaseWithMetadata,
     Seq[scala.Predef.String], T0]((tc: hydra.testing.TestCaseWithMetadata) =>
    hydra.ext.python.testing.generatePythonTestCase(groupPath)(tc))(`cases_`))((testCaseLines: Seq[Seq[scala.Predef.String]]) =>
    hydra.lib.eithers.bind[T0, Seq[scala.Predef.String], scala.Predef.String](hydra.lib.eithers.mapList[hydra.testing.TestGroup,
       scala.Predef.String, T0]((subgroup: hydra.testing.TestGroup) =>
    {
    lazy val groupName: scala.Predef.String = (subgroup.name)
    lazy val header: scala.Predef.String = hydra.lib.strings.cat2("# ")(groupName)
    hydra.lib.eithers.map[scala.Predef.String, scala.Predef.String, T0]((content: scala.Predef.String) => hydra.lib.strings.cat(Seq(header,
       "\n\n", content)))(hydra.ext.python.testing.generatePythonTestGroupHierarchy(hydra.lib.lists.concat2[scala.Predef.String](groupPath)(Seq(groupName)))(subgroup))
  })(subgroups))((subgroupBlocks: Seq[scala.Predef.String]) =>
    {
    lazy val testCasesStr: scala.Predef.String = hydra.lib.strings.intercalate("\n\n")(hydra.lib.lists.concat[scala.Predef.String](testCaseLines))
    lazy val subgroupsStr: scala.Predef.String = hydra.lib.strings.intercalate("\n\n")(subgroupBlocks)
    Right(hydra.lib.strings.cat(Seq(testCasesStr, hydra.lib.logic.ifElse[scala.Predef.String](hydra.lib.logic.or(hydra.lib.equality.equal[scala.Predef.String](testCasesStr)(""))(hydra.lib.equality.equal[scala.Predef.String](subgroupsStr)("")))("")("\n\n"),
       subgroupsStr)))
  }))
}

def generateTestFileWithPythonCodec[T0](testModule: hydra.packaging.Module)(testGroup: hydra.testing.TestGroup): Either[T0,
   Tuple2[scala.Predef.String, scala.Predef.String]] =
  hydra.lib.eithers.map[scala.Predef.String, Tuple2[scala.Predef.String, scala.Predef.String], T0]((testBody: scala.Predef.String) =>
  {
  lazy val testModuleContent: scala.Predef.String = hydra.ext.python.testing.buildPythonTestModule(testModule)(testGroup)(testBody)
  lazy val `ns_`: hydra.packaging.Namespace = (testModule.namespace)
  lazy val parts: Seq[scala.Predef.String] = hydra.lib.strings.splitOn(".")(`ns_`)
  lazy val dirParts: Seq[scala.Predef.String] = hydra.lib.lists.init[scala.Predef.String](parts)
  lazy val fileName: scala.Predef.String = hydra.lib.strings.cat(Seq("test_", hydra.lib.lists.last[scala.Predef.String](parts), ".py"))
  lazy val filePath: scala.Predef.String = hydra.lib.strings.cat(Seq(hydra.lib.strings.intercalate("/")(dirParts), "/", fileName))
  Tuple2(filePath, testModuleContent)
})(hydra.ext.python.testing.generatePythonTestGroupHierarchy(Seq())(testGroup))
