(defpackage :hydra.decode.relational
(:use :cl :hydra.core :hydra.errors :hydra.extract.core :hydra.lib.eithers :hydra.relational)
(:export :hydra_decode_relational_column_name :hydra_decode_relational_column_schema :hydra_decode_relational_relation_name :hydra_decode_relational_foreign_key :hydra_decode_relational_primary_key :hydra_decode_relational_row :hydra_decode_relational_relation :hydra_decode_relational_relation_schema :hydra_decode_relational_relationship))

(in-package :hydra.decode.relational)

(cl:defvar hydra_decode_relational_column_name (cl:lambda (cx) (cl:lambda (raw) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :wrap) ((cl:lambda (wrapped_term) ((hydra_lib_eithers_map (cl:lambda (b) b)) (((cl:lambda (cx2) (cl:lambda (raw2) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped2) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :literal) ((cl:lambda (v) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :string) ((cl:lambda (s) (list :right s)) match_value)) (t (list :left "expected string literal")))) (cadr match_target))) v)) match_value)) (t (list :left "expected literal")))) (cadr match_target))) stripped2))) ((hydra_extract_core_strip_with_decoding_error cx2) raw2)))) cx) ((cl:lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw)))))

(cl:defvar hydra_decode_relational_column_schema (cl:lambda (t_) (cl:lambda (cx) (cl:lambda (raw) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :record) ((cl:lambda (record) (let ((field_map (hydra_extract_core_to_field_map record))) ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "name") hydra_decode_relational_column_name) field_map) cx)) (cl:lambda (field_name) ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "domain") t_) field_map) cx)) (cl:lambda (field_domain) (list :right (make-hydra_relational_column_schema field_name field_domain)))))))) match_value)) (t (list :left "expected record")))) (cadr match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw))))))

(cl:defvar hydra_decode_relational_relation_name (cl:lambda (cx) (cl:lambda (raw) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :wrap) ((cl:lambda (wrapped_term) ((hydra_lib_eithers_map (cl:lambda (b) b)) (((cl:lambda (cx2) (cl:lambda (raw2) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped2) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :literal) ((cl:lambda (v) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :string) ((cl:lambda (s) (list :right s)) match_value)) (t (list :left "expected string literal")))) (cadr match_target))) v)) match_value)) (t (list :left "expected literal")))) (cadr match_target))) stripped2))) ((hydra_extract_core_strip_with_decoding_error cx2) raw2)))) cx) ((cl:lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw)))))

(cl:defvar hydra_decode_relational_foreign_key (cl:lambda (cx) (cl:lambda (raw) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :record) ((cl:lambda (record) (let ((field_map (hydra_extract_core_to_field_map record))) ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "foreignRelation") hydra_decode_relational_relation_name) field_map) cx)) (cl:lambda (field_foreign_relation) ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "keys") ((hydra_extract_core_decode_map hydra_decode_relational_column_name) hydra_decode_relational_column_name)) field_map) cx)) (cl:lambda (field_keys) (list :right (make-hydra_relational_foreign_key field_foreign_relation field_keys)))))))) match_value)) (t (list :left "expected record")))) (cadr match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw)))))

(cl:defvar hydra_decode_relational_primary_key (cl:lambda (cx) (cl:lambda (raw) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :wrap) ((cl:lambda (wrapped_term) ((hydra_lib_eithers_map (cl:lambda (b) b)) (((hydra_extract_core_decode_list hydra_decode_relational_column_name) cx) ((cl:lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw)))))

(cl:defvar hydra_decode_relational_row (cl:lambda (v) (cl:lambda (cx) (cl:lambda (raw) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :wrap) ((cl:lambda (wrapped_term) ((hydra_lib_eithers_map (cl:lambda (b) b)) (((hydra_extract_core_decode_list v) cx) ((cl:lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw))))))

(cl:defvar hydra_decode_relational_relation (cl:lambda (v) (cl:lambda (cx) (cl:lambda (raw) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :wrap) ((cl:lambda (wrapped_term) ((hydra_lib_eithers_map (cl:lambda (b) b)) (((hydra_extract_core_decode_list (hydra_decode_relational_row v)) cx) ((cl:lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw))))))

(cl:defvar hydra_decode_relational_relation_schema (cl:lambda (t_) (cl:lambda (cx) (cl:lambda (raw) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :record) ((cl:lambda (record) (let ((field_map (hydra_extract_core_to_field_map record))) ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "name") hydra_decode_relational_relation_name) field_map) cx)) (cl:lambda (field_name) ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "columns") (hydra_extract_core_decode_list (hydra_decode_relational_column_schema t_))) field_map) cx)) (cl:lambda (field_columns) ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "primaryKeys") (hydra_extract_core_decode_list hydra_decode_relational_primary_key)) field_map) cx)) (cl:lambda (field_primary_keys) ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "foreignKeys") (hydra_extract_core_decode_list hydra_decode_relational_foreign_key)) field_map) cx)) (cl:lambda (field_foreign_keys) (list :right (make-hydra_relational_relation_schema field_name field_columns field_primary_keys field_foreign_keys)))))))))))) match_value)) (t (list :left "expected record")))) (cadr match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw))))))

(cl:defvar hydra_decode_relational_relationship (cl:lambda (v) (cl:lambda (cx) (cl:lambda (raw) (((hydra_lib_eithers_either (cl:lambda (err) (list :left err))) (cl:lambda (stripped) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :wrap) ((cl:lambda (wrapped_term) ((hydra_lib_eithers_map (cl:lambda (b) b)) (((hydra_extract_core_decode_set ((hydra_extract_core_decode_map hydra_decode_relational_column_name) v)) cx) ((cl:lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw))))))
