// Note: this is an automatically generated file. Do not edit.

package hydra.messages;

/**
 * A collection of standard error and warning messages
 */
public interface Messages {
  String warningAutoGeneratedFile = "Unimplemented term variant: TermVariantTyped";
}