(define-library (hydra ast)
(export hydra_ast_associativity-variants make-hydra_ast_block_style hydra_ast_block_style? hydra_ast_block_style-indent hydra_ast_block_style-newline_before_content hydra_ast_block_style-newline_after_content make-hydra_ast_bracket_expr hydra_ast_bracket_expr? hydra_ast_bracket_expr-brackets hydra_ast_bracket_expr-enclosed hydra_ast_bracket_expr-style make-hydra_ast_brackets hydra_ast_brackets? hydra_ast_brackets-open hydra_ast_brackets-close hydra_ast_expr-variants make-hydra_ast_indented_expression hydra_ast_indented_expression? hydra_ast_indented_expression-style hydra_ast_indented_expression-expr hydra_ast_indent_style-variants make-hydra_ast_op hydra_ast_op? hydra_ast_op-symbol hydra_ast_op-padding hydra_ast_op-precedence hydra_ast_op-associativity make-hydra_ast_op_expr hydra_ast_op_expr? hydra_ast_op_expr-op hydra_ast_op_expr-lhs hydra_ast_op_expr-rhs make-hydra_ast_padding hydra_ast_padding? hydra_ast_padding-left hydra_ast_padding-right make-hydra_ast_precedence hydra_ast_precedence? hydra_ast_precedence-value make-hydra_ast_symbol hydra_ast_symbol? hydra_ast_symbol-value hydra_ast_ws-variants)
(import (scheme base))
(begin
(define hydra_ast_associativity-variants (list 'none 'left 'right 'both))
(define-record-type hydra_ast_block_style (make-hydra_ast_block_style indent newline_before_content newline_after_content) hydra_ast_block_style? (indent hydra_ast_block_style-indent) (newline_before_content hydra_ast_block_style-newline_before_content) (newline_after_content hydra_ast_block_style-newline_after_content))
(define-record-type hydra_ast_bracket_expr (make-hydra_ast_bracket_expr brackets enclosed style) hydra_ast_bracket_expr? (brackets hydra_ast_bracket_expr-brackets) (enclosed hydra_ast_bracket_expr-enclosed) (style hydra_ast_bracket_expr-style))
(define-record-type hydra_ast_brackets (make-hydra_ast_brackets open close) hydra_ast_brackets? (open hydra_ast_brackets-open) (close hydra_ast_brackets-close))
(define hydra_ast_expr-variants (list 'const 'indent 'op 'brackets))
(define-record-type hydra_ast_indented_expression (make-hydra_ast_indented_expression style expr) hydra_ast_indented_expression? (style hydra_ast_indented_expression-style) (expr hydra_ast_indented_expression-expr))
(define hydra_ast_indent_style-variants (list 'all_lines 'subsequent_lines))
(define-record-type hydra_ast_op (make-hydra_ast_op symbol padding precedence associativity) hydra_ast_op? (symbol hydra_ast_op-symbol) (padding hydra_ast_op-padding) (precedence hydra_ast_op-precedence) (associativity hydra_ast_op-associativity))
(define-record-type hydra_ast_op_expr (make-hydra_ast_op_expr op lhs rhs) hydra_ast_op_expr? (op hydra_ast_op_expr-op) (lhs hydra_ast_op_expr-lhs) (rhs hydra_ast_op_expr-rhs))
(define-record-type hydra_ast_padding (make-hydra_ast_padding left right) hydra_ast_padding? (left hydra_ast_padding-left) (right hydra_ast_padding-right))
(define-record-type hydra_ast_precedence (make-hydra_ast_precedence value) hydra_ast_precedence? (value hydra_ast_precedence-value))
(define-record-type hydra_ast_symbol (make-hydra_ast_symbol value) hydra_ast_symbol? (value hydra_ast_symbol-value))
(define hydra_ast_ws-variants (list 'none 'space 'break 'break_and_indent 'double_break))))
