-- | A collection of standard error and warning messages

module Hydra.Messages where

import Prelude hiding  (Enum, Ordering, map, pure, sum)
import qualified Data.Int as I
import qualified Data.List as L
import qualified Data.Map as M
import qualified Data.Set as S

warningAutoGeneratedFile :: String
warningAutoGeneratedFile = "Note: this is an automatically generated file. Do not edit."
