-- | A collection of standard error and warning messages

module Hydra.Messages where

import Data.Int
import Data.List as L
import Data.Map as M
import Data.Set as S

warningAutoGeneratedFile :: String
warningAutoGeneratedFile = "Note: this is an automatically generated file. Do not edit."