// Note: this is an automatically generated file. Do not edit.

package hydra.ext.java;

/**
 * Java test code generation codec for JUnit-based generation tests
 */
public interface Testing {
  static String buildJavaTestModule(hydra.packaging.Module testModule, hydra.testing.TestGroup testGroup, String testBody) {
    hydra.packaging.Namespace ns_ = (testModule).namespace;
    hydra.util.ConsList<String> parts = hydra.lib.strings.SplitOn.apply(
      ".",
      (ns_).value);
    hydra.util.Lazy<String> className_ = new hydra.util.Lazy<>(() -> hydra.lib.strings.Cat2.apply(
      hydra.Formatting.capitalize(hydra.lib.lists.Last.apply(parts)),
      "Test"));
    String groupName_ = (testGroup).name;
    hydra.util.Lazy<String> packageName = new hydra.util.Lazy<>(() -> hydra.lib.strings.Intercalate.apply(
      ".",
      hydra.lib.lists.Init.apply(parts)));
    hydra.util.ConsList<String> standardImports = hydra.util.ConsList.of(
      "import org.junit.jupiter.api.Test;",
      "import static org.junit.jupiter.api.Assertions.*;",
      "import java.util.*;",
      "import hydra.util.*;");
    String header = hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
      hydra.lib.strings.Cat2.apply(
        "// ",
        hydra.Constants.warningAutoGeneratedFile()),
      "\n",
      hydra.lib.strings.Cat2.apply(
        "// ",
        groupName_),
      "\n\n",
      hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
        "package ",
        packageName.get(),
        ";\n\n")),
      hydra.lib.strings.Intercalate.apply(
        "\n",
        standardImports),
      "\n\n",
      hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
        "public class ",
        className_.get(),
        " {\n\n"))));
    return hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
      header,
      testBody,
      "\n}\n"));
  }

  static hydra.util.ConsList<String> findJavaImports() {
    return hydra.util.ConsList.of(
      "import org.junit.jupiter.api.Test;",
      "import static org.junit.jupiter.api.Assertions.*;",
      "import java.util.*;");
  }

  static String formatJavaTestName(String name) {
    String replaced = hydra.lib.strings.Intercalate.apply(
      " Neg",
      hydra.lib.strings.SplitOn.apply(
        "-",
        hydra.lib.strings.Intercalate.apply(
          "Dot",
          hydra.lib.strings.SplitOn.apply(
            ".",
            hydra.lib.strings.Intercalate.apply(
              " Plus",
              hydra.lib.strings.SplitOn.apply(
                "+",
                hydra.lib.strings.Intercalate.apply(
                  " Div",
                  hydra.lib.strings.SplitOn.apply(
                    "/",
                    hydra.lib.strings.Intercalate.apply(
                      " Mul",
                      hydra.lib.strings.SplitOn.apply(
                        "*",
                        hydra.lib.strings.Intercalate.apply(
                          " Num",
                          hydra.lib.strings.SplitOn.apply(
                            "#",
                            name))))))))))));
    String sanitized = hydra.Formatting.nonAlnumToUnderscores(replaced);
    String pascal_ = hydra.Formatting.convertCase(
      new hydra.util.CaseConvention.LowerSnake(),
      new hydra.util.CaseConvention.Pascal(),
      sanitized);
    return hydra.lib.strings.Cat2.apply(
      "test",
      pascal_);
  }

  static <T0> hydra.util.Either<T0, hydra.util.ConsList<String>> generateJavaTestCase(hydra.util.ConsList<String> groupPath, hydra.testing.TestCaseWithMetadata tcm) {
    String name_ = (tcm).name;
    hydra.testing.TestCase tcase = (tcm).case_;
    return (tcase).accept(new hydra.testing.TestCase.PartialVisitor<>() {
      @Override
      public hydra.util.Either<T0, hydra.util.ConsList<String>> visit(hydra.testing.TestCase.Universal ucase) {
        String actual_ = (ucase).value.actual;
        String expected_ = (ucase).value.expected;
        hydra.util.Lazy<String> fullName = new hydra.util.Lazy<>(() -> hydra.lib.logic.IfElse.lazy(
          hydra.lib.lists.Null.apply(groupPath),
          () -> name_,
          () -> hydra.lib.strings.Intercalate.apply(
            "_",
            hydra.lib.lists.Concat2.apply(
              groupPath,
              hydra.util.ConsList.of(name_)))));
        String formattedName = hydra.ext.java.Testing.formatJavaTestName(fullName.get());
        return hydra.util.Either.<T0, hydra.util.ConsList<String>>right(hydra.util.ConsList.of(
          "    @Test",
          hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
            "    public void ",
            formattedName,
            "() {")),
          "        assertEquals(",
          hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
            "            ",
            expected_,
            ",")),
          hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
            "            ",
            actual_,
            ");")),
          "    }"));
      }
    });
  }

  static <T0, T1> hydra.util.Either<T1, hydra.util.Pair<String, String>> generateJavaTestFile(hydra.packaging.Module testModule, hydra.testing.TestGroup testGroup, T0 _g) {
    return hydra.ext.java.Testing.<T1>generateTestFileWithJavaCodec(
      testModule,
      testGroup);
  }

  static <T0> hydra.util.Either<T0, String> generateJavaTestGroupHierarchy(hydra.util.ConsList<String> groupPath, hydra.testing.TestGroup testGroup) {
    hydra.util.ConsList<hydra.testing.TestCaseWithMetadata> cases_ = (testGroup).cases;
    hydra.util.ConsList<hydra.testing.TestGroup> subgroups = (testGroup).subgroups;
    return hydra.lib.eithers.Bind.apply(
      hydra.lib.eithers.Map.apply(
        (java.util.function.Function<hydra.util.ConsList<hydra.util.ConsList<String>>, String>) (lines_ -> hydra.lib.strings.Intercalate.apply(
          "\n\n",
          hydra.lib.lists.Concat.apply(lines_))),
        hydra.lib.eithers.MapList.apply(
          (java.util.function.Function<hydra.testing.TestCaseWithMetadata, hydra.util.Either<T0, hydra.util.ConsList<String>>>) (tc -> hydra.ext.java.Testing.<T0>generateJavaTestCase(
            groupPath,
            tc)),
          cases_)),
      (java.util.function.Function<String, hydra.util.Either<T0, String>>) (testCasesStr -> hydra.lib.eithers.Map.apply(
        (java.util.function.Function<String, String>) (subgroupsStr -> hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
          testCasesStr,
          hydra.lib.logic.IfElse.lazy(
            hydra.lib.logic.Or.apply(
              hydra.lib.equality.Equal.apply(
                testCasesStr,
                ""),
              hydra.lib.equality.Equal.apply(
                subgroupsStr,
                "")),
            () -> "",
            () -> "\n\n"),
          subgroupsStr))),
        hydra.lib.eithers.Map.apply(
          (java.util.function.Function<hydra.util.ConsList<String>, String>) (blocks -> hydra.lib.strings.Intercalate.apply(
            "\n\n",
            blocks)),
          hydra.lib.eithers.MapList.apply(
            (java.util.function.Function<hydra.testing.TestGroup, hydra.util.Either<T0, String>>) (subgroup -> {
              String groupName = (subgroup).name;
              String header = hydra.lib.strings.Cat2.apply(
                "    // ",
                groupName);
              return hydra.lib.eithers.Map.apply(
                (java.util.function.Function<String, String>) (content -> hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
                  header,
                  "\n\n",
                  content))),
                hydra.ext.java.Testing.<T0>generateJavaTestGroupHierarchy(
                  hydra.lib.lists.Concat2.apply(
                    groupPath,
                    hydra.util.ConsList.of(groupName)),
                  subgroup));
            }),
            subgroups)))));
  }

  static <T0> hydra.util.Either<T0, hydra.util.Pair<String, String>> generateTestFileWithJavaCodec(hydra.packaging.Module testModule, hydra.testing.TestGroup testGroup) {
    return hydra.lib.eithers.Map.apply(
      (java.util.function.Function<String, hydra.util.Pair<String, String>>) (testBody -> {
        hydra.packaging.Namespace ns_ = (testModule).namespace;
        hydra.util.ConsList<String> parts = hydra.lib.strings.SplitOn.apply(
          ".",
          (ns_).value);
        hydra.util.Lazy<String> className_ = new hydra.util.Lazy<>(() -> hydra.lib.strings.Cat2.apply(
          hydra.Formatting.capitalize(hydra.lib.lists.Last.apply(parts)),
          "Test"));
        hydra.util.Lazy<hydra.util.ConsList<String>> dirParts = new hydra.util.Lazy<>(() -> hydra.lib.lists.Drop.apply(
          1,
          hydra.lib.lists.Init.apply(parts)));
        String fileName = hydra.lib.strings.Cat2.apply(
          className_.get(),
          ".java");
        String filePath = hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
          hydra.lib.strings.Intercalate.apply(
            "/",
            dirParts.get()),
          "/",
          fileName));
        String testModuleContent = hydra.ext.java.Testing.buildJavaTestModule(
          testModule,
          testGroup,
          testBody);
        return (hydra.util.Pair<String, String>) ((hydra.util.Pair<String, String>) (new hydra.util.Pair<String, String>(filePath, testModuleContent)));
      }),
      hydra.ext.java.Testing.<T0>generateJavaTestGroupHierarchy(
        (hydra.util.ConsList<String>) (hydra.util.ConsList.<String>empty()),
        testGroup));
  }

  static String namespaceToJavaClassName(hydra.packaging.Namespace ns_) {
    return hydra.lib.strings.Intercalate.apply(
      ".",
      hydra.lib.lists.Map.apply(
        hydra.Formatting::capitalize,
        hydra.lib.strings.SplitOn.apply(
          ".",
          (ns_).value)));
  }
}
