(defpackage :hydra.ext.haskell.serde
(:use :cl :hydra.ast :hydra.constants :hydra.ext.haskell.ast :hydra.ext.haskell.operators :hydra.lib.equality :hydra.lib.lists :hydra.lib.literals :hydra.lib.logic :hydra.lib.maybes :hydra.lib.strings :hydra.serialization)
(:export :hydra_ext_haskell_serde_write_qualified_name :hydra_ext_haskell_serde_name_to_expr :hydra_ext_haskell_serde_literal_to_expr :hydra_ext_haskell_serde_application_pattern_to_expr :hydra_ext_haskell_serde_pattern_to_expr :hydra_ext_haskell_serde_assertion_to_expr :hydra_ext_haskell_serde_class_assertion_to_expr :hydra_ext_haskell_serde_type_to_expr :hydra_ext_haskell_serde_type_signature_to_expr :hydra_ext_haskell_serde_alternative_to_expr :hydra_ext_haskell_serde_application_expression_to_expr :hydra_ext_haskell_serde_case_expression_to_expr :hydra_ext_haskell_serde_case_rhs_to_expr :hydra_ext_haskell_serde_construct_record_expression_to_expr :hydra_ext_haskell_serde_expression_to_expr :hydra_ext_haskell_serde_if_expression_to_expr :hydra_ext_haskell_serde_lambda_expression_to_expr :hydra_ext_haskell_serde_local_binding_to_expr :hydra_ext_haskell_serde_right_hand_side_to_expr :hydra_ext_haskell_serde_statement_to_expr :hydra_ext_haskell_serde_value_binding_to_expr :hydra_ext_haskell_serde_field_to_expr :hydra_ext_haskell_serde_to_haskell_comments :hydra_ext_haskell_serde_field_with_comments_to_expr :hydra_ext_haskell_serde_constructor_to_expr :hydra_ext_haskell_serde_constructor_with_comments_to_expr :hydra_ext_haskell_serde_data_or_newtype_to_expr :hydra_ext_haskell_serde_variable_to_expr :hydra_ext_haskell_serde_declaration_head_to_expr :hydra_ext_haskell_serde_declaration_to_expr :hydra_ext_haskell_serde_declaration_with_comments_to_expr :hydra_ext_haskell_serde_import_export_spec_to_expr :hydra_ext_haskell_serde_import_to_expr :hydra_ext_haskell_serde_module_head_to_expr :hydra_ext_haskell_serde_to_simple_comments :hydra_ext_haskell_serde_module_to_expr))

(in-package :hydra.ext.haskell.serde)

(cl:defvar hydra_ext_haskell_serde_write_qualified_name (cl:lambda (qname) (let* ((h (cl:lambda (name_part) ((cl:lambda (v) v) name_part))) (qualifiers ((cl:lambda (v) (hydra_ext_haskell_ast_qualified_name-qualifiers v)) qname)) (unqual ((cl:lambda (v) (hydra_ext_haskell_ast_qualified_name-unqualified v)) qname)) (all_parts ((hydra_lib_lists_concat2 ((hydra_lib_lists_map h) qualifiers)) (cl:list (h unqual))))) ((hydra_lib_strings_intercalate ".") all_parts))))

(cl:defvar hydra_ext_haskell_serde_name_to_expr (cl:lambda (name) (hydra_serialization_cst ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :implicit) ((cl:lambda (qn) ((hydra_lib_strings_cat2 "?") (hydra_ext_haskell_serde_write_qualified_name qn))) match_value)) ((equal (car match_target) :normal) ((cl:lambda (qn) (hydra_ext_haskell_serde_write_qualified_name qn)) match_value)) ((equal (car match_target) :parens) ((cl:lambda (qn) (hydra_lib_strings_cat (cl:list "(" (hydra_ext_haskell_serde_write_qualified_name qn) ")"))) match_value)))) (cadr match_target))) name))))

(cl:defvar hydra_ext_haskell_serde_literal_to_expr (cl:lambda (lit) (let ((parens_if_neg (cl:lambda (b) (cl:lambda (e) (if b (hydra_lib_strings_cat (cl:list "(" e ")")) e))))) (hydra_serialization_cst ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :char) ((cl:lambda (c) (hydra_lib_literals_show_string (hydra_lib_literals_show_uint16 c))) match_value)) ((equal (car match_target) :double) ((cl:lambda (d) ((parens_if_neg ((hydra_lib_equality_lt d) 0.0)) (hydra_lib_literals_show_float64 d))) match_value)) ((equal (car match_target) :float) ((cl:lambda (f) ((parens_if_neg ((hydra_lib_equality_lt f) 0.0)) (hydra_lib_literals_show_float32 f))) match_value)) ((equal (car match_target) :int) ((cl:lambda (i) ((parens_if_neg ((hydra_lib_equality_lt i) 0)) (hydra_lib_literals_show_int32 i))) match_value)) ((equal (car match_target) :integer) ((cl:lambda (i) ((parens_if_neg ((hydra_lib_equality_lt i) 0)) (hydra_lib_literals_show_bigint i))) match_value)) ((equal (car match_target) :string) ((cl:lambda (s) (hydra_lib_literals_show_string s)) match_value)))) (cadr match_target))) lit)))))

(cl:defvar hydra_ext_haskell_serde_application_pattern_to_expr (cl:lambda (app_pat) (let* ((name ((cl:lambda (v) (hydra_ext_haskell_ast_application_pattern-name v)) app_pat)) (pats ((cl:lambda (v) (hydra_ext_haskell_ast_application_pattern-args v)) app_pat))) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_ext_haskell_serde_name_to_expr name)) ((hydra_lib_lists_map hydra_ext_haskell_serde_pattern_to_expr) pats))))))

(cl:defvar hydra_ext_haskell_serde_pattern_to_expr (cl:lambda (pat) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :application) ((cl:lambda (app) (hydra_ext_haskell_serde_application_pattern_to_expr app)) match_value)) ((equal (car match_target) :list) ((cl:lambda (pats) ((hydra_serialization_bracket_list hydra_serialization_half_block_style) ((hydra_lib_lists_map hydra_ext_haskell_serde_pattern_to_expr) pats))) match_value)) ((equal (car match_target) :literal) ((cl:lambda (lit) (hydra_ext_haskell_serde_literal_to_expr lit)) match_value)) ((equal (car match_target) :name) ((cl:lambda (name) (hydra_ext_haskell_serde_name_to_expr name)) match_value)) ((equal (car match_target) :parens) ((cl:lambda (pat_) (hydra_serialization_parenthesize (hydra_ext_haskell_serde_pattern_to_expr pat_))) match_value)) ((equal (car match_target) :tuple) ((cl:lambda (pats) ((hydra_serialization_paren_list cl:nil) ((hydra_lib_lists_map hydra_ext_haskell_serde_pattern_to_expr) pats))) match_value)) ((equal (car match_target) :wildcard) ((cl:lambda (_) (hydra_serialization_cst "_")) match_value)))) (cadr match_target))) pat)))

(cl:defvar hydra_ext_haskell_serde_assertion_to_expr (cl:lambda (sert) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :class) ((cl:lambda (cls) (hydra_ext_haskell_serde_class_assertion_to_expr cls)) match_value)) ((equal (car match_target) :tuple) ((cl:lambda (serts) ((hydra_serialization_paren_list cl:nil) ((hydra_lib_lists_map hydra_ext_haskell_serde_assertion_to_expr) serts))) match_value)))) (cadr match_target))) sert)))

(cl:defvar hydra_ext_haskell_serde_class_assertion_to_expr (cl:lambda (cls_asrt) (let* ((name ((cl:lambda (v) (hydra_ext_haskell_ast_class_assertion-name v)) cls_asrt)) (types ((cl:lambda (v) (hydra_ext_haskell_ast_class_assertion-types v)) cls_asrt))) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_ext_haskell_serde_name_to_expr name)) (cl:list ((hydra_serialization_comma_sep hydra_serialization_half_block_style) ((hydra_lib_lists_map hydra_ext_haskell_serde_type_to_expr) types))))))))

(cl:defvar hydra_ext_haskell_serde_type_to_expr (cl:lambda (htype) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :application) ((cl:lambda (app_type) (let* ((lhs ((cl:lambda (v) (hydra_ext_haskell_ast_application_type-context v)) app_type)) (rhs ((cl:lambda (v) (hydra_ext_haskell_ast_application_type-argument v)) app_type))) (((hydra_serialization_ifx hydra_ext_haskell_operators_app_op) (hydra_ext_haskell_serde_type_to_expr lhs)) (hydra_ext_haskell_serde_type_to_expr rhs)))) match_value)) ((equal (car match_target) :ctx) ((cl:lambda (ctx_type) (let* ((ctx ((cl:lambda (v) (hydra_ext_haskell_ast_context_type-ctx v)) ctx_type)) (typ ((cl:lambda (v) (hydra_ext_haskell_ast_context_type-type v)) ctx_type))) (((hydra_serialization_ifx hydra_ext_haskell_operators_assert_op) (hydra_ext_haskell_serde_assertion_to_expr ctx)) (hydra_ext_haskell_serde_type_to_expr typ)))) match_value)) ((equal (car match_target) :function) ((cl:lambda (fun_type) (let* ((cod ((cl:lambda (v) (hydra_ext_haskell_ast_function_type-codomain v)) fun_type)) (dom ((cl:lambda (v) (hydra_ext_haskell_ast_function_type-domain v)) fun_type))) (((hydra_serialization_ifx hydra_ext_haskell_operators_arrow_op) (hydra_ext_haskell_serde_type_to_expr dom)) (hydra_ext_haskell_serde_type_to_expr cod)))) match_value)) ((equal (car match_target) :list) ((cl:lambda (htype_) ((hydra_serialization_bracket_list hydra_serialization_inline_style) (cl:list (hydra_ext_haskell_serde_type_to_expr htype_)))) match_value)) ((equal (car match_target) :tuple) ((cl:lambda (types) ((hydra_serialization_paren_list cl:nil) ((hydra_lib_lists_map hydra_ext_haskell_serde_type_to_expr) types))) match_value)) ((equal (car match_target) :variable) ((cl:lambda (name) (hydra_ext_haskell_serde_name_to_expr name)) match_value)))) (cadr match_target))) htype)))

(cl:defvar hydra_ext_haskell_serde_type_signature_to_expr (cl:lambda (type_sig) (let* ((name ((cl:lambda (v) (hydra_ext_haskell_ast_type_signature-name v)) type_sig)) (name_expr (hydra_ext_haskell_serde_name_to_expr name)) (typ ((cl:lambda (v) (hydra_ext_haskell_ast_type_signature-type v)) type_sig)) (type_expr (hydra_ext_haskell_serde_type_to_expr typ)) (inline_sig (hydra_serialization_structural_space_sep (cl:list name_expr (hydra_serialization_cst "::") type_expr)))) (if ((hydra_lib_equality_gt (hydra_serialization_expression_length inline_sig)) 120) (hydra_serialization_newline_sep (cl:list (hydra_serialization_space_sep (cl:list name_expr (hydra_serialization_cst "::"))) (hydra_serialization_tab_indent type_expr))) inline_sig))))

(cl:defvar hydra_ext_haskell_serde_alternative_to_expr (cl:lambda (alt) (hydra_serialization_structural_space_sep (cl:list (hydra_ext_haskell_serde_pattern_to_expr ((cl:lambda (v) (hydra_ext_haskell_ast_alternative-pattern v)) alt)) (hydra_serialization_cst "->") (hydra_ext_haskell_serde_case_rhs_to_expr ((cl:lambda (v) (hydra_ext_haskell_ast_alternative-rhs v)) alt))))))

(cl:defvar hydra_ext_haskell_serde_application_expression_to_expr (cl:lambda (app) (((hydra_serialization_ifx hydra_ext_haskell_operators_app_op) (hydra_ext_haskell_serde_expression_to_expr ((cl:lambda (v) (hydra_ext_haskell_ast_application_expression-function v)) app))) (hydra_ext_haskell_serde_expression_to_expr ((cl:lambda (v) (hydra_ext_haskell_ast_application_expression-argument v)) app)))))

(cl:defvar hydra_ext_haskell_serde_case_expression_to_expr (cl:lambda (case_expr) (let* ((alts ((cl:lambda (v) (hydra_ext_haskell_ast_case_expression-alternatives v)) case_expr)) (cs ((cl:lambda (v) (hydra_ext_haskell_ast_case_expression-case v)) case_expr)) (lhs (hydra_serialization_space_sep (cl:list (hydra_serialization_cst "case") (hydra_ext_haskell_serde_expression_to_expr cs)))) (of_op (make-hydra_ast_op "of" (make-hydra_ast_padding (list :space cl:nil) (list :break_and_indent "  ")) 0 (list :none cl:nil))) (rhs (hydra_serialization_newline_sep ((hydra_lib_lists_map hydra_ext_haskell_serde_alternative_to_expr) alts)))) (((hydra_serialization_ifx of_op) lhs) rhs))))

(cl:defvar hydra_ext_haskell_serde_case_rhs_to_expr (cl:lambda (rhs) (hydra_ext_haskell_serde_expression_to_expr ((cl:lambda (v) v) rhs))))

(cl:defvar hydra_ext_haskell_serde_construct_record_expression_to_expr (cl:lambda (construct_record) (let* ((from_update (cl:lambda (update) (let* ((fn_ ((cl:lambda (v) (hydra_ext_haskell_ast_field_update-name v)) update)) (val ((cl:lambda (v) (hydra_ext_haskell_ast_field_update-value v)) update))) (((hydra_serialization_ifx hydra_ext_haskell_operators_define_op) (hydra_ext_haskell_serde_name_to_expr fn_)) (hydra_ext_haskell_serde_expression_to_expr val))))) (updates ((cl:lambda (v) (hydra_ext_haskell_ast_construct_record_expression-fields v)) construct_record)) (body ((hydra_serialization_comma_sep hydra_serialization_half_block_style) ((hydra_lib_lists_map from_update) updates))) (name ((cl:lambda (v) (hydra_ext_haskell_ast_construct_record_expression-name v)) construct_record))) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_ext_haskell_serde_name_to_expr name)) (cl:list (((hydra_serialization_brackets hydra_serialization_curly_braces) hydra_serialization_half_block_style) body)))))))

(cl:defvar hydra_ext_haskell_serde_expression_to_expr (cl:lambda (expr) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :application) ((cl:lambda (app) (hydra_ext_haskell_serde_application_expression_to_expr app)) match_value)) ((equal (car match_target) :case) ((cl:lambda (cases) (hydra_ext_haskell_serde_case_expression_to_expr cases)) match_value)) ((equal (car match_target) :construct_record) ((cl:lambda (r) (hydra_ext_haskell_serde_construct_record_expression_to_expr r)) match_value)) ((equal (car match_target) :do) ((cl:lambda (statements) (hydra_serialization_indent_block ((hydra_lib_lists_cons (hydra_serialization_cst "do")) ((hydra_lib_lists_map hydra_ext_haskell_serde_statement_to_expr) statements)))) match_value)) ((equal (car match_target) :if) ((cl:lambda (ifte) (hydra_ext_haskell_serde_if_expression_to_expr ifte)) match_value)) ((equal (car match_target) :literal) ((cl:lambda (lit) (hydra_ext_haskell_serde_literal_to_expr lit)) match_value)) ((equal (car match_target) :lambda) ((cl:lambda (lam) (hydra_serialization_parenthesize (hydra_ext_haskell_serde_lambda_expression_to_expr lam))) match_value)) ((equal (car match_target) :let) ((cl:lambda (let_expr) (let* ((bindings ((cl:lambda (v) (hydra_ext_haskell_ast_let_expression-bindings v)) let_expr)) (encode_binding (cl:lambda (binding) ((hydra_serialization_indent_subsequent_lines "    ") (hydra_ext_haskell_serde_local_binding_to_expr binding)))) (inner ((cl:lambda (v) (hydra_ext_haskell_ast_let_expression-inner v)) let_expr))) (hydra_serialization_indent_block ((hydra_lib_lists_cons (hydra_serialization_cst "")) ((hydra_lib_lists_cons (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_serialization_cst "let")) (cl:list ((hydra_serialization_custom_indent_block "    ") ((hydra_lib_lists_map encode_binding) bindings)))))) (cl:list (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_serialization_cst "in")) (cl:list (hydra_ext_haskell_serde_expression_to_expr inner)))))))))) match_value)) ((equal (car match_target) :list) ((cl:lambda (exprs) ((hydra_serialization_bracket_list hydra_serialization_half_block_style) ((hydra_lib_lists_map hydra_ext_haskell_serde_expression_to_expr) exprs))) match_value)) ((equal (car match_target) :parens) ((cl:lambda (expr_) (hydra_serialization_parenthesize (hydra_ext_haskell_serde_expression_to_expr expr_))) match_value)) ((equal (car match_target) :tuple) ((cl:lambda (exprs) ((hydra_serialization_paren_list cl:nil) ((hydra_lib_lists_map hydra_ext_haskell_serde_expression_to_expr) exprs))) match_value)) ((equal (car match_target) :variable) ((cl:lambda (name) (hydra_ext_haskell_serde_name_to_expr name)) match_value)))) (cadr match_target))) expr)))

(cl:defvar hydra_ext_haskell_serde_if_expression_to_expr (cl:lambda (if_expr) (let* ((eelse ((cl:lambda (v) (hydra_ext_haskell_ast_if_expression-else v)) if_expr)) (ethen ((cl:lambda (v) (hydra_ext_haskell_ast_if_expression-then v)) if_expr)) (body (hydra_serialization_newline_sep ((hydra_lib_lists_cons (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_serialization_cst "then")) (cl:list (hydra_ext_haskell_serde_expression_to_expr ethen))))) (cl:list (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_serialization_cst "else")) (cl:list (hydra_ext_haskell_serde_expression_to_expr eelse)))))))) (eif ((cl:lambda (v) (hydra_ext_haskell_ast_if_expression-condition v)) if_expr)) (if_op (make-hydra_ast_op "" (make-hydra_ast_padding (list :none cl:nil) (list :break_and_indent "  ")) 0 (list :none cl:nil)))) (((hydra_serialization_ifx if_op) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_serialization_cst "if")) (cl:list (hydra_ext_haskell_serde_expression_to_expr eif))))) body))))

(cl:defvar hydra_ext_haskell_serde_lambda_expression_to_expr (cl:lambda (lambda_expr) (let* ((bindings ((cl:lambda (v) (hydra_ext_haskell_ast_lambda_expression-bindings v)) lambda_expr)) (inner ((cl:lambda (v) (hydra_ext_haskell_ast_lambda_expression-inner v)) lambda_expr)) (body (hydra_ext_haskell_serde_expression_to_expr inner)) (head (hydra_serialization_space_sep ((hydra_lib_lists_map hydra_ext_haskell_serde_pattern_to_expr) bindings)))) (((hydra_serialization_ifx hydra_ext_haskell_operators_lambda_op) ((hydra_serialization_prefix "\\") head)) body))))

(cl:defvar hydra_ext_haskell_serde_local_binding_to_expr (cl:lambda (binding) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :signature) ((cl:lambda (ts) (hydra_ext_haskell_serde_type_signature_to_expr ts)) match_value)) ((equal (car match_target) :value) ((cl:lambda (vb) (hydra_ext_haskell_serde_value_binding_to_expr vb)) match_value)))) (cadr match_target))) binding)))

(cl:defvar hydra_ext_haskell_serde_right_hand_side_to_expr (cl:lambda (rhs) (hydra_ext_haskell_serde_expression_to_expr ((cl:lambda (v) v) rhs))))

(cl:defvar hydra_ext_haskell_serde_statement_to_expr (cl:lambda (stmt) (hydra_ext_haskell_serde_expression_to_expr ((cl:lambda (v) v) stmt))))

(cl:defvar hydra_ext_haskell_serde_value_binding_to_expr (cl:lambda (vb) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :simple) ((cl:lambda (simple_v_b) (let* ((pat ((cl:lambda (v) (hydra_ext_haskell_ast_simple_value_binding-pattern v)) simple_v_b)) (lhs_expr (hydra_ext_haskell_serde_pattern_to_expr pat)) (rhs ((cl:lambda (v) (hydra_ext_haskell_ast_simple_value_binding-rhs v)) simple_v_b)) (rhs_expr (hydra_ext_haskell_serde_right_hand_side_to_expr rhs)) (inline_body (hydra_serialization_structural_space_sep (cl:list lhs_expr (hydra_serialization_cst "=") rhs_expr))) (body (if ((hydra_lib_equality_gt (hydra_serialization_expression_length inline_body)) 120) (hydra_serialization_newline_sep (cl:list (hydra_serialization_space_sep (cl:list lhs_expr (hydra_serialization_cst "="))) (hydra_serialization_tab_indent rhs_expr))) inline_body)) (local ((cl:lambda (v) (hydra_ext_haskell_ast_simple_value_binding-local_bindings v)) simple_v_b))) (((hydra_lib_maybes_maybe (cl:lambda () body)) (cl:lambda (local_bindings) (let ((bindings ((cl:lambda (v) v) local_bindings))) (hydra_serialization_indent_block ((hydra_lib_lists_cons body) (cl:list (hydra_serialization_indent_block ((hydra_lib_lists_cons (hydra_serialization_cst "where")) ((hydra_lib_lists_map hydra_ext_haskell_serde_local_binding_to_expr) bindings))))))))) local))) match_value)))) (cadr match_target))) vb)))

(cl:defvar hydra_ext_haskell_serde_field_to_expr (cl:lambda (field) (let* ((name ((cl:lambda (v) (hydra_ext_haskell_ast_field-name v)) field)) (typ ((cl:lambda (v) (hydra_ext_haskell_ast_field-type v)) field))) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_ext_haskell_serde_name_to_expr name)) ((hydra_lib_lists_cons (hydra_serialization_cst "::")) (cl:list (hydra_ext_haskell_serde_type_to_expr typ))))))))

(cl:defvar hydra_ext_haskell_serde_to_haskell_comments (cl:lambda (c) ((hydra_lib_strings_intercalate "
") ((hydra_lib_lists_map (cl:lambda (s) ((hydra_lib_strings_cat2 "-- | ") s))) (hydra_lib_strings_lines c)))))

(cl:defvar hydra_ext_haskell_serde_field_with_comments_to_expr (cl:lambda (field_with_comments) (let* ((field ((cl:lambda (v) (hydra_ext_haskell_ast_field_with_comments-field v)) field_with_comments)) (mc ((cl:lambda (v) (hydra_ext_haskell_ast_field_with_comments-comments v)) field_with_comments))) (((hydra_lib_maybes_maybe (cl:lambda () (hydra_ext_haskell_serde_field_to_expr field))) (cl:lambda (c) (hydra_serialization_newline_sep ((hydra_lib_lists_cons (hydra_serialization_cst (hydra_ext_haskell_serde_to_haskell_comments c))) (cl:list (hydra_ext_haskell_serde_field_to_expr field)))))) mc))))

(cl:defvar hydra_ext_haskell_serde_constructor_to_expr (cl:lambda (cons) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :ordinary) ((cl:lambda (ord) (let* ((name ((cl:lambda (v) (hydra_ext_haskell_ast_ordinary_constructor-name v)) ord)) (types ((cl:lambda (v) (hydra_ext_haskell_ast_ordinary_constructor-fields v)) ord))) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_ext_haskell_serde_name_to_expr name)) (cl:list (hydra_serialization_space_sep ((hydra_lib_lists_map hydra_ext_haskell_serde_type_to_expr) types))))))) match_value)) ((equal (car match_target) :record) ((cl:lambda (rec) (let* ((fields ((cl:lambda (v) (hydra_ext_haskell_ast_record_constructor-fields v)) rec)) (name ((cl:lambda (v) (hydra_ext_haskell_ast_record_constructor-name v)) rec))) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_ext_haskell_serde_name_to_expr name)) (cl:list (((hydra_serialization_curly_braces_list (list :nothing)) hydra_serialization_half_block_style) ((hydra_lib_lists_map hydra_ext_haskell_serde_field_with_comments_to_expr) fields))))))) match_value)))) (cadr match_target))) cons)))

(cl:defvar hydra_ext_haskell_serde_constructor_with_comments_to_expr (cl:lambda (cons_with_comments) (let* ((body ((cl:lambda (v) (hydra_ext_haskell_ast_constructor_with_comments-body v)) cons_with_comments)) (mc ((cl:lambda (v) (hydra_ext_haskell_ast_constructor_with_comments-comments v)) cons_with_comments))) (((hydra_lib_maybes_maybe (cl:lambda () (hydra_ext_haskell_serde_constructor_to_expr body))) (cl:lambda (c) (hydra_serialization_newline_sep ((hydra_lib_lists_cons (hydra_serialization_cst (hydra_ext_haskell_serde_to_haskell_comments c))) (cl:list (hydra_ext_haskell_serde_constructor_to_expr body)))))) mc))))

(cl:defvar hydra_ext_haskell_serde_data_or_newtype_to_expr (cl:lambda (kw) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :data) ((cl:lambda (_) (hydra_serialization_cst "data")) match_value)) ((equal (car match_target) :newtype) ((cl:lambda (_) (hydra_serialization_cst "newtype")) match_value)))) (cadr match_target))) kw)))

(cl:defvar hydra_ext_haskell_serde_variable_to_expr (cl:lambda (variable) (hydra_ext_haskell_serde_name_to_expr ((cl:lambda (v) v) variable))))

(cl:defvar hydra_ext_haskell_serde_declaration_head_to_expr (cl:lambda (hd) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :application) ((cl:lambda (app_head) (let* ((fun ((cl:lambda (v) (hydra_ext_haskell_ast_application_declaration_head-function v)) app_head)) (op ((cl:lambda (v) (hydra_ext_haskell_ast_application_declaration_head-operand v)) app_head))) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_ext_haskell_serde_declaration_head_to_expr fun)) (cl:list (hydra_ext_haskell_serde_variable_to_expr op)))))) match_value)) ((equal (car match_target) :simple) ((cl:lambda (name) (hydra_ext_haskell_serde_name_to_expr name)) match_value)))) (cadr match_target))) hd)))

(cl:defvar hydra_ext_haskell_serde_declaration_to_expr (cl:lambda (decl) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :data) ((cl:lambda (data_decl) (let* ((cons ((cl:lambda (v) (hydra_ext_haskell_ast_data_declaration-constructors v)) data_decl)) (constructors ((hydra_serialization_or_sep hydra_serialization_half_block_style) ((hydra_lib_lists_map hydra_ext_haskell_serde_constructor_with_comments_to_expr) cons))) (deriv ((cl:lambda (v) (hydra_ext_haskell_ast_data_declaration-deriving v)) data_decl)) (deriv_cat (hydra_lib_lists_concat ((hydra_lib_lists_map (cl:lambda (v) v)) deriv))) (deriving_clause (if (hydra_lib_lists_null deriv_cat) (cl:list) (cl:list (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_serialization_cst "deriving")) (cl:list ((hydra_serialization_paren_list cl:nil) ((hydra_lib_lists_map hydra_ext_haskell_serde_name_to_expr) deriv_cat)))))))) (hd ((cl:lambda (v) (hydra_ext_haskell_ast_data_declaration-head v)) data_decl)) (kw ((cl:lambda (v) (hydra_ext_haskell_ast_data_declaration-keyword v)) data_decl)) (main_parts (cl:list (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_ext_haskell_serde_data_or_newtype_to_expr kw)) ((hydra_lib_lists_cons (hydra_ext_haskell_serde_declaration_head_to_expr hd)) (cl:list (hydra_serialization_cst "="))))) constructors))) (hydra_serialization_indent_block ((hydra_lib_lists_concat2 main_parts) deriving_clause)))) match_value)) ((equal (car match_target) :type) ((cl:lambda (type_decl) (let* ((hd ((cl:lambda (v) (hydra_ext_haskell_ast_type_declaration-name v)) type_decl)) (typ ((cl:lambda (v) (hydra_ext_haskell_ast_type_declaration-type v)) type_decl))) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_serialization_cst "type")) ((hydra_lib_lists_cons (hydra_ext_haskell_serde_declaration_head_to_expr hd)) ((hydra_lib_lists_cons (hydra_serialization_cst "=")) (cl:list (hydra_ext_haskell_serde_type_to_expr typ)))))))) match_value)) ((equal (car match_target) :value_binding) ((cl:lambda (vb) (hydra_ext_haskell_serde_value_binding_to_expr vb)) match_value)) ((equal (car match_target) :typed_binding) ((cl:lambda (typed_binding) (let* ((type_sig ((cl:lambda (v) (hydra_ext_haskell_ast_typed_binding-type_signature v)) typed_binding)) (htype ((cl:lambda (v) (hydra_ext_haskell_ast_type_signature-type v)) type_sig)) (name ((cl:lambda (v) (hydra_ext_haskell_ast_type_signature-name v)) type_sig)) (vb ((cl:lambda (v) (hydra_ext_haskell_ast_typed_binding-value_binding v)) typed_binding))) (hydra_serialization_newline_sep ((hydra_lib_lists_cons (hydra_serialization_structural_space_sep (cl:list (hydra_ext_haskell_serde_name_to_expr name) (hydra_serialization_cst "::") (hydra_ext_haskell_serde_type_to_expr htype)))) (cl:list (hydra_ext_haskell_serde_value_binding_to_expr vb)))))) match_value)))) (cadr match_target))) decl)))

(cl:defvar hydra_ext_haskell_serde_declaration_with_comments_to_expr (cl:lambda (decl_with_comments) (let* ((body ((cl:lambda (v) (hydra_ext_haskell_ast_declaration_with_comments-body v)) decl_with_comments)) (mc ((cl:lambda (v) (hydra_ext_haskell_ast_declaration_with_comments-comments v)) decl_with_comments))) (((hydra_lib_maybes_maybe (cl:lambda () (hydra_ext_haskell_serde_declaration_to_expr body))) (cl:lambda (c) (hydra_serialization_newline_sep ((hydra_lib_lists_cons (hydra_serialization_cst (hydra_ext_haskell_serde_to_haskell_comments c))) (cl:list (hydra_ext_haskell_serde_declaration_to_expr body)))))) mc))))

(cl:defvar hydra_ext_haskell_serde_import_export_spec_to_expr (cl:lambda (spec) (hydra_ext_haskell_serde_name_to_expr ((cl:lambda (v) (hydra_ext_haskell_ast_import_export_spec-name v)) spec))))

(cl:defvar hydra_ext_haskell_serde_import_to_expr (cl:lambda (import_) (let* ((hiding_sec (cl:lambda (spec) ((cl:lambda (match_target) ((cl:lambda (match_value) (cond ((equal (car match_target) :hiding) ((cl:lambda (names) (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_serialization_cst "hiding ")) (cl:list (hydra_serialization_parens ((hydra_serialization_comma_sep hydra_serialization_inline_style) ((hydra_lib_lists_map hydra_ext_haskell_serde_import_export_spec_to_expr) names))))))) match_value)))) (cadr match_target))) spec))) (mod ((cl:lambda (v) (hydra_ext_haskell_ast_import-as v)) import_)) (mod_name ((cl:lambda (v) (hydra_ext_haskell_ast_import-module v)) import_)) (mspec ((cl:lambda (v) (hydra_ext_haskell_ast_import-spec v)) import_)) (name ((cl:lambda (v) v) mod_name)) (qual ((cl:lambda (v) (hydra_ext_haskell_ast_import-qualified v)) import_)) (parts (hydra_lib_maybes_cat (cl:list (list :just (hydra_serialization_cst "import")) (if qual (list :just (hydra_serialization_cst "qualified")) (list :nothing)) (list :just (hydra_serialization_cst name)) ((hydra_lib_maybes_map (cl:lambda (m) (hydra_serialization_cst ((hydra_lib_strings_cat2 "as ") ((cl:lambda (v) v) m))))) mod) ((hydra_lib_maybes_map hiding_sec) mspec))))) (hydra_serialization_space_sep parts))))

(cl:defvar hydra_ext_haskell_serde_module_head_to_expr (cl:lambda (module_head) (let* ((mod_name ((cl:lambda (v) (hydra_ext_haskell_ast_module_head-name v)) module_head)) (mname ((cl:lambda (v) v) mod_name)) (head (hydra_serialization_space_sep ((hydra_lib_lists_cons (hydra_serialization_cst "module")) ((hydra_lib_lists_cons (hydra_serialization_cst mname)) (cl:list (hydra_serialization_cst "where")))))) (mc ((cl:lambda (v) (hydra_ext_haskell_ast_module_head-comments v)) module_head))) (((hydra_lib_maybes_maybe (cl:lambda () head)) (cl:lambda (c) (hydra_serialization_newline_sep ((hydra_lib_lists_cons (hydra_serialization_cst (hydra_ext_haskell_serde_to_haskell_comments c))) ((hydra_lib_lists_cons (hydra_serialization_cst "")) (cl:list head)))))) mc))))

(cl:defvar hydra_ext_haskell_serde_to_simple_comments (cl:lambda (c) ((hydra_lib_strings_intercalate "
") ((hydra_lib_lists_map (cl:lambda (s) ((hydra_lib_strings_cat2 "-- ") s))) (hydra_lib_strings_lines c)))))

(cl:defvar hydra_ext_haskell_serde_module_to_expr (cl:lambda (module) (let* ((decls ((cl:lambda (v) (hydra_ext_haskell_ast_module-declarations v)) module)) (decl_lines ((hydra_lib_lists_map hydra_ext_haskell_serde_declaration_with_comments_to_expr) decls)) (mh ((cl:lambda (v) (hydra_ext_haskell_ast_module-head v)) module)) (header_line (((hydra_lib_maybes_maybe (cl:lambda () (cl:list))) (cl:lambda (h) (cl:list (hydra_ext_haskell_serde_module_head_to_expr h)))) mh)) (imports ((cl:lambda (v) (hydra_ext_haskell_ast_module-imports v)) module)) (import_lines (if (hydra_lib_lists_null imports) (cl:list) (cl:list (hydra_serialization_newline_sep ((hydra_lib_lists_map hydra_ext_haskell_serde_import_to_expr) imports))))) (warning (cl:list (hydra_serialization_cst (hydra_ext_haskell_serde_to_simple_comments hydra_constants_warning_auto_generated_file))))) (hydra_serialization_double_newline_sep (hydra_lib_lists_concat (cl:list warning header_line import_lines decl_lines))))))
