-- | Serialization of Go syntax to source code.
--
-- This module provides functions for converting Go AST nodes to source code text,
-- using Hydra's Ast.Expr representation as an intermediate form.
module Hydra.Sources.Go.Serde where

import Hydra.Constants
import Hydra.Kernel
import Hydra.Serialization
import qualified Hydra.Ast as Ast
import qualified Hydra.Go.Syntax as Go

import qualified Data.List as L
import qualified Data.Maybe as Y
import qualified Data.Char as C
import Data.Char (ord, toUpper)
import Numeric (showHex)

-- ============================================================================
-- Source File Structure
-- ============================================================================

sourceFileToExpr :: Go.SourceFile -> Ast.Expr
sourceFileToExpr (Go.SourceFile pkg imports decls) = doubleNewlineSep $ Y.catMaybes [
  Just $ singleLineComment warningAutoGeneratedFile,
  Just $ packageClauseToExpr pkg,
  if L.null imports then Nothing else Just $ newlineSep (importDeclToExpr <$> imports),
  if L.null decls then Nothing else Just $ doubleNewlineSep (topLevelDeclToExpr <$> decls)]

moduleToExpr :: Go.Module -> Ast.Expr
moduleToExpr (Go.Module pkg imports decls) = doubleNewlineSep $ Y.catMaybes [
  Just $ singleLineComment warningAutoGeneratedFile,
  Just $ packageClauseToExpr pkg,
  if L.null imports then Nothing else Just $ newlineSep (importDeclToExpr <$> imports),
  if L.null decls then Nothing else Just $ doubleNewlineSep (topLevelDeclToExpr <$> decls)]

packageClauseToExpr :: Go.PackageClause -> Ast.Expr
packageClauseToExpr (Go.PackageClause ident) = spaceSep [cst "package", identifierToExpr ident]

importDeclToExpr :: Go.ImportDecl -> Ast.Expr
importDeclToExpr (Go.ImportDecl specs) = case specs of
  [spec] -> spaceSep [cst "import", importSpecToExpr spec]
  _ -> spaceSep [cst "import", parenList True (importSpecToExpr <$> specs)]

importSpecToExpr :: Go.ImportSpec -> Ast.Expr
importSpecToExpr (Go.ImportSpec malias path) = case malias of
  Nothing -> importPathToExpr path
  Just alias -> spaceSep [importAliasToExpr alias, importPathToExpr path]

importAliasToExpr :: Go.ImportAlias -> Ast.Expr
importAliasToExpr alias = case alias of
  Go.ImportAliasDot -> cst "."
  Go.ImportAliasName ident -> identifierToExpr ident

importPathToExpr :: Go.ImportPath -> Ast.Expr
importPathToExpr (Go.ImportPath lit) = stringLitToExpr lit

-- ============================================================================
-- Declarations
-- ============================================================================

topLevelDeclToExpr :: Go.TopLevelDecl -> Ast.Expr
topLevelDeclToExpr decl = case decl of
  Go.TopLevelDeclDeclaration d -> declarationToExpr d
  Go.TopLevelDeclFunction f -> functionDeclToExpr f
  Go.TopLevelDeclMethod m -> methodDeclToExpr m

declarationToExpr :: Go.Declaration -> Ast.Expr
declarationToExpr decl = case decl of
  Go.DeclarationConst c -> constDeclToExpr c
  Go.DeclarationType t -> typeDeclToExpr t
  Go.DeclarationVar v -> varDeclToExpr v

constDeclToExpr :: Go.ConstDecl -> Ast.Expr
constDeclToExpr (Go.ConstDecl specs) = case specs of
  [spec] -> spaceSep [cst "const", constSpecToExpr spec]
  _ -> spaceSep [cst "const", parenList True (constSpecToExpr <$> specs)]

constSpecToExpr :: Go.ConstSpec -> Ast.Expr
constSpecToExpr (Go.ConstSpec names mtyp values) = spaceSep $ Y.catMaybes [
  Just $ commaSep inlineStyle (identifierToExpr <$> names),
  typeToExpr <$> mtyp,
  if L.null values then Nothing else Just $ spaceSep [cst "=", commaSep inlineStyle (expressionToExpr <$> values)]]

varDeclToExpr :: Go.VarDecl -> Ast.Expr
varDeclToExpr (Go.VarDecl specs) = case specs of
  [spec] -> spaceSep [cst "var", varSpecToExpr spec]
  _ -> spaceSep [cst "var", parenList True (varSpecToExpr <$> specs)]

varSpecToExpr :: Go.VarSpec -> Ast.Expr
varSpecToExpr (Go.VarSpec names mtyp values) = spaceSep $ Y.catMaybes [
  Just $ commaSep inlineStyle (identifierToExpr <$> names),
  typeToExpr <$> mtyp,
  if L.null values then Nothing else Just $ spaceSep [cst "=", commaSep inlineStyle (expressionToExpr <$> values)]]

shortVarDeclToExpr :: Go.ShortVarDecl -> Ast.Expr
shortVarDeclToExpr (Go.ShortVarDecl names values) = spaceSep [
  commaSep inlineStyle (identifierToExpr <$> names),
  cst ":=",
  commaSep inlineStyle (expressionToExpr <$> values)]

typeDeclToExpr :: Go.TypeDecl -> Ast.Expr
typeDeclToExpr (Go.TypeDecl specs) = case specs of
  [spec] -> spaceSep [cst "type", typeSpecToExpr spec]
  _ -> spaceSep [cst "type", parenList True (typeSpecToExpr <$> specs)]

typeSpecToExpr :: Go.TypeSpec -> Ast.Expr
typeSpecToExpr spec = case spec of
  Go.TypeSpecAlias a -> aliasDeclToExpr a
  Go.TypeSpecDefinition d -> typeDefToExpr d

aliasDeclToExpr :: Go.AliasDecl -> Ast.Expr
aliasDeclToExpr (Go.AliasDecl name typ) = spaceSep [identifierToExpr name, cst "=", typeToExpr typ]

typeDefToExpr :: Go.TypeDef -> Ast.Expr
typeDefToExpr (Go.TypeDef name mtparams typ) = spaceSep $ Y.catMaybes [
  Just $ identifierToExpr name,
  typeParametersToExpr <$> mtparams,
  Just $ typeToExpr typ]

typeParametersToExpr :: Go.TypeParameters -> Ast.Expr
typeParametersToExpr (Go.TypeParameters decls) = brackets squareBrackets inlineStyle $
  commaSep inlineStyle (typeParamDeclToExpr <$> decls)

typeParamDeclToExpr :: Go.TypeParamDecl -> Ast.Expr
typeParamDeclToExpr (Go.TypeParamDecl names constraint) = spaceSep [
  commaSep inlineStyle (identifierToExpr <$> names),
  typeConstraintToExpr constraint]

typeConstraintToExpr :: Go.TypeConstraint -> Ast.Expr
typeConstraintToExpr (Go.TypeConstraint elem) = typeElemToExpr elem

functionDeclToExpr :: Go.FunctionDecl -> Ast.Expr
functionDeclToExpr (Go.FunctionDecl name mtparams sig mbody) = spaceSep $ Y.catMaybes [
  Just $ cst "func",
  Just $ noSep $ Y.catMaybes [
    Just $ identifierToExpr name,
    typeParametersToExpr <$> mtparams],
  Just $ signatureToExpr sig,
  functionBodyToExpr <$> mbody]

functionBodyToExpr :: Go.FunctionBody -> Ast.Expr
functionBodyToExpr (Go.FunctionBody block) = blockToExpr block

methodDeclToExpr :: Go.MethodDecl -> Ast.Expr
methodDeclToExpr (Go.MethodDecl recv name sig mbody) = spaceSep $ Y.catMaybes [
  Just $ cst "func",
  Just $ receiverToExpr recv,
  Just $ noSep [identifierToExpr name, signatureToExpr sig],
  functionBodyToExpr <$> mbody]

receiverToExpr :: Go.Receiver -> Ast.Expr
receiverToExpr (Go.Receiver mname typ) = parenList False $ case mname of
  Nothing -> [typeToExpr typ]
  Just name -> [spaceSep [identifierToExpr name, typeToExpr typ]]

-- ============================================================================
-- Types
-- ============================================================================

typeToExpr :: Go.Type -> Ast.Expr
typeToExpr typ = case typ of
  Go.TypeName_ tn -> typeNameToExpr tn
  Go.TypeLiteral lit -> typeLitToExpr lit
  Go.TypeParen t -> parens (typeToExpr t)

typeNameToExpr :: Go.TypeName -> Ast.Expr
typeNameToExpr (Go.TypeName qid targs) = noSep $ Y.catMaybes [
  Just $ qualifiedIdentToExpr qid,
  if L.null targs then Nothing else Just $ brackets squareBrackets inlineStyle $
    commaSep inlineStyle (typeToExpr <$> targs)]

qualifiedIdentToExpr :: Go.QualifiedIdent -> Ast.Expr
qualifiedIdentToExpr (Go.QualifiedIdent mpkg name) = case mpkg of
  Nothing -> identifierToExpr name
  Just pkg -> dotSep [identifierToExpr pkg, identifierToExpr name]

typeLitToExpr :: Go.TypeLit -> Ast.Expr
typeLitToExpr lit = case lit of
  Go.TypeLitArray a -> arrayTypeToExpr a
  Go.TypeLitStruct s -> structTypeToExpr s
  Go.TypeLitPointer p -> pointerTypeToExpr p
  Go.TypeLitFunction f -> functionTypeToExpr f
  Go.TypeLitInterface i -> interfaceTypeToExpr i
  Go.TypeLitSlice s -> sliceTypeToExpr s
  Go.TypeLitMap m -> mapTypeToExpr m
  Go.TypeLitChannel c -> channelTypeToExpr c

arrayTypeToExpr :: Go.ArrayType -> Ast.Expr
arrayTypeToExpr (Go.ArrayType len elem) = noSep [
  brackets squareBrackets inlineStyle (expressionToExpr len),
  typeToExpr elem]

sliceTypeToExpr :: Go.SliceType -> Ast.Expr
sliceTypeToExpr (Go.SliceType elem) = noSep [cst "[]", typeToExpr elem]

structTypeToExpr :: Go.StructType -> Ast.Expr
structTypeToExpr (Go.StructType fields) = if L.null fields
  then cst "struct{}"
  else spaceSep [cst "struct", curlyBlock fullBlockStyle $ newlineSep (fieldDeclToExpr <$> fields)]

fieldDeclToExpr :: Go.FieldDecl -> Ast.Expr
fieldDeclToExpr field = case field of
  Go.FieldDeclNamed nf -> namedFieldToExpr nf
  Go.FieldDeclEmbedded ef -> embeddedFieldToExpr ef

namedFieldToExpr :: Go.NamedField -> Ast.Expr
namedFieldToExpr (Go.NamedField names typ mtag) = spaceSep $ Y.catMaybes [
  Just $ commaSep inlineStyle (identifierToExpr <$> names),
  Just $ typeToExpr typ,
  tagToExpr <$> mtag]

embeddedFieldToExpr :: Go.EmbeddedField -> Ast.Expr
embeddedFieldToExpr (Go.EmbeddedField isPtr typName mtag) = spaceSep $ Y.catMaybes [
  Just $ noSep $ Y.catMaybes [
    if isPtr then Just (cst "*") else Nothing,
    Just $ typeNameToExpr typName],
  tagToExpr <$> mtag]

tagToExpr :: Go.Tag -> Ast.Expr
tagToExpr (Go.Tag lit) = stringLitToExpr lit

pointerTypeToExpr :: Go.PointerType -> Ast.Expr
pointerTypeToExpr (Go.PointerType typ) = noSep [cst "*", typeToExpr typ]

functionTypeToExpr :: Go.FunctionType -> Ast.Expr
functionTypeToExpr (Go.FunctionType sig) = noSep [cst "func", signatureToExpr sig]

signatureToExpr :: Go.Signature -> Ast.Expr
signatureToExpr (Go.Signature params mresult) = noSep $ Y.catMaybes [
  Just $ parametersToExpr params,
  resultToExpr <$> mresult]

resultToExpr :: Go.Result -> Ast.Expr
resultToExpr result = case result of
  Go.ResultParameters p -> spaceSep [cst "", parametersToExpr p]
  Go.ResultType t -> spaceSep [cst "", typeToExpr t]

parametersToExpr :: Go.Parameters -> Ast.Expr
parametersToExpr (Go.Parameters decls) = parenList False (parameterDeclToExpr <$> decls)

parameterDeclToExpr :: Go.ParameterDecl -> Ast.Expr
parameterDeclToExpr (Go.ParameterDecl names variadic typ) = spaceSep $ Y.catMaybes [
  if L.null names then Nothing else Just $ commaSep inlineStyle (identifierToExpr <$> names),
  Just $ noSep $ Y.catMaybes [
    if variadic then Just (cst "...") else Nothing,
    Just $ typeToExpr typ]]

interfaceTypeToExpr :: Go.InterfaceType -> Ast.Expr
interfaceTypeToExpr (Go.InterfaceType elems) = if L.null elems
  then cst "interface{}"
  else spaceSep [cst "interface", curlyBlock fullBlockStyle $ newlineSep (interfaceElemToExpr <$> elems)]

interfaceElemToExpr :: Go.InterfaceElem -> Ast.Expr
interfaceElemToExpr elem = case elem of
  Go.InterfaceElemMethod m -> methodElemToExpr m
  Go.InterfaceElemType t -> typeElemToExpr t

methodElemToExpr :: Go.MethodElem -> Ast.Expr
methodElemToExpr (Go.MethodElem name sig) = noSep [identifierToExpr name, signatureToExpr sig]

typeElemToExpr :: Go.TypeElem -> Ast.Expr
typeElemToExpr (Go.TypeElem terms) = sep (orOp False) (typeTermToExpr <$> terms)

typeTermToExpr :: Go.TypeTerm -> Ast.Expr
typeTermToExpr (Go.TypeTerm underlying typ) = noSep $ Y.catMaybes [
  if underlying then Just (cst "~") else Nothing,
  Just $ typeToExpr typ]

mapTypeToExpr :: Go.MapType -> Ast.Expr
mapTypeToExpr (Go.MapType key val) = noSep [
  cst "map",
  brackets squareBrackets inlineStyle (typeToExpr key),
  typeToExpr val]

channelTypeToExpr :: Go.ChannelType -> Ast.Expr
channelTypeToExpr (Go.ChannelType dir elem) = spaceSep [channelDirectionToExpr dir, typeToExpr elem]

channelDirectionToExpr :: Go.ChannelDirection -> Ast.Expr
channelDirectionToExpr dir = case dir of
  Go.ChannelDirectionBidirectional -> cst "chan"
  Go.ChannelDirectionSend -> cst "chan<-"
  Go.ChannelDirectionReceive -> cst "<-chan"

-- ============================================================================
-- Expressions
-- ============================================================================

expressionToExpr :: Go.Expression -> Ast.Expr
expressionToExpr expr = case expr of
  Go.ExpressionUnary u -> unaryExprToExpr u
  Go.ExpressionBinary b -> binaryExprToExpr b

unaryExprToExpr :: Go.UnaryExpr -> Ast.Expr
unaryExprToExpr expr = case expr of
  Go.UnaryExprPrimary p -> primaryExprToExpr p
  Go.UnaryExprOp op -> unaryOperationToExpr op

unaryOperationToExpr :: Go.UnaryOperation -> Ast.Expr
unaryOperationToExpr (Go.UnaryOperation op operand) = noSep [unaryOpToExpr op, unaryExprToExpr operand]

binaryExprToExpr :: Go.BinaryExpr -> Ast.Expr
binaryExprToExpr (Go.BinaryExpr left op right) = spaceSep [
  expressionToExpr left,
  binaryOpToExpr op,
  expressionToExpr right]

binaryOpToExpr :: Go.BinaryOp -> Ast.Expr
binaryOpToExpr op = cst $ case op of
  Go.BinaryOpOr -> "||"
  Go.BinaryOpAnd -> "&&"
  Go.BinaryOpEqual -> "=="
  Go.BinaryOpNotEqual -> "!="
  Go.BinaryOpLess -> "<"
  Go.BinaryOpLessEqual -> "<="
  Go.BinaryOpGreater -> ">"
  Go.BinaryOpGreaterEqual -> ">="
  Go.BinaryOpAdd -> "+"
  Go.BinaryOpSubtract -> "-"
  Go.BinaryOpBitwiseOr -> "|"
  Go.BinaryOpBitwiseXor -> "^"
  Go.BinaryOpMultiply -> "*"
  Go.BinaryOpDivide -> "/"
  Go.BinaryOpRemainder -> "%"
  Go.BinaryOpLeftShift -> "<<"
  Go.BinaryOpRightShift -> ">>"
  Go.BinaryOpBitwiseAnd -> "&"
  Go.BinaryOpBitClear -> "&^"

primaryExprToExpr :: Go.PrimaryExpr -> Ast.Expr
primaryExprToExpr expr = case expr of
  Go.PrimaryExprOperand o -> operandToExpr o
  Go.PrimaryExprConversion c -> conversionToExpr c
  Go.PrimaryExprMethodExpr m -> methodExprToExpr m
  Go.PrimaryExprSelector s -> selectorExprToExpr s
  Go.PrimaryExprIndex i -> indexExprToExpr i
  Go.PrimaryExprSlice s -> sliceExprToExpr s
  Go.PrimaryExprTypeAssertion t -> typeAssertionExprToExpr t
  Go.PrimaryExprCall c -> callExprToExpr c

selectorExprToExpr :: Go.SelectorExpr -> Ast.Expr
selectorExprToExpr (Go.SelectorExpr expr sel) = dotSep [primaryExprToExpr expr, identifierToExpr sel]

indexExprToExpr :: Go.IndexExpr -> Ast.Expr
indexExprToExpr (Go.IndexExpr expr idx) = noSep [
  primaryExprToExpr expr,
  brackets squareBrackets inlineStyle (expressionToExpr idx)]

sliceExprToExpr :: Go.SliceExpr -> Ast.Expr
sliceExprToExpr (Go.SliceExpr expr slice) = noSep [primaryExprToExpr expr, sliceToExpr slice]

typeAssertionExprToExpr :: Go.TypeAssertionExpr -> Ast.Expr
typeAssertionExprToExpr (Go.TypeAssertionExpr expr typ) = noSep [
  primaryExprToExpr expr,
  cst ".",
  parenList False [typeToExpr typ]]

callExprToExpr :: Go.CallExpr -> Ast.Expr
callExprToExpr (Go.CallExpr func args) = noSep [primaryExprToExpr func, argumentsToExpr args]

operandToExpr :: Go.Operand -> Ast.Expr
operandToExpr op = case op of
  Go.OperandLiteral l -> literalToExpr l
  Go.OperandName_ n -> operandNameToExpr n
  Go.OperandParen e -> parens (expressionToExpr e)

operandNameToExpr :: Go.OperandName -> Ast.Expr
operandNameToExpr (Go.OperandName qid targs) = noSep $ Y.catMaybes [
  Just $ qualifiedIdentToExpr qid,
  if L.null targs then Nothing else Just $ brackets squareBrackets inlineStyle $
    commaSep inlineStyle (typeToExpr <$> targs)]

literalToExpr :: Go.Literal -> Ast.Expr
literalToExpr lit = case lit of
  Go.LiteralBasic b -> basicLitToExpr b
  Go.LiteralComposite c -> compositeLitToExpr c
  Go.LiteralFunction f -> functionLitToExpr f

basicLitToExpr :: Go.BasicLit -> Ast.Expr
basicLitToExpr lit = case lit of
  Go.BasicLitInt i -> intLitToExpr i
  Go.BasicLitFloat f -> floatLitToExpr f
  Go.BasicLitImaginary i -> imaginaryLitToExpr i
  Go.BasicLitRune r -> runeLitToExpr r
  Go.BasicLitString s -> stringLitToExpr s

compositeLitToExpr :: Go.CompositeLit -> Ast.Expr
compositeLitToExpr (Go.CompositeLit typ val) = noSep [literalTypeToExpr typ, literalValueToExpr val]

literalTypeToExpr :: Go.LiteralType -> Ast.Expr
literalTypeToExpr typ = case typ of
  Go.LiteralTypeStruct s -> structTypeToExpr s
  Go.LiteralTypeArray a -> arrayTypeToExpr a
  Go.LiteralTypeInferredArray t -> noSep [cst "[...]", typeToExpr t]
  Go.LiteralTypeSlice s -> sliceTypeToExpr s
  Go.LiteralTypeMap m -> mapTypeToExpr m
  Go.LiteralTypeName n -> typeNameToExpr n

literalValueToExpr :: Go.LiteralValue -> Ast.Expr
literalValueToExpr (Go.LiteralValue elems) = if L.null elems
  then cst "{}"
  else curlyBracesList Nothing inlineStyle (keyedElementToExpr <$> elems)

keyedElementToExpr :: Go.KeyedElement -> Ast.Expr
keyedElementToExpr (Go.KeyedElement mkey elem) = case mkey of
  Nothing -> elementToExpr elem
  Just key -> spaceSep [noSep [keyToExpr key, cst ":"], elementToExpr elem]

keyToExpr :: Go.Key -> Ast.Expr
keyToExpr key = case key of
  Go.KeyField ident -> identifierToExpr ident
  Go.KeyExpression e -> expressionToExpr e
  Go.KeyLiteral lv -> literalValueToExpr lv

elementToExpr :: Go.Element -> Ast.Expr
elementToExpr elem = case elem of
  Go.ElementExpression e -> expressionToExpr e
  Go.ElementLiteral lv -> literalValueToExpr lv

functionLitToExpr :: Go.FunctionLit -> Ast.Expr
functionLitToExpr (Go.FunctionLit sig body) = spaceSep [
  cst "func",
  signatureToExpr sig,
  functionBodyToExpr body]

selectorToExpr :: Go.Selector -> Ast.Expr
selectorToExpr (Go.Selector ident) = noSep [cst ".", identifierToExpr ident]

indexToExpr :: Go.Index -> Ast.Expr
indexToExpr (Go.Index exprs) = brackets squareBrackets inlineStyle $ commaSep inlineStyle (expressionToExpr <$> exprs)

sliceToExpr :: Go.Slice -> Ast.Expr
sliceToExpr slice = case slice of
  Go.SliceSimple s -> simpleSliceToExpr s
  Go.SliceFull f -> fullSliceToExpr f

simpleSliceToExpr :: Go.SimpleSlice -> Ast.Expr
simpleSliceToExpr (Go.SimpleSlice mlo mhi) = brackets squareBrackets inlineStyle $ noSep [
  Y.maybe (cst "") expressionToExpr mlo,
  cst ":",
  Y.maybe (cst "") expressionToExpr mhi]

fullSliceToExpr :: Go.FullSlice -> Ast.Expr
fullSliceToExpr (Go.FullSlice mlo hi maxv) = brackets squareBrackets inlineStyle $ noSep [
  Y.maybe (cst "") expressionToExpr mlo,
  cst ":",
  expressionToExpr hi,
  cst ":",
  expressionToExpr maxv]

typeAssertionToExpr :: Go.TypeAssertion -> Ast.Expr
typeAssertionToExpr (Go.TypeAssertion typ) = noSep [cst ".", parenList False [typeToExpr typ]]

argumentsToExpr :: Go.Arguments -> Ast.Expr
argumentsToExpr (Go.Arguments mtypeArg exprs ellipsis) = parenList False $ Y.catMaybes $
  [typeToExpr <$> mtypeArg] ++ (fmap Just (expressionToExpr <$> exprs)) ++ [if ellipsis then Just (cst "...") else Nothing]

methodExprToExpr :: Go.MethodExpr -> Ast.Expr
methodExprToExpr (Go.MethodExpr recv method) = dotSep [typeToExpr recv, identifierToExpr method]

conversionToExpr :: Go.Conversion -> Ast.Expr
conversionToExpr (Go.Conversion typ expr) = noSep [typeToExpr typ, parenList False [expressionToExpr expr]]

-- ============================================================================
-- Statements
-- ============================================================================

statementToExpr :: Go.Statement -> Ast.Expr
statementToExpr stmt = case stmt of
  Go.StatementDeclaration d -> declarationToExpr d
  Go.StatementLabeled l -> labeledStmtToExpr l
  Go.StatementSimple s -> simpleStmtToExpr s
  Go.StatementGo g -> goStmtToExpr g
  Go.StatementReturn r -> returnStmtToExpr r
  Go.StatementBreak b -> breakStmtToExpr b
  Go.StatementContinue c -> continueStmtToExpr c
  Go.StatementGoto g -> gotoStmtToExpr g
  Go.StatementFallthrough f -> fallthroughStmtToExpr f
  Go.StatementBlock b -> blockToExpr b
  Go.StatementIf i -> ifStmtToExpr i
  Go.StatementSwitch s -> switchStmtToExpr s
  Go.StatementSelect s -> selectStmtToExpr s
  Go.StatementFor f -> forStmtToExpr f
  Go.StatementDefer d -> deferStmtToExpr d

simpleStmtToExpr :: Go.SimpleStmt -> Ast.Expr
simpleStmtToExpr stmt = case stmt of
  Go.SimpleStmtEmpty e -> emptyStmtToExpr e
  Go.SimpleStmtExpression e -> expressionStmtToExpr e
  Go.SimpleStmtSend s -> sendStmtToExpr s
  Go.SimpleStmtIncDec i -> incDecStmtToExpr i
  Go.SimpleStmtAssignment a -> assignmentToExpr a
  Go.SimpleStmtShortVarDecl s -> shortVarDeclToExpr s

emptyStmtToExpr :: Go.EmptyStmt -> Ast.Expr
emptyStmtToExpr (Go.EmptyStmt ()) = cst ""

labeledStmtToExpr :: Go.LabeledStmt -> Ast.Expr
labeledStmtToExpr (Go.LabeledStmt label stmt) = newlineSep [
  noSep [identifierToExpr label, cst ":"],
  statementToExpr stmt]

expressionStmtToExpr :: Go.ExpressionStmt -> Ast.Expr
expressionStmtToExpr (Go.ExpressionStmt expr) = expressionToExpr expr

sendStmtToExpr :: Go.SendStmt -> Ast.Expr
sendStmtToExpr (Go.SendStmt ch val) = spaceSep [expressionToExpr ch, cst "<-", expressionToExpr val]

incDecStmtToExpr :: Go.IncDecStmt -> Ast.Expr
incDecStmtToExpr (Go.IncDecStmt expr isInc) = noSep [
  expressionToExpr expr,
  cst $ if isInc then "++" else "--"]

assignmentToExpr :: Go.Assignment -> Ast.Expr
assignmentToExpr (Go.Assignment lhs op rhs) = spaceSep [
  commaSep inlineStyle (expressionToExpr <$> lhs),
  assignOpToExpr op,
  commaSep inlineStyle (expressionToExpr <$> rhs)]

assignOpToExpr :: Go.AssignOp -> Ast.Expr
assignOpToExpr op = case op of
  Go.AssignOpSimple -> cst "="
  Go.AssignOpAdd addOp -> noSep [addOpToExpr addOp, cst "="]
  Go.AssignOpMul mulOp -> noSep [mulOpToExpr mulOp, cst "="]

ifStmtToExpr :: Go.IfStmt -> Ast.Expr
ifStmtToExpr (Go.IfStmt minit cond thenBlock melseClause) = spaceSep $ Y.catMaybes [
  Just $ cst "if",
  (\s -> noSep [simpleStmtToExpr s, cst ";"]) <$> minit,
  Just $ expressionToExpr cond,
  Just $ blockToExpr thenBlock,
  elseClauseToExpr <$> melseClause]

elseClauseToExpr :: Go.ElseClause -> Ast.Expr
elseClauseToExpr clause = case clause of
  Go.ElseClauseIf ifStmt -> spaceSep [cst "else", ifStmtToExpr ifStmt]
  Go.ElseClauseBlock block -> spaceSep [cst "else", blockToExpr block]

switchStmtToExpr :: Go.SwitchStmt -> Ast.Expr
switchStmtToExpr stmt = case stmt of
  Go.SwitchStmtExpression e -> exprSwitchStmtToExpr e
  Go.SwitchStmtType t -> typeSwitchStmtToExpr t

exprSwitchStmtToExpr :: Go.ExprSwitchStmt -> Ast.Expr
exprSwitchStmtToExpr (Go.ExprSwitchStmt minit mexpr cases) = spaceSep $ Y.catMaybes [
  Just $ cst "switch",
  (\s -> noSep [simpleStmtToExpr s, cst ";"]) <$> minit,
  expressionToExpr <$> mexpr,
  Just $ curlyBlock fullBlockStyle $ newlineSep (exprCaseClauseToExpr <$> cases)]

exprCaseClauseToExpr :: Go.ExprCaseClause -> Ast.Expr
exprCaseClauseToExpr (Go.ExprCaseClause mexprs stmts) = newlineSep [
  case mexprs of
    Nothing -> cst "default:"
    Just exprs -> noSep [cst "case ", commaSep inlineStyle (expressionToExpr <$> exprs), cst ":"],
  indentBlock (statementToExpr <$> stmts)]

typeSwitchStmtToExpr :: Go.TypeSwitchStmt -> Ast.Expr
typeSwitchStmtToExpr (Go.TypeSwitchStmt minit guard cases) = spaceSep $ Y.catMaybes [
  Just $ cst "switch",
  (\s -> noSep [simpleStmtToExpr s, cst ";"]) <$> minit,
  Just $ typeSwitchGuardToExpr guard,
  Just $ curlyBlock fullBlockStyle $ newlineSep (typeCaseClauseToExpr <$> cases)]

typeSwitchGuardToExpr :: Go.TypeSwitchGuard -> Ast.Expr
typeSwitchGuardToExpr (Go.TypeSwitchGuard mname expr) = case mname of
  Nothing -> noSep [primaryExprToExpr expr, cst ".(type)"]
  Just name -> spaceSep [identifierToExpr name, cst ":=", noSep [primaryExprToExpr expr, cst ".(type)"]]

typeCaseClauseToExpr :: Go.TypeCaseClause -> Ast.Expr
typeCaseClauseToExpr (Go.TypeCaseClause mtypes stmts) = newlineSep [
  case mtypes of
    Nothing -> cst "default:"
    Just types -> noSep [cst "case ", commaSep inlineStyle (typeToExpr <$> types), cst ":"],
  indentBlock (statementToExpr <$> stmts)]

forStmtToExpr :: Go.ForStmt -> Ast.Expr
forStmtToExpr (Go.ForStmt mclause body) = spaceSep $ Y.catMaybes [
  Just $ cst "for",
  forClauseOrRangeToExpr <$> mclause,
  Just $ blockToExpr body]

forClauseOrRangeToExpr :: Go.ForClauseOrRange -> Ast.Expr
forClauseOrRangeToExpr clause = case clause of
  Go.ForClauseOrRangeCondition e -> expressionToExpr e
  Go.ForClauseOrRangeClause c -> forClauseToExpr c
  Go.ForClauseOrRangeRange r -> rangeClauseToExpr r

forClauseToExpr :: Go.ForClause -> Ast.Expr
forClauseToExpr (Go.ForClause minit mcond mpost) = noSep [
  Y.maybe (cst "") simpleStmtToExpr minit,
  cst ";",
  Y.maybe (cst "") (\e -> spaceSep [cst "", expressionToExpr e]) mcond,
  cst ";",
  Y.maybe (cst "") (\s -> spaceSep [cst "", simpleStmtToExpr s]) mpost]

rangeClauseToExpr :: Go.RangeClause -> Ast.Expr
rangeClauseToExpr (Go.RangeClause mvars expr) = spaceSep $ Y.catMaybes [
  rangeVarsToExpr <$> mvars,
  Just $ cst "range",
  Just $ expressionToExpr expr]

rangeVarsToExpr :: Go.RangeVars -> Ast.Expr
rangeVarsToExpr vars = case vars of
  Go.RangeVarsAssign exprs -> spaceSep [commaSep inlineStyle (expressionToExpr <$> exprs), cst "="]
  Go.RangeVarsDeclare idents -> spaceSep [commaSep inlineStyle (identifierToExpr <$> idents), cst ":="]

goStmtToExpr :: Go.GoStmt -> Ast.Expr
goStmtToExpr (Go.GoStmt expr) = spaceSep [cst "go", expressionToExpr expr]

selectStmtToExpr :: Go.SelectStmt -> Ast.Expr
selectStmtToExpr (Go.SelectStmt clauses) = spaceSep [
  cst "select",
  curlyBlock fullBlockStyle $ newlineSep (commClauseToExpr <$> clauses)]

commClauseToExpr :: Go.CommClause -> Ast.Expr
commClauseToExpr (Go.CommClause commCase stmts) = newlineSep [
  commCaseToExpr commCase,
  indentBlock (statementToExpr <$> stmts)]

commCaseToExpr :: Go.CommCase -> Ast.Expr
commCaseToExpr commCase = case commCase of
  Go.CommCaseSend s -> noSep [cst "case ", sendStmtToExpr s, cst ":"]
  Go.CommCaseReceive r -> noSep [cst "case ", receiveCaseToExpr r, cst ":"]
  Go.CommCaseDefault -> cst "default:"

receiveCaseToExpr :: Go.ReceiveCase -> Ast.Expr
receiveCaseToExpr (Go.ReceiveCase mvars expr) = spaceSep $ Y.catMaybes [
  rangeVarsToExpr <$> mvars,
  Just $ noSep [cst "<-", expressionToExpr expr]]

returnStmtToExpr :: Go.ReturnStmt -> Ast.Expr
returnStmtToExpr (Go.ReturnStmt exprs) = if L.null exprs
  then cst "return"
  else spaceSep [cst "return", commaSep inlineStyle (expressionToExpr <$> exprs)]

breakStmtToExpr :: Go.BreakStmt -> Ast.Expr
breakStmtToExpr (Go.BreakStmt mlabel) = case mlabel of
  Nothing -> cst "break"
  Just label -> spaceSep [cst "break", identifierToExpr label]

continueStmtToExpr :: Go.ContinueStmt -> Ast.Expr
continueStmtToExpr (Go.ContinueStmt mlabel) = case mlabel of
  Nothing -> cst "continue"
  Just label -> spaceSep [cst "continue", identifierToExpr label]

gotoStmtToExpr :: Go.GotoStmt -> Ast.Expr
gotoStmtToExpr (Go.GotoStmt label) = spaceSep [cst "goto", identifierToExpr label]

fallthroughStmtToExpr :: Go.FallthroughStmt -> Ast.Expr
fallthroughStmtToExpr (Go.FallthroughStmt ()) = cst "fallthrough"

deferStmtToExpr :: Go.DeferStmt -> Ast.Expr
deferStmtToExpr (Go.DeferStmt expr) = spaceSep [cst "defer", expressionToExpr expr]

blockToExpr :: Go.Block -> Ast.Expr
blockToExpr (Go.Block stmts) = curlyBlock fullBlockStyle $ newlineSep (statementToExpr <$> stmts)

-- ============================================================================
-- Operators
-- ============================================================================

unaryOpToExpr :: Go.UnaryOp -> Ast.Expr
unaryOpToExpr op = cst $ case op of
  Go.UnaryOpPlus -> "+"
  Go.UnaryOpMinus -> "-"
  Go.UnaryOpNot -> "!"
  Go.UnaryOpXor -> "^"
  Go.UnaryOpDeref -> "*"
  Go.UnaryOpAddressOf -> "&"
  Go.UnaryOpReceive -> "<-"

mulOpToExpr :: Go.MulOp -> Ast.Expr
mulOpToExpr op = cst $ case op of
  Go.MulOpMultiply -> "*"
  Go.MulOpDivide -> "/"
  Go.MulOpRemainder -> "%"
  Go.MulOpLeftShift -> "<<"
  Go.MulOpRightShift -> ">>"
  Go.MulOpBitwiseAnd -> "&"
  Go.MulOpBitClear -> "&^"

addOpToExpr :: Go.AddOp -> Ast.Expr
addOpToExpr op = cst $ case op of
  Go.AddOpAdd -> "+"
  Go.AddOpSubtract -> "-"
  Go.AddOpBitwiseOr -> "|"
  Go.AddOpBitwiseXor -> "^"

relOpToExpr :: Go.RelOp -> Ast.Expr
relOpToExpr op = cst $ case op of
  Go.RelOpEqual -> "=="
  Go.RelOpNotEqual -> "!="
  Go.RelOpLess -> "<"
  Go.RelOpLessEqual -> "<="
  Go.RelOpGreater -> ">"
  Go.RelOpGreaterEqual -> ">="

-- ============================================================================
-- Terminal Tokens
-- ============================================================================

identifierToExpr :: Go.Identifier -> Ast.Expr
identifierToExpr (Go.Identifier s) = cst s

intLitToExpr :: Go.IntLit -> Ast.Expr
intLitToExpr (Go.IntLit n) = cst $ show n

floatLitToExpr :: Go.FloatLit -> Ast.Expr
floatLitToExpr (Go.FloatLit d) = cst $ show d

imaginaryLitToExpr :: Go.ImaginaryLit -> Ast.Expr
imaginaryLitToExpr (Go.ImaginaryLit d) = cst $ show d ++ "i"

runeLitToExpr :: Go.RuneLit -> Ast.Expr
runeLitToExpr (Go.RuneLit c) = cst $ "'" ++ escapeRune (C.chr $ fromIntegral c) ++ "'"
  where
    escapeRune ch = case ch of
      '\'' -> "\\'"
      '\\' -> "\\\\"
      '\n' -> "\\n"
      '\r' -> "\\r"
      '\t' -> "\\t"
      _ -> if ord ch >= 32 && ord ch < 127
           then [ch]
           else if ord ch > 0xFFFF
             then -- Supplementary plane: use UTF-16 surrogate pair
               let n = ord ch - 0x10000
                   hi = 0xD800 + (n `div` 0x400)
                   lo = 0xDC00 + (n `mod` 0x400)
                   padH x = let h = fmap C.toUpper $ showHex x "" in
                            replicate (4 - L.length h) '0' ++ h
               in "\\u" ++ padH hi ++ "\\u" ++ padH lo
             else "\\u" ++ L.take (4 - L.length hex) "0000" ++ hex
               where hex = showHex (ord ch) ""

stringLitToExpr :: Go.StringLit -> Ast.Expr
stringLitToExpr lit = case lit of
  Go.StringLitRaw r -> rawStringLitToExpr r
  Go.StringLitInterpreted i -> interpretedStringLitToExpr i

rawStringLitToExpr :: Go.RawStringLit -> Ast.Expr
rawStringLitToExpr (Go.RawStringLit s) = cst $ "`" ++ s ++ "`"

interpretedStringLitToExpr :: Go.InterpretedStringLit -> Ast.Expr
interpretedStringLitToExpr (Go.InterpretedStringLit s) = cst $ "\"" ++ escapeGoString s ++ "\""
  where
    escapeGoString = concatMap escapeChar
    escapeChar c = case c of
      '"'  -> "\\\""
      '\\' -> "\\\\"
      '\n' -> "\\n"
      '\r' -> "\\r"
      '\t' -> "\\t"
      _ | c < ' ' || c > '~' -> goUnicodeEscape (ord c)
        | otherwise -> [c]
    goUnicodeEscape n
      | n > 0xFFFF = -- Supplementary plane: use UTF-16 surrogate pair
          let n' = n - 0x10000
              hi = 0xD800 + (n' `div` 0x400)
              lo = 0xDC00 + (n' `mod` 0x400)
          in "\\u" ++ padHex hi ++ "\\u" ++ padHex lo
      | otherwise = "\\u" ++ padHex n
    padHex n = replicate (4 - length hex) '0' ++ hex
      where hex = fmap toUpper $ showHex n ""

-- ============================================================================
-- Hydra-specific constructs
-- ============================================================================

annotatedDeclarationToExpr :: Go.AnnotatedDeclaration -> Ast.Expr
annotatedDeclarationToExpr (Go.AnnotatedDeclaration comment decl) = newlineSep [
  commentToExpr comment,
  topLevelDeclToExpr decl]

commentToExpr :: String -> Ast.Expr
commentToExpr s = if L.null (lines s)
  then cst ""
  else newlineSep (singleLineComment <$> lines s)

-- ============================================================================
-- Helpers
-- ============================================================================

singleLineComment :: String -> Ast.Expr
singleLineComment c = cst $ "// " ++ sanitizeGoComment c

sanitizeGoComment :: String -> String
sanitizeGoComment = id  -- Go comments don't need special escaping like HTML
