-- Stub: will be regenerated by sync
module Hydra.Test.TestSuite where
import Hydra.Testing
allTests :: TestGroup
allTests = TestGroup {testGroupName = "stub", testGroupDescription = Nothing, testGroupSubgroups = [], testGroupCases = []}
