# Note: this is an automatically generated file. Do not edit.

r"""Source-level representation of hydra.show.util."""

from __future__ import annotations
from hydra.dsl.python import FrozenDict, Just, Nothing
from typing import cast
import hydra.core
import hydra.module

def module() -> hydra.module.Module:
    return hydra.module.Module(hydra.module.Namespace("hydra.show.util"), (hydra.core.Binding(hydra.core.Name("hydra.show.util.caseConvention"), cast(hydra.core.Term, hydra.core.TermAnnotated(hydra.core.AnnotatedTerm(cast(hydra.core.Term, hydra.core.TermFunction(cast(hydra.core.Function, hydra.core.FunctionLambda(hydra.core.Lambda(hydra.core.Name("c"), Nothing(), cast(hydra.core.Term, hydra.core.TermApplication(hydra.core.Application(cast(hydra.core.Term, hydra.core.TermFunction(cast(hydra.core.Function, hydra.core.FunctionElimination(cast(hydra.core.Elimination, hydra.core.EliminationUnion(hydra.core.CaseStatement(hydra.core.Name("hydra.util.CaseConvention"), Nothing(), (hydra.core.Field(hydra.core.Name("lowerSnake"), cast(hydra.core.Term, hydra.core.TermFunction(cast(hydra.core.Function, hydra.core.FunctionLambda(hydra.core.Lambda(hydra.core.Name("_"), Nothing(), cast(hydra.core.Term, hydra.core.TermLiteral(cast(hydra.core.Literal, hydra.core.LiteralString("lower_snake_case")))))))))), hydra.core.Field(hydra.core.Name("upperSnake"), cast(hydra.core.Term, hydra.core.TermFunction(cast(hydra.core.Function, hydra.core.FunctionLambda(hydra.core.Lambda(hydra.core.Name("_"), Nothing(), cast(hydra.core.Term, hydra.core.TermLiteral(cast(hydra.core.Literal, hydra.core.LiteralString("UPPER_SNAKE_CASE")))))))))), hydra.core.Field(hydra.core.Name("camel"), cast(hydra.core.Term, hydra.core.TermFunction(cast(hydra.core.Function, hydra.core.FunctionLambda(hydra.core.Lambda(hydra.core.Name("_"), Nothing(), cast(hydra.core.Term, hydra.core.TermLiteral(cast(hydra.core.Literal, hydra.core.LiteralString("camelCase")))))))))), hydra.core.Field(hydra.core.Name("pascal"), cast(hydra.core.Term, hydra.core.TermFunction(cast(hydra.core.Function, hydra.core.FunctionLambda(hydra.core.Lambda(hydra.core.Name("_"), Nothing(), cast(hydra.core.Term, hydra.core.TermLiteral(cast(hydra.core.Literal, hydra.core.LiteralString("PascalCase")))))))))))))))))), cast(hydra.core.Term, hydra.core.TermVariable(hydra.core.Name("c"))))))))))), FrozenDict({
      hydra.core.Name("description"): cast(hydra.core.Term, hydra.core.TermLiteral(cast(hydra.core.Literal, hydra.core.LiteralString("Show a case convention as a string"))))})))), Nothing()),), (), (hydra.module.Namespace("hydra.accessors"), hydra.module.Namespace("hydra.ast"), hydra.module.Namespace("hydra.classes"), hydra.module.Namespace("hydra.coders"), hydra.module.Namespace("hydra.compute"), hydra.module.Namespace("hydra.constraints"), hydra.module.Namespace("hydra.core"), hydra.module.Namespace("hydra.grammar"), hydra.module.Namespace("hydra.graph"), hydra.module.Namespace("hydra.json.model"), hydra.module.Namespace("hydra.module"), hydra.module.Namespace("hydra.parsing"), hydra.module.Namespace("hydra.phantoms"), hydra.module.Namespace("hydra.query"), hydra.module.Namespace("hydra.relational"), hydra.module.Namespace("hydra.tabular"), hydra.module.Namespace("hydra.testing"), hydra.module.Namespace("hydra.topology"), hydra.module.Namespace("hydra.typing"), hydra.module.Namespace("hydra.util"), hydra.module.Namespace("hydra.variants"), hydra.module.Namespace("hydra.workflow")), Just("String representations of hydra.util types"))
