// Note: this is an automatically generated file. Do not edit.

package testlibmaybes

import (
  "hydra.dev/hydra/core"
  "hydra.dev/hydra/testing"
)

var AllTests = testing.TestGroup{Name: "hydra.lib.maybes primitives", Description: nil, Subgroups: []any{testing.TestGroup{Name: "apply", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "both just", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.apply")}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.add")}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 3}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}
  return &_v
}()}}}, Output: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 8}}}
  return &_v
}()}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing function", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.apply")}}, Argument: core.TermMaybe{Value: nil}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}
  return &_v
}()}}}, Output: core.TermMaybe{Value: nil}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing value", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.apply")}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.add")}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 3}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}, Output: core.TermMaybe{Value: nil}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "bind", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "just to just", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.bind")}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}
  return &_v
}()}}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}
  return &_v
}()}}}}}}, Output: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 10}}}
  return &_v
}()}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing to nothing", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.bind")}}, Argument: core.TermMaybe{Value: nil}}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}
  return &_v
}()}}}}}}, Output: core.TermMaybe{Value: nil}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "cases", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "just applies function", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.cases")}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}
  return &_v
}()}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 0}}}}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}}}}, Output: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 10}}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing returns default", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.cases")}}, Argument: core.TermMaybe{Value: nil}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 99}}}}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}}}}, Output: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 99}}}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "cat", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "filters nothings", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.cat")}}, Argument: core.TermList{Value: []any{core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 1}}}
  return &_v
}()}, core.TermMaybe{Value: nil}, core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}
  return &_v
}()}}}}}, Output: core.TermList{Value: []any{core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 1}}}, core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "all justs", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.cat")}}, Argument: core.TermList{Value: []any{core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 1}}}
  return &_v
}()}, core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}
  return &_v
}()}}}}}, Output: core.TermList{Value: []any{core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 1}}}, core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "all nothings", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.cat")}}, Argument: core.TermList{Value: []any{core.TermMaybe{Value: nil}, core.TermMaybe{Value: nil}}}}}, Output: core.TermList{Value: []any{}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "empty list", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.cat")}}, Argument: core.TermList{Value: []any{}}}}, Output: core.TermList{Value: []any{}}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "compose", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "both succeed", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.compose")}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.logic.ifElse")}}, Argument: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.equality.lte")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.add")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 1}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}}}}}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("y"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.logic.ifElse")}}, Argument: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.equality.gte")}}, Argument: core.TermVariable{Value: core.Name("y")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("y")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}}}}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}}}, Output: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 12}}}
  return &_v
}()}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "first fails", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.compose")}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.logic.ifElse")}}, Argument: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.equality.lte")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.add")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 1}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}}}}}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("y"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.logic.ifElse")}}, Argument: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.equality.gte")}}, Argument: core.TermVariable{Value: core.Name("y")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("y")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}}}}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 10}}}}}, Output: core.TermMaybe{Value: nil}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "second fails", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.compose")}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.logic.ifElse")}}, Argument: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.equality.lte")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.add")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 1}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}}}}}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("y"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.logic.ifElse")}}, Argument: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.equality.gte")}}, Argument: core.TermVariable{Value: core.Name("y")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("y")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}}}}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 3}}}}}, Output: core.TermMaybe{Value: nil}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "fromJust", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "extract from just", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.fromJust")}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}
  return &_v
}()}}}, Output: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "fromMaybe", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "just value", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.fromMaybe")}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 0}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}
  return &_v
}()}}}, Output: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing with default", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.fromMaybe")}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 99}}}}}, Argument: core.TermMaybe{Value: nil}}}, Output: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 99}}}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "isJust", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "just value", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.isJust")}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}
  return &_v
}()}}}, Output: core.TermLiteral{Value: core.LiteralBoolean{Value: true}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.isJust")}}, Argument: core.TermMaybe{Value: nil}}}, Output: core.TermLiteral{Value: core.LiteralBoolean{Value: false}}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "isNothing", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "just value", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.isNothing")}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}
  return &_v
}()}}}, Output: core.TermLiteral{Value: core.LiteralBoolean{Value: false}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.isNothing")}}, Argument: core.TermMaybe{Value: nil}}}, Output: core.TermLiteral{Value: core.LiteralBoolean{Value: true}}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "map", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "maps just value", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.map")}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}
  return &_v
}()}}}, Output: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 10}}}
  return &_v
}()}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing unchanged", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.map")}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}}}}, Argument: core.TermMaybe{Value: nil}}}, Output: core.TermMaybe{Value: nil}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "mapMaybe", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "filter and transform", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.mapMaybe")}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.logic.ifElse")}}, Argument: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.equality.gt")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}}}}}}, Argument: core.TermList{Value: []any{core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 1}}}, core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}, core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 3}}}, core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 4}}}, core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}}}}}, Output: core.TermList{Value: []any{core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 6}}}, core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 8}}}, core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 10}}}}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "empty result", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.mapMaybe")}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.logic.ifElse")}}, Argument: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.equality.gt")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}}}}}}, Argument: core.TermList{Value: []any{core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 1}}}, core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}, Output: core.TermList{Value: []any{}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "empty input", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.mapMaybe")}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.logic.ifElse")}}, Argument: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.equality.gt")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}
  return &_v
}()}}}, Argument: core.TermMaybe{Value: nil}}}}}}}}, Argument: core.TermList{Value: []any{}}}}, Output: core.TermList{Value: []any{}}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "maybe", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "just value applies function", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.maybe")}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 0}}}}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}}}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 5}}}
  return &_v
}()}}}, Output: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 10}}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing returns default", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.maybe")}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 99}}}}}, Argument: core.TermFunction{Value: core.FunctionLambda{Value: core.Lambda{Parameter: core.Name("x"), Domain: nil, Body: core.TermApplication{Value: core.Application{Function: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.math.mul")}}, Argument: core.TermVariable{Value: core.Name("x")}}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 2}}}}}}}}}}, Argument: core.TermMaybe{Value: nil}}}, Output: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 99}}}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "pure", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "wraps integer", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.pure")}}, Argument: core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}}}, Output: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}
  return &_v
}()}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "wraps string", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.pure")}}, Argument: core.TermLiteral{Value: core.LiteralString_{Value: "hello"}}}}, Output: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralString_{Value: "hello"}}
  return &_v
}()}}}, Description: nil, Tags: []any{}}}}, testing.TestGroup{Name: "toList", Description: nil, Subgroups: []any{}, Cases: []any{testing.TestCaseWithMetadata{Name: "just value", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.toList")}}, Argument: core.TermMaybe{Value: func () any {
  _v := core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}
  return &_v
}()}}}, Output: core.TermList{Value: []any{core.TermLiteral{Value: core.LiteralInteger{Value: core.IntegerValueInt32_{Value: 42}}}}}}}, Description: nil, Tags: []any{}}, testing.TestCaseWithMetadata{Name: "nothing", Case_: testing.TestCaseEvaluation{Value: testing.EvaluationTestCase{EvaluationStyle: testing.EvaluationStyleEager{}, Input: core.TermApplication{Value: core.Application{Function: core.TermFunction{Value: core.FunctionPrimitive{Value: core.Name("hydra.lib.maybes.toList")}}, Argument: core.TermMaybe{Value: nil}}}, Output: core.TermList{Value: []any{}}}}, Description: nil, Tags: []any{}}}}}, Cases: []any{}}
