-- | Coq code generator driver: a thin host-side wrapper over the DSL-ported
-- `Hydra.Coq.Generate`. Only the `generateSources` adapter and the
-- `_CoqProject` writer live here; everything else has been promoted to DSL.

module Hydra.Coq.GenerateDriver where

import qualified Hydra.Packaging as Pkg
import qualified Hydra.Coq.Generate as CoqGenerate
import qualified Hydra.Context as Context
import qualified Hydra.Graph as Graph
import qualified Hydra.Errors as Errors
import qualified Data.Map as Map
import qualified Data.Set as Set
import System.FilePath ((</>))

-- | Standard coder interface: takes an adapted Module and Definitions,
-- returns a map from file paths to file contents.
-- Thin wrapper over the DSL-ported `Hydra.Coq.Generate.moduleToCoq` that
-- adapts the generateSources signature (accepting unused Context/Graph
-- parameters and wrapping the result in Either).
moduleToCoq :: Map.Map (String, String) String -> Map.Map String Int -> Set.Set String -> Set.Set String -> Pkg.Module -> [Pkg.Definition] -> Context.Context -> Graph.Graph
  -> Either Errors.Error (Map.Map FilePath String)
moduleToCoq fieldMap constrCounts ambiguousNames globalSanitizedAcc mod defs _cx _g =
  Right (CoqGenerate.moduleToCoq fieldMap constrCounts ambiguousNames globalSanitizedAcc mod defs)

-- | Generate a _CoqProject file for the output directory.
-- Maps the physical directory to the empty logical path so that
-- e.g. hydra/Core.v becomes module "hydra.Core".
writeCoqProject :: FilePath -> IO ()
writeCoqProject baseDir = do
  let content = unlines
        [ "# Generated by Hydra's Coq code generator"
        , "-Q . \"\""
        ]
  writeFile (baseDir </> "_CoqProject") content
  putStrLn "  _CoqProject"
