(ns hydra.dependencies
  (:require [hydra.coders :refer :all] [hydra.core :refer :all] [hydra.lexical :refer :all] [hydra.lib.eithers :refer :all] [hydra.lib.equality :refer :all] [hydra.lib.lists :refer :all] [hydra.lib.literals :refer :all] [hydra.lib.logic :refer :all] [hydra.lib.maps :refer :all] [hydra.lib.math :refer :all] [hydra.lib.maybes :refer :all] [hydra.lib.pairs :refer :all] [hydra.lib.sets :refer :all] [hydra.lib.strings :refer :all] [hydra.names :refer :all] [hydra.packaging :refer :all] [hydra.rewriting :refer :all] [hydra.sorting :refer :all] [hydra.strip :refer :all] [hydra.variables :refer :all]
))

(declare hydra_dependencies_term_dependency_names hydra_dependencies_definitions_with_dependencies hydra_dependencies_flatten_let_terms hydra_dependencies_inline_type hydra_dependencies_is_lambda hydra_dependencies_lift_lambda_above_let hydra_dependencies_prune_let hydra_dependencies_replace_typedefs hydra_dependencies_simplify_term hydra_dependencies_to_short_names hydra_dependencies_topological_sort_binding_map hydra_dependencies_topological_sort_bindings hydra_dependencies_type_names_in_type hydra_dependencies_type_dependency_names hydra_dependencies_topological_sort_type_definitions)

(def hydra_dependencies_term_dependency_names (fn [binds] (fn [with_prims] (fn [with_noms] (fn [term0] (let [add_names (fn [names] (fn [term] (let [nominal (fn [name] (if with_noms ((hydra_lib_sets_insert name) names) names))] (let [prim (fn [name] (if with_prims ((hydra_lib_sets_insert name) names) names))] (let [var_ (fn [name] (if binds ((hydra_lib_sets_insert name) names) names))] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :function) ((fn [f] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :elimination) ((fn [e] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :record) ((fn [proj] (nominal ((fn [v] (:type_name v)) proj))) match_value) (= (first match_target) :union) ((fn [case_stmt] (nominal ((fn [v] (:type_name v)) case_stmt))) match_value) (= (first match_target) :wrap) ((fn [name] (nominal name)) match_value))) (second match_target))) e)) match_value) :else names)) (second match_target))) f)) match_value) (= (first match_target) :record) ((fn [record] (nominal ((fn [v] (:type_name v)) record))) match_value) (= (first match_target) :union) ((fn [injection] (nominal ((fn [v] (:type_name v)) injection))) match_value) (= (first match_target) :variable) ((fn [name] (var_ name)) match_value) (= (first match_target) :wrap) ((fn [wrapped_term] (nominal ((fn [v] (:type_name v)) wrapped_term))) match_value) :else names)) (second match_target))) term))))))] ((((hydra_rewriting_fold_over_term (list :pre nil)) add_names) hydra_lib_sets_empty) term0)))))))

(def hydra_dependencies_definitions_with_dependencies (fn [cx] (fn [graph] (fn [original] (let [dep_names (fn [el] (hydra_lib_sets_to_list ((((hydra_dependencies_term_dependency_names true) false) false) ((fn [v] (:term v)) el))))] (let [all_dep_names (hydra_lib_lists_nub ((hydra_lib_lists_concat2 ((hydra_lib_lists_map (fn [v] (:name v))) original)) (hydra_lib_lists_concat ((hydra_lib_lists_map dep_names) original))))] ((hydra_lib_eithers_map_list (fn [name] (((hydra_lexical_require_binding cx) graph) name))) all_dep_names)))))))

(def hydra_dependencies_flatten_let_terms (fn [term] (let [rewrite_binding (fn rewrite_binding [binding] (let [key0 ((fn [v] (:name v)) binding)] (let [val0 ((fn [v] (:term v)) binding)] (let [t_ ((fn [v] (:type v)) binding)] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] (let [val1 ((fn [v] (:body v)) at)] (let [ann ((fn [v] (:annotation v)) at)] (let [recursive (rewrite_binding (->hydra_core_binding key0 val1 t_))] (let [inner_binding (hydra_lib_pairs_first recursive)] (let [deps (hydra_lib_pairs_second recursive)] (let [val2 ((fn [v] (:term v)) inner_binding)] (list (->hydra_core_binding key0 (list :annotated (->hydra_core_annotated_term val2 ann)) t_) deps)))))))) match_value) (= (first match_target) :let) ((fn [inner_let] (let [bindings1 ((fn [v] (:bindings v)) inner_let)] (let [body1 ((fn [v] (:body v)) inner_let)] (let [prefix ((hydra_lib_strings_cat2 ((fn [v] v) key0)) "_")] (let [qualify (fn [n] ((hydra_lib_strings_cat2 prefix) ((fn [v] v) n)))] (let [to_subst_pair (fn [b] (list ((fn [v] (:name v)) b) (qualify ((fn [v] (:name v)) b))))] (let [subst (hydra_lib_maps_from_list ((hydra_lib_lists_map to_subst_pair) bindings1))] (let [replace_vars (hydra_variables_substitute_variables subst)] (let [new_body (replace_vars body1)] (let [new_binding (fn [b] (->hydra_core_binding (qualify ((fn [v] (:name v)) b)) (replace_vars ((fn [v] (:term v)) b)) ((fn [v] (:type v)) b)))] (list (->hydra_core_binding key0 new_body t_) ((hydra_lib_lists_map new_binding) bindings1)))))))))))) match_value) :else (list (->hydra_core_binding key0 val0 t_) (list)))) (second match_target))) val0)))))] (let [flatten_body_let (fn flatten_body_let [bindings] (fn [body] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :let) ((fn [inner_lt] (let [inner_bindings ((fn [v] (:bindings v)) inner_lt)] (let [inner_body ((fn [v] (:body v)) inner_lt)] ((flatten_body_let ((hydra_lib_lists_concat2 bindings) inner_bindings)) inner_body)))) match_value) :else (list ((hydra_lib_lists_concat2 (list)) bindings) body))) (second match_target))) body)))] (let [flatten (fn [recurse] (fn [term2] (let [rewritten (recurse term2)] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :let) ((fn [lt] (let [bindings ((fn [v] (:bindings v)) lt)] (let [body ((fn [v] (:body v)) lt)] (let [for_result (fn [hr] ((hydra_lib_lists_concat2 (hydra_lib_pairs_second hr)) (hydra_lib_lists_pure (hydra_lib_pairs_first hr))))] (let [flattened_bindings (hydra_lib_lists_concat ((hydra_lib_lists_map (fn [arg_] (for_result (rewrite_binding arg_)))) bindings))] (let [merged ((flatten_body_let flattened_bindings) body)] (let [new_bindings (hydra_lib_pairs_first merged)] (let [new_body (hydra_lib_pairs_second merged)] (list :let (->hydra_core_let new_bindings new_body)))))))))) match_value) :else rewritten)) (second match_target))) rewritten))))] ((hydra_rewriting_rewrite_term flatten) term))))))

(def hydra_dependencies_inline_type (fn [schema] (fn [typ] (let [f (fn [recurse] (fn [typ2] (let [after_recurse (fn [tr] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :variable) ((fn [v] (((hydra_lib_maybes_maybe (fn [] (list :left ((hydra_lib_strings_cat2 "No such type in schema: ") ((fn [v] v) v))))) (hydra_dependencies_inline_type schema)) ((hydra_lib_maps_lookup v) schema))) match_value) :else (list :right tr))) (second match_target))) tr))] ((hydra_lib_eithers_bind (recurse typ2)) (fn [tr] (after_recurse tr))))))] ((hydra_rewriting_rewrite_type_m f) typ)))))

(def hydra_dependencies_is_lambda (fn [term] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :function) ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :lambda) ((fn [_] true) match_value) :else false)) (second match_target))) match_value) (= (first match_target) :let) ((fn [lt] (hydra_dependencies_is_lambda ((fn [v] (:body v)) lt))) match_value) :else false)) (second match_target))) (hydra_strip_deannotate_term term))))

(def hydra_dependencies_lift_lambda_above_let (fn [term0] (let [rewrite (fn rewrite [recurse] (fn [term] (let [rewrite_binding (fn [b] (->hydra_core_binding ((fn [v] (:name v)) b) ((rewrite recurse) ((fn [v] (:term v)) b)) ((fn [v] (:type v)) b)))] (let [rewrite_bindings (fn [bs] ((hydra_lib_lists_map rewrite_binding) bs))] (let [dig_for_lambdas (fn dig_for_lambdas [original] (fn [cons] (fn [term2] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] (((dig_for_lambdas original) (fn [t_] (list :annotated (->hydra_core_annotated_term (cons t_) ((fn [v] (:annotation v)) at))))) ((fn [v] (:body v)) at))) match_value) (= (first match_target) :function) ((fn [f] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :lambda) ((fn [l] (list :function (list :lambda (->hydra_core_lambda ((fn [v] (:parameter v)) l) ((fn [v] (:domain v)) l) (((dig_for_lambdas (cons ((fn [v] (:body v)) l))) (fn [t_] (cons t_))) ((fn [v] (:body v)) l)))))) match_value) :else (recurse original))) (second match_target))) f)) match_value) (= (first match_target) :let) ((fn [l] (((dig_for_lambdas original) (fn [t_] (cons (list :let (->hydra_core_let (rewrite_bindings ((fn [v] (:bindings v)) l)) t_))))) ((fn [v] (:body v)) l))) match_value) :else (recurse original))) (second match_target))) term2))))] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :let) ((fn [l] (((dig_for_lambdas term) (fn [t_] (list :let (->hydra_core_let (rewrite_bindings ((fn [v] (:bindings v)) l)) t_)))) ((fn [v] (:body v)) l))) match_value) :else (recurse term))) (second match_target))) term))))))] ((hydra_rewriting_rewrite_term rewrite) term0))))

(def hydra_dependencies_prune_let (fn [l] (let [binding_map (hydra_lib_maps_from_list ((hydra_lib_lists_map (fn [b] (list ((fn [v] (:name v)) b) ((fn [v] (:term v)) b)))) ((fn [v] (:bindings v)) l)))] (let [root_name "[[[root]]]"] (let [adj (fn [n] ((hydra_lib_sets_intersection (hydra_lib_sets_from_list (hydra_lib_maps_keys binding_map))) (hydra_variables_free_variables_in_term (if ((hydra_lib_equality_equal n) root_name) ((fn [v] (:body v)) l) (hydra_lib_maybes_from_just ((hydra_lib_maps_lookup n) binding_map))))))] (let [reachable ((hydra_sorting_find_reachable_nodes adj) root_name)] (let [pruned_bindings ((hydra_lib_lists_filter (fn [b] ((hydra_lib_sets_member ((fn [v] (:name v)) b)) reachable))) ((fn [v] (:bindings v)) l))] (->hydra_core_let pruned_bindings ((fn [v] (:body v)) l)))))))))

(def hydra_dependencies_replace_typedefs (fn [types] (fn [typ0] (let [rewrite (fn rewrite [recurse] (fn [typ] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] (list :annotated (->hydra_core_annotated_type ((rewrite recurse) ((fn [v] (:body v)) at)) ((fn [v] (:annotation v)) at)))) match_value) (= (first match_target) :record) ((fn [_] typ) match_value) (= (first match_target) :union) ((fn [_] typ) match_value) (= (first match_target) :variable) ((fn [v] (let [for_mono (fn [t_] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :record) ((fn [_] typ) match_value) (= (first match_target) :union) ((fn [_] typ) match_value) (= (first match_target) :wrap) ((fn [_] typ) match_value) :else ((rewrite recurse) t_))) (second match_target))) t_))] (let [for_type_scheme (fn [ts] (let [t_ ((fn [v] (:type v)) ts)] (if (hydra_lib_lists_null ((fn [v] (:variables v)) ts)) (for_mono t_) typ)))] (((hydra_lib_maybes_maybe (fn [] typ)) (fn [ts] (for_type_scheme ts))) ((hydra_lib_maps_lookup v) types))))) match_value) (= (first match_target) :wrap) ((fn [_] typ) match_value) :else (recurse typ))) (second match_target))) typ)))] ((hydra_rewriting_rewrite_type rewrite) typ0)))))

(def hydra_dependencies_simplify_term (fn [term] (let [simplify (fn [recurse] (fn [term2] (let [for_rhs (fn [rhs] (fn [var_] (fn [body] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :variable) ((fn [v] (hydra_dependencies_simplify_term (((hydra_variables_substitute_variable var_) v) body))) match_value) :else term2)) (second match_target))) (hydra_strip_deannotate_term rhs)))))] (let [for_lhs (fn [lhs] (fn [rhs] (let [for_fun (fn [fun] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :lambda) ((fn [l] (let [var_ ((fn [v] (:parameter v)) l)] (let [body ((fn [v] (:body v)) l)] (if ((hydra_lib_sets_member var_) (hydra_variables_free_variables_in_term body)) (((for_rhs rhs) var_) body) (hydra_dependencies_simplify_term body))))) match_value) :else term2)) (second match_target))) fun))] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :function) ((fn [fun] (for_fun fun)) match_value) :else term2)) (second match_target))) (hydra_strip_deannotate_term lhs)))))] (let [for_term (fn [stripped] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :application) ((fn [app] (let [lhs ((fn [v] (:function v)) app)] (let [rhs ((fn [v] (:argument v)) app)] ((for_lhs lhs) rhs)))) match_value) :else term2)) (second match_target))) stripped))] (let [stripped (hydra_strip_deannotate_term term2)] (recurse (for_term stripped))))))))] ((hydra_rewriting_rewrite_term simplify) term))))

(def hydra_dependencies_to_short_names (fn [original] (let [add_name (fn [acc] (fn [name] (let [local (hydra_names_local_name_of name)] (let [group ((hydra_lib_maybes_from_maybe (fn [] hydra_lib_sets_empty)) ((hydra_lib_maps_lookup local) acc))] (((hydra_lib_maps_insert local) ((hydra_lib_sets_insert name) group)) acc)))))] (let [group_names_by_local (fn [names] (((hydra_lib_lists_foldl add_name) hydra_lib_maps_empty) names))] (let [groups (group_names_by_local original)] (let [rename_group (fn [local_names] (let [local (hydra_lib_pairs_first local_names)] (let [names (hydra_lib_pairs_second local_names)] (let [range_from (fn range_from [start] ((hydra_lib_lists_cons start) (range_from ((hydra_lib_math_add start) 1))))] (let [rename (fn [name] (fn [i] (list name (if ((hydra_lib_equality_gt i) 1) ((hydra_lib_strings_cat2 local) (hydra_lib_literals_show_int32 i)) local))))] (((hydra_lib_lists_zip_with rename) (hydra_lib_sets_to_list names)) (range_from 1)))))))] (hydra_lib_maps_from_list (hydra_lib_lists_concat ((hydra_lib_lists_map rename_group) (hydra_lib_maps_to_list groups))))))))))

(def hydra_dependencies_topological_sort_binding_map (fn [binding_map] (let [bindings (hydra_lib_maps_to_list binding_map)] (let [keys (hydra_lib_sets_from_list ((hydra_lib_lists_map hydra_lib_pairs_first) bindings))] (let [has_type_annotation (fn has_type_annotation [term] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] (has_type_annotation ((fn [v] (:body v)) at))) match_value) :else false)) (second match_target))) term))] (let [deps_of (fn [name_and_term] (let [name (hydra_lib_pairs_first name_and_term)] (let [term (hydra_lib_pairs_second name_and_term)] (list name (if (has_type_annotation term) (list) (hydra_lib_sets_to_list ((hydra_lib_sets_intersection keys) (hydra_variables_free_variables_in_term term))))))))] (let [to_pair (fn [name] (list name ((hydra_lib_maybes_from_maybe (fn [] (list :literal (list :string "Impossible!")))) ((hydra_lib_maps_lookup name) binding_map))))] ((hydra_lib_lists_map (hydra_lib_lists_map to_pair)) (hydra_sorting_topological_sort_components ((hydra_lib_lists_map deps_of) bindings))))))))))

(def hydra_dependencies_topological_sort_bindings (fn [els] (let [adjlist (fn [e] (list ((fn [v] (:name v)) e) (hydra_lib_sets_to_list ((((hydra_dependencies_term_dependency_names false) true) true) ((fn [v] (:term v)) e)))))] (hydra_sorting_topological_sort ((hydra_lib_lists_map adjlist) els)))))

(def hydra_dependencies_type_names_in_type (fn [typ0] (let [add_names (fn [names] (fn [typ] names))] ((((hydra_rewriting_fold_over_type (list :pre nil)) add_names) hydra_lib_sets_empty) typ0))))

(def hydra_dependencies_type_dependency_names (fn [with_schema] (fn [typ] (if with_schema ((hydra_lib_sets_union (hydra_variables_free_variables_in_type typ)) (hydra_dependencies_type_names_in_type typ)) (hydra_variables_free_variables_in_type typ)))))

(def hydra_dependencies_topological_sort_type_definitions (fn [defs] (let [to_pair (fn [def_] (list ((fn [v] (:name v)) def_) (hydra_lib_sets_to_list ((hydra_dependencies_type_dependency_names false) ((fn [v] (:type v)) ((fn [v] (:type v)) def_))))))] (let [name_to_def (hydra_lib_maps_from_list ((hydra_lib_lists_map (fn [d] (list ((fn [v] (:name v)) d) d))) defs))] (let [sorted (hydra_sorting_topological_sort_components ((hydra_lib_lists_map to_pair) defs))] ((hydra_lib_lists_map (fn [names] (hydra_lib_maybes_cat ((hydra_lib_lists_map (fn [n] ((hydra_lib_maps_lookup n) name_to_def))) names)))) sorted))))))
