(ns hydra.strip
  (:require [hydra.core :refer :all] [hydra.lib.lists :refer :all] [hydra.rewriting :refer :all]
))

(declare hydra_strip_deannotate_and_detype_term hydra_strip_deannotate_term hydra_strip_deannotate_type hydra_strip_deannotate_type_parameters hydra_strip_deannotate_type_recursive hydra_strip_deannotate_type_scheme_recursive hydra_strip_detype_term hydra_strip_remove_term_annotations hydra_strip_remove_type_annotations hydra_strip_remove_type_annotations_from_term hydra_strip_remove_types_from_term hydra_strip_strip_type_lambdas)

(def hydra_strip_deannotate_and_detype_term (fn [t_] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] (hydra_strip_deannotate_and_detype_term ((fn [v] (:body v)) at))) match_value) (= (first match_target) :type_application) ((fn [tt] (hydra_strip_deannotate_and_detype_term ((fn [v] (:body v)) tt))) match_value) (= (first match_target) :type_lambda) ((fn [ta] (hydra_strip_deannotate_and_detype_term ((fn [v] (:body v)) ta))) match_value) :else t_)) (second match_target))) t_)))

(def hydra_strip_deannotate_term (fn [t_] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] (hydra_strip_deannotate_term ((fn [v] (:body v)) at))) match_value) :else t_)) (second match_target))) t_)))

(def hydra_strip_deannotate_type (fn [t_] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [arg_] (hydra_strip_deannotate_type ((fn [v] (:body v)) arg_))) match_value) :else t_)) (second match_target))) t_)))

(def hydra_strip_deannotate_type_parameters (fn [t_] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :forall) ((fn [lt] (hydra_strip_deannotate_type_parameters ((fn [v] (:body v)) lt))) match_value) :else t_)) (second match_target))) (hydra_strip_deannotate_type t_))))

(def hydra_strip_deannotate_type_recursive (fn [typ] (let [strip (fn [recurse] (fn [typ2] (let [rewritten (recurse typ2)] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] ((fn [v] (:body v)) at)) match_value) :else rewritten)) (second match_target))) rewritten))))] ((hydra_rewriting_rewrite_type strip) typ))))

(def hydra_strip_deannotate_type_scheme_recursive (fn [ts] (let [vars ((fn [v] (:variables v)) ts)] (let [typ ((fn [v] (:type v)) ts)] (let [constraints ((fn [v] (:constraints v)) ts)] (->hydra_core_type_scheme vars (hydra_strip_deannotate_type_recursive typ) constraints))))))

(def hydra_strip_detype_term (fn [t_] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] (let [subj ((fn [v] (:body v)) at)] (let [ann ((fn [v] (:annotation v)) at)] (list :annotated (->hydra_core_annotated_term (hydra_strip_detype_term subj) ann))))) match_value) (= (first match_target) :type_application) ((fn [tt] (hydra_strip_deannotate_and_detype_term ((fn [v] (:body v)) tt))) match_value) (= (first match_target) :type_lambda) ((fn [ta] (hydra_strip_deannotate_and_detype_term ((fn [v] (:body v)) ta))) match_value) :else t_)) (second match_target))) t_)))

(def hydra_strip_remove_term_annotations (fn [term] (let [remove (fn [recurse] (fn [term2] (let [rewritten (recurse term2)] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] ((fn [v] (:body v)) at)) match_value) :else rewritten)) (second match_target))) term2))))] ((hydra_rewriting_rewrite_term remove) term))))

(def hydra_strip_remove_type_annotations (fn [typ] (let [remove (fn [recurse] (fn [typ2] (let [rewritten (recurse typ2)] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] ((fn [v] (:body v)) at)) match_value) :else rewritten)) (second match_target))) rewritten))))] ((hydra_rewriting_rewrite_type remove) typ))))

(def hydra_strip_remove_type_annotations_from_term (fn [term] (let [strip (fn [recurse] (fn [term2] (let [rewritten (recurse term2)] (let [strip_binding (fn [b] (->hydra_core_binding ((fn [v] (:name v)) b) ((fn [v] (:term v)) b) (list :nothing)))] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :let) ((fn [lt] (list :let (->hydra_core_let ((hydra_lib_lists_map strip_binding) ((fn [v] (:bindings v)) lt)) ((fn [v] (:body v)) lt)))) match_value) (= (first match_target) :type_application) ((fn [tt] ((fn [v] (:body v)) tt)) match_value) (= (first match_target) :type_lambda) ((fn [ta] ((fn [v] (:body v)) ta)) match_value) :else rewritten)) (second match_target))) rewritten)))))] ((hydra_rewriting_rewrite_term strip) term))))

(def hydra_strip_remove_types_from_term (fn [term] (let [strip (fn [recurse] (fn [term2] (let [rewritten (recurse term2)] (let [strip_binding (fn [b] (->hydra_core_binding ((fn [v] (:name v)) b) ((fn [v] (:term v)) b) (list :nothing)))] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :function) ((fn [f] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :elimination) ((fn [e] (list :function (list :elimination e))) match_value) (= (first match_target) :lambda) ((fn [l] (list :function (list :lambda (->hydra_core_lambda ((fn [v] (:parameter v)) l) (list :nothing) ((fn [v] (:body v)) l))))) match_value) :else (list :function f))) (second match_target))) f)) match_value) (= (first match_target) :let) ((fn [lt] (list :let (->hydra_core_let ((hydra_lib_lists_map strip_binding) ((fn [v] (:bindings v)) lt)) ((fn [v] (:body v)) lt)))) match_value) (= (first match_target) :type_application) ((fn [tt] ((fn [v] (:body v)) tt)) match_value) (= (first match_target) :type_lambda) ((fn [ta] ((fn [v] (:body v)) ta)) match_value) :else rewritten)) (second match_target))) rewritten)))))] ((hydra_rewriting_rewrite_term strip) term))))

(def hydra_strip_strip_type_lambdas (fn [t_] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :annotated) ((fn [at] (let [subj ((fn [v] (:body v)) at)] (let [ann ((fn [v] (:annotation v)) at)] (list :annotated (->hydra_core_annotated_term (hydra_strip_strip_type_lambdas subj) ann))))) match_value) (= (first match_target) :type_lambda) ((fn [ta] (hydra_strip_strip_type_lambdas ((fn [v] (:body v)) ta))) match_value) :else t_)) (second match_target))) t_)))
