(require 'cl-lib)

(require 'hydra.core)

(require 'hydra.graph)

(require 'hydra.lib.lists)

(require 'hydra.lib.maps)

(require 'hydra.lib.maybes)

(require 'hydra.lib.sets)

(defvar hydra_scoping_f_type_to_type_scheme (lambda (typ) (letrec ((strip_annotations (lambda (t_) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :annotated) (funcall (lambda (at) (strip_annotations (funcall (lambda (v) (hydra_core_annotated_type-body v)) at))) match_value)) (t t_))) (cadr match_target))) t_)))) (letrec ((gather_forall (lambda (vars) (lambda (typ2) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :forall) (funcall (lambda (ft) (funcall (gather_forall (funcall (hydra_lib_lists_cons (funcall (lambda (v) (hydra_core_forall_type-parameter v)) ft)) vars)) (funcall (lambda (v) (hydra_core_forall_type-body v)) ft))) match_value)) (t (make-hydra_core_type_scheme (hydra_lib_lists_reverse vars) typ2 (list :nothing))))) (cadr match_target))) (strip_annotations typ2)))))) (funcall (gather_forall (list)) typ)))))

(defvar hydra_scoping_extend_graph_for_lambda (lambda (g) (lambda (lam) (let ((var_ (funcall (lambda (v) (hydra_core_lambda-parameter v)) lam))) (make-hydra_graph_graph (funcall (lambda (v) (hydra_graph_graph-bound_terms v)) g) (funcall (funcall (hydra_lib_maybes_maybe (lambda () (funcall (lambda (v) (hydra_graph_graph-bound_types v)) g))) (lambda (dom) (funcall (funcall (hydra_lib_maps_insert var_) (hydra_scoping_f_type_to_type_scheme dom)) (funcall (lambda (v) (hydra_graph_graph-bound_types v)) g)))) (funcall (lambda (v) (hydra_core_lambda-domain v)) lam)) (funcall (lambda (v) (hydra_graph_graph-class_constraints v)) g) (funcall (hydra_lib_sets_insert var_) (funcall (lambda (v) (hydra_graph_graph-lambda_variables v)) g)) (funcall (hydra_lib_maps_delete var_) (funcall (lambda (v) (hydra_graph_graph-metadata v)) g)) (funcall (lambda (v) (hydra_graph_graph-primitives v)) g) (funcall (lambda (v) (hydra_graph_graph-schema_types v)) g) (funcall (lambda (v) (hydra_graph_graph-type_variables v)) g))))))

(defvar hydra_scoping_extend_graph_with_bindings (lambda (bindings) (lambda (g) (let ((new_terms (hydra_lib_maps_from_list (funcall (hydra_lib_lists_map (lambda (b) (list (funcall (lambda (v) (hydra_core_binding-name v)) b) (funcall (lambda (v) (hydra_core_binding-term v)) b)))) bindings)))) (let ((new_types (hydra_lib_maps_from_list (hydra_lib_maybes_cat (funcall (hydra_lib_lists_map (lambda (b) (funcall (hydra_lib_maybes_map (lambda (ts) (list (funcall (lambda (v) (hydra_core_binding-name v)) b) ts))) (funcall (lambda (v) (hydra_core_binding-type v)) b)))) bindings))))) (make-hydra_graph_graph (funcall (hydra_lib_maps_union new_terms) (funcall (lambda (v) (hydra_graph_graph-bound_terms v)) g)) (funcall (hydra_lib_maps_union new_types) (funcall (lambda (v) (hydra_graph_graph-bound_types v)) g)) (funcall (lambda (v) (hydra_graph_graph-class_constraints v)) g) (funcall (lambda (v) (hydra_graph_graph-lambda_variables v)) g) (funcall (lambda (v) (hydra_graph_graph-metadata v)) g) (funcall (lambda (v) (hydra_graph_graph-primitives v)) g) (funcall (lambda (v) (hydra_graph_graph-schema_types v)) g) (funcall (lambda (v) (hydra_graph_graph-type_variables v)) g)))))))

(defvar hydra_scoping_extend_graph_for_let (lambda (for_binding) (lambda (g) (lambda (letrec_) (let ((bindings (funcall (lambda (v) (hydra_core_let-bindings v)) letrec_))) (let ((g2 (funcall (hydra_scoping_extend_graph_with_bindings bindings) g))) (make-hydra_graph_graph (funcall (hydra_lib_maps_union (hydra_lib_maps_from_list (funcall (hydra_lib_lists_map (lambda (b) (list (funcall (lambda (v) (hydra_core_binding-name v)) b) (funcall (lambda (v) (hydra_core_binding-term v)) b)))) bindings))) (funcall (lambda (v) (hydra_graph_graph-bound_terms v)) g)) (funcall (hydra_lib_maps_union (hydra_lib_maps_from_list (hydra_lib_maybes_cat (funcall (hydra_lib_lists_map (lambda (b) (funcall (hydra_lib_maybes_map (lambda (ts) (list (funcall (lambda (v) (hydra_core_binding-name v)) b) ts))) (funcall (lambda (v) (hydra_core_binding-type v)) b)))) bindings)))) (funcall (lambda (v) (hydra_graph_graph-bound_types v)) g)) (funcall (lambda (v) (hydra_graph_graph-class_constraints v)) g) (funcall (funcall (hydra_lib_lists_foldl (lambda (s) (lambda (b) (funcall (hydra_lib_sets_delete (funcall (lambda (v) (hydra_core_binding-name v)) b)) s)))) (funcall (lambda (v) (hydra_graph_graph-lambda_variables v)) g)) bindings) (funcall (lambda (v) (hydra_graph_graph-metadata v)) (funcall (funcall (hydra_lib_lists_foldl (lambda (g_acc) (lambda (b) (let ((m (funcall (lambda (v) (hydra_graph_graph-metadata v)) g_acc))) (let ((new_meta (funcall (funcall (hydra_lib_maybes_maybe (lambda () (funcall (hydra_lib_maps_delete (funcall (lambda (v) (hydra_core_binding-name v)) b)) m))) (lambda (t_) (funcall (funcall (hydra_lib_maps_insert (funcall (lambda (v) (hydra_core_binding-name v)) b)) t_) m))) (funcall (for_binding g_acc) b)))) (make-hydra_graph_graph (funcall (lambda (v) (hydra_graph_graph-bound_terms v)) g_acc) (funcall (lambda (v) (hydra_graph_graph-bound_types v)) g_acc) (funcall (lambda (v) (hydra_graph_graph-class_constraints v)) g_acc) (funcall (lambda (v) (hydra_graph_graph-lambda_variables v)) g_acc) new_meta (funcall (lambda (v) (hydra_graph_graph-primitives v)) g_acc) (funcall (lambda (v) (hydra_graph_graph-schema_types v)) g_acc) (funcall (lambda (v) (hydra_graph_graph-type_variables v)) g_acc))))))) g2) bindings)) (funcall (lambda (v) (hydra_graph_graph-primitives v)) g) (funcall (lambda (v) (hydra_graph_graph-schema_types v)) g) (funcall (lambda (v) (hydra_graph_graph-type_variables v)) g))))))))

(defvar hydra_scoping_extend_graph_for_type_lambda (lambda (g) (lambda (tlam) (let ((name (funcall (lambda (v) (hydra_core_type_lambda-parameter v)) tlam))) (make-hydra_graph_graph (funcall (lambda (v) (hydra_graph_graph-bound_terms v)) g) (funcall (lambda (v) (hydra_graph_graph-bound_types v)) g) (funcall (lambda (v) (hydra_graph_graph-class_constraints v)) g) (funcall (lambda (v) (hydra_graph_graph-lambda_variables v)) g) (funcall (lambda (v) (hydra_graph_graph-metadata v)) g) (funcall (lambda (v) (hydra_graph_graph-primitives v)) g) (funcall (lambda (v) (hydra_graph_graph-schema_types v)) g) (funcall (hydra_lib_sets_insert name) (funcall (lambda (v) (hydra_graph_graph-type_variables v)) g)))))))

(defvar hydra_scoping_type_scheme_to_f_type (lambda (ts) (let ((vars (funcall (lambda (v) (hydra_core_type_scheme-variables v)) ts))) (let ((body (funcall (lambda (v) (hydra_core_type_scheme-type v)) ts))) (funcall (funcall (hydra_lib_lists_foldl (lambda (t_) (lambda (v) (list :forall (make-hydra_core_forall_type v t_))))) body) (hydra_lib_lists_reverse vars))))))

(provide 'hydra.scoping)
