name:       hydra-ext
version:    0.15.0
author:     josh@fortytwo.net
license:    Apache-2.0
category:   Data
synopsis:   Built-in extensions to Hydra, including models, coders, and utilities
github:     CategoricalData/hydra

extra-source-files:
  - LICENSE
  - README.md
  - stack.yaml

dependencies: # copied from ../hydra-haskell/package.yaml
  - aeson                         >= 2.1.0 && < 2.3
  - base                          >= 4.19.0 && < 4.22
  - base64-bytestring             >= 1.2.1 && < 1.3
  - bytestring                    >= 0.11.5 && < 0.13
  - containers                    >= 0.6.7 && < 0.8
  - directory                     >= 1.3.6 && < 1.4
  - filepath                      >= 1.4.200 && < 1.6
  - regex-tdfa                    >= 1.3.2 && < 1.4
  - scientific                    >= 0.3.7 && < 0.4
  - split                         >= 0.2.3 && < 0.3
  - text                          >= 2.0.2 && < 2.2
  - vector                        >= 0.12.0 && < 0.14

library:
  source-dirs:
    - src/main/haskell
    - src/gen-main/haskell
    - ../hydra-coq/src/main/haskell
    - ../hydra-haskell/src/main/haskell
    - ../hydra-haskell/src/gen-main/haskell
    - ../hydra-java/src/main/haskell
    - ../hydra-javascript/src/main/haskell
    - ../hydra-kernel/src/main/haskell
    - ../hydra-kernel/src/gen-main/haskell
    - ../hydra-lisp/src/main/haskell
    - ../hydra-python/src/main/haskell
    - ../hydra-scala/src/main/haskell
  ghc-options: [-rtsopts]

executables:
  update-haskell-ext-main:
    main: Main.hs
    source-dirs:
      - src/exec/update-haskell-ext-main
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-scala:
    main: Main.hs
    source-dirs:
      - src/exec/update-scala
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-scala-tests:
    main: Main.hs
    source-dirs:
      - src/exec/update-scala-tests
      - ../hydra-kernel/src/gen-test/haskell
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext
      - hspec                      >= 2.11.0 && < 2.12

  update-ext-sources:
    main: Main.hs
    source-dirs:
      - src/exec/update-ext-sources
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-json-ext:
    main: Main.hs
    source-dirs:
      - src/exec/update-json-ext
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  diag-module:
    main: Main.hs
    source-dirs:
      - src/exec/diag-module
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  generate-lisp:
    main: Main.hs
    source-dirs:
      - src/exec/generate-lisp
      - ../hydra-kernel/src/gen-test/haskell
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext
      - hspec                      >= 2.11.0 && < 2.12

  generate-coq:
    main: Main.hs
    source-dirs:
      - src/exec/generate-coq
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  bootstrap-from-json:
    main: Main.hs
    source-dirs:
      - src/exec/bootstrap-from-json
      - ../hydra-kernel/src/gen-test/haskell
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext
      - hspec                      >= 2.11.0 && < 2.12
      - time

tests:
  hydra-ext-test:
    main: Spec.hs
    source-dirs:
      - src/test/haskell
      - ../hydra-kernel/src/gen-test/haskell
    dependencies:
      - hydra-ext
      - hspec                      >= 2.11.0 && < 2.12
      - hspec-discover              >= 2.11.0 && < 2.12
      - HUnit
      - QuickCheck
      - mtl