// Note: this is an automatically generated file. Do not edit.

package hydra.test.lib.strings;

/**
 * Test cases for hydra.lib.strings primitives
 */
public interface Strings {
  static hydra.testing.TestGroup allTests() {
    return new hydra.testing.TestGroup("hydra.lib.strings primitives", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), java.util.List.of(
      new hydra.testing.TestGroup("cat", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("basic concatenation", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("one")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("two")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("three")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("onetwothree")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat"))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty list", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat"))), new hydra.core.Term.List((java.util.List<hydra.core.Term>) (java.util.List.<hydra.core.Term>of())))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("with empty strings", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("one")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("one")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("all empty strings", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode strings", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u4E16")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\uD83C\uDF0D")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1\u4E16\uD83C\uDF0D")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("combining characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("e")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u0301")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("e\u0301")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("control characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\t")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\r")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\t\r")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("null character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u0000")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("world")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello\u0000world")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("cat2", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("basic concatenation", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat2"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("world")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("helloworld")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty first string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat2"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("world")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("world")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty second string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat2"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("both empty strings", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat2"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat2"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u4E16")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1\u4E16")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("special characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat2"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\t")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\t")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("null characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.cat2"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello\u0000")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("world")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello\u0000world")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("charAt", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("first character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.charAt"))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(0))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(104))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("middle character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.charAt"))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(2))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(108))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("last character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.charAt"))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(4))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(111))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single character string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.charAt"))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(0))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(97))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.charAt"))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(0))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(241))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("multi-byte unicode", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.charAt"))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(0))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u4E16")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(19990))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("second of combining pair", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.charAt"))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(1))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("e\u0301")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(769))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("fromList", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("basic ascii string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.fromList"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(104))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(101))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(108))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(108))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(111))))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty code point list", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.fromList"))), new hydra.core.Term.List((java.util.List<hydra.core.Term>) (java.util.List.<hydra.core.Term>of())))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.fromList"))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(97))))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.fromList"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(241))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(19990))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(127757))))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1\u4E16\uD83C\uDF0D")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("combining character sequence", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.fromList"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(101))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(769))))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("e\u0301")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("special characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.fromList"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(10))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(9))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(13))))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\t\r")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("null character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.fromList"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(104))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(0))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(105))))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("h\u0000i")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("intercalate", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("comma separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.intercalate"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(",")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("one")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("two")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("three")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("one,two,three")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.intercalate"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("b")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("c")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("abc")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("multi-character separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.intercalate"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(" | ")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("A")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("B")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("C")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("A | B | C")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty string list", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.intercalate"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(",")))), new hydra.core.Term.List((java.util.List<hydra.core.Term>) (java.util.List.<hydra.core.Term>of())))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single item list", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.intercalate"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(",")))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.String_("only")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("only")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty strings in list", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.intercalate"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(",")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(",a,")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.intercalate"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\uD83C\uDF0D")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("link1")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("link2")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("link1\uD83C\uDF0Dlink2")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("newline separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.intercalate"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("line1")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("line2")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("line1\nline2")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("length", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("empty string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.length"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(0))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.length"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(1))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("basic word", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.length"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(5))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.length"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1\u4E16\uD83C\uDF0D")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(3))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("combining character sequence", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.length"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("e\u0301")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(2))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("special characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.length"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\t\r")))), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(3))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("lines", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("single line", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello world")))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello world")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("two lines", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello\nworld")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("world")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("three lines", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("one\ntwo\nthree")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("one")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("two")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("three")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.List((java.util.List<hydra.core.Term>) (java.util.List.<hydra.core.Term>of())))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("just newline", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n")))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("trailing newline", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello\n")))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("leading newline", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\nhello")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("multiple consecutive newlines", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a\n\nb")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("b")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode content", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1\n\u4E16")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u4E16")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("tabs not split", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.lines"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a\tb\nc")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("a\tb")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("c")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("null", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("empty string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.null"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.Boolean_(true)))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.null"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")))), new hydra.core.Term.Literal(new hydra.core.Literal.Boolean_(false)))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("space", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.null"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(" ")))), new hydra.core.Term.Literal(new hydra.core.Literal.Boolean_(false)))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode space", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.null"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00A0")))), new hydra.core.Term.Literal(new hydra.core.Literal.Boolean_(false)))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("newline", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.null"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n")))), new hydra.core.Term.Literal(new hydra.core.Literal.Boolean_(false)))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("null character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.null"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u0000")))), new hydra.core.Term.Literal(new hydra.core.Literal.Boolean_(false)))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("multi-character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.null"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.Literal(new hydra.core.Literal.Boolean_(false)))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("splitOn", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("basic separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("ss")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("Mississippi")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("Mi")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("i")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("ippi")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single char separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(" ")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("one two three")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("one")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("two")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("three")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("multi-char separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("  ")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a  b  c")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("b")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("c")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("separator not found", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("x")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("separator at start", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("h")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("ello")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("separator at end", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("o")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("hell")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("leading and trailing separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(" ")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(" one two ")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("one")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("two")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("whole string as separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("Mississippi")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("Mississippi")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("consecutive separators", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(" ")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a  b")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("b")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("multiple occurrences", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("l")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("he")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("o")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("overlapping pattern", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("aa")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("aaa")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("abc")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("b")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("c")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("separator on empty string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("x")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("both empty", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single char both", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u4E16")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello\u4E16world")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("world")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode content", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_(",")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1,\u4E16,\uD83C\uDF0D")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u4E16")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\uD83C\uDF0D")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("newline separator", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.splitOn"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("line1\nline2\nline3")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("line1")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("line2")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("line3")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("toList", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("empty string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toList"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.List((java.util.List<hydra.core.Term>) (java.util.List.<hydra.core.Term>of())))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toList"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(97))))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("basic word", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toList"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(104))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(101))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(108))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(108))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(111))))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toList"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1\u4E16\uD83C\uDF0D")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(241))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(19990))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(127757))))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("combining character sequence", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toList"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("e\u0301")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(101))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(769))))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("control characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toList"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\t\r")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(10))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(9))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(13))))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("null character", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toList"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("h\u0000i")))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(104))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(0))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(105))))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("toLower", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("mixed case", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toLower"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("Hello World")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello world")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("all uppercase", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toLower"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("HELLO")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("all lowercase", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toLower"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toLower"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("with numbers and punctuation", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toLower"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("Abc123, XYZ!")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("abc123, xyz!")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("control characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toLower"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\t\r")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\t\r")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode accented chars", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toLower"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00D1\u00C1\u00C9\u00CD\u00D3\u00DA")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1\u00E1\u00E9\u00ED\u00F3\u00FA")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("toUpper", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("mixed case", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toUpper"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello World")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("HELLO WORLD")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("all lowercase", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toUpper"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("HELLO")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("all uppercase", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toUpper"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("HELLO")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("HELLO")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty string", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toUpper"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("with numbers and punctuation", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toUpper"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("abc123, xyz!")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("ABC123, XYZ!")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("control characters", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toUpper"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\t\r")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\t\r")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode accented chars", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.toUpper"))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1\u00E1\u00E9\u00ED\u00F3\u00FA")))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00D1\u00C1\u00C9\u00CD\u00D3\u00DA")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("unlines", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("multiple lines", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.unlines"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("one")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("two")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("three")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("one\ntwo\nthree\n")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("single line", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.unlines"))), new hydra.core.Term.List(java.util.List.of(new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello\n")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty list", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.unlines"))), new hydra.core.Term.List((java.util.List<hydra.core.Term>) (java.util.List.<hydra.core.Term>of())))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("with empty lines", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.unlines"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("world")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello\n\nworld\n")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("all empty lines", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.unlines"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\n\n\n")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("unicode content", new hydra.testing.TestCase.Evaluation(new hydra.testing.EvaluationTestCase(new hydra.testing.EvaluationStyle.Eager(), new hydra.core.Term.Application(new hydra.core.Application(new hydra.core.Term.Function(new hydra.core.Function.Primitive(new hydra.core.Name("hydra.lib.strings.unlines"))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1o\u00F1o")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u4E16\u754C")))))), new hydra.core.Term.Literal(new hydra.core.Literal.String_("\u00F1o\u00F1o\n\u4E16\u754C\n")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of()))))), (java.util.List<hydra.testing.TestCaseWithMetadata>) (java.util.List.<hydra.testing.TestCaseWithMetadata>of()));
  }
}
