module Hydra.Sources.Kernel.Terms.Constants where

-- Standard imports for kernel terms modules
import Hydra.Kernel hiding (
  ignoredVariable, keyClasses, keyDebugId, keyDeprecated, keyDescription,
  keyExclude, keyFirstClassType, keyFreshTypeVariableCount, keyMaxLength, keyMinLength,
  keyPreserveFieldName, keyType, maxInt32, maxTraceDepth,
  regexCamelCase, regexNamespace, regexPackageName, regexPascalCase,
  warningAutoGeneratedFile)
import qualified Hydra.Dsl.Paths    as Paths
import qualified Hydra.Overlay.Haskell.Dsl.Annotations       as Annotations
import qualified Hydra.Dsl.Ast          as Ast
import qualified Hydra.Overlay.Haskell.Bootstrap         as Bootstrap
import qualified Hydra.Dsl.Coders       as Coders
import qualified Hydra.Dsl.Util      as Util
import qualified Hydra.Overlay.Haskell.Dsl.Typed.Core         as Core
import qualified Hydra.Overlay.Haskell.Dsl.Typed.Graph        as Graph
import qualified Hydra.Dsl.Json.Model         as Json
import qualified Hydra.Dsl.Lib.Chars    as Chars
import qualified Hydra.Dsl.Lib.Eithers  as Eithers
import qualified Hydra.Dsl.Lib.Equality as Equality
import qualified Hydra.Dsl.Lib.Lists    as Lists
import qualified Hydra.Dsl.Lib.Literals as Literals
import qualified Hydra.Dsl.Lib.Logic    as Logic
import qualified Hydra.Dsl.Lib.Maps     as Maps
import qualified Hydra.Dsl.Lib.Math     as Math
import qualified Hydra.Dsl.Lib.Optionals   as Optionals
import qualified Hydra.Dsl.Lib.Pairs    as Pairs
import qualified Hydra.Dsl.Lib.Sets     as Sets
import qualified Hydra.Dsl.Lib.Strings  as Strings
import qualified Hydra.Overlay.Haskell.Dsl.Literals          as Literals
import qualified Hydra.Overlay.Haskell.Dsl.LiteralTypes      as LiteralTypes
import qualified Hydra.Overlay.Haskell.Dsl.Typed.Base         as MetaBase
import qualified Hydra.Overlay.Haskell.Dsl.Typed.Terms        as MetaTerms
import qualified Hydra.Overlay.Haskell.Dsl.Typed.Types        as MetaTypes
import qualified Hydra.Dsl.Packaging       as Packaging
import qualified Hydra.Dsl.Parsing      as Parsing
import           Hydra.Overlay.Haskell.Dsl.Typed.Phantoms     as Phantoms
import qualified Hydra.Overlay.Haskell.Dsl.Prims             as Prims
import qualified Hydra.Overlay.Haskell.Dsl.Typed.Tabular           as Tabular
import qualified Hydra.Overlay.Haskell.Dsl.Typed.Testing      as Testing
import qualified Hydra.Overlay.Haskell.Dsl.Terms             as Terms
import qualified Hydra.Overlay.Haskell.Dsl.Tests             as Tests
import qualified Hydra.Dsl.Topology     as Topology
import qualified Hydra.Overlay.Haskell.Dsl.Types             as Types
import qualified Hydra.Dsl.Typing       as Typing
import qualified Hydra.Dsl.Util         as Util
import qualified Hydra.Overlay.Haskell.Dsl.Typed.Variants     as Variants
import           Hydra.Sources.Kernel.Types.All
import           Prelude hiding ((++))
import qualified Data.Char                   as Char
import qualified Data.Int                    as I
import qualified Data.List                   as L
import qualified Data.Map                    as M
import qualified Data.Set                    as S
import qualified Data.Maybe                  as Y


ns :: ModuleName
ns = ModuleName "hydra.constants"

module_ :: Module
module_ = Module {
            moduleName = ns,
            moduleDefinitions = definitions,
            moduleDependencies = Bootstrap.unqualifiedDep <$> (kernelTypesModuleNames),
            moduleMetadata = Bootstrap.descriptionMetadata (Just ("A module for tier-0 constants."))}
  where
   definitions = [
     toDefinition ignoredVariable,
     toDefinition keyClasses,
     toDefinition keyDebugId,
     toDefinition keyDeprecated,
     toDefinition keyDescription,
     toDefinition keyExclude,
     toDefinition keyFirstClassType,
     toDefinition keyFreshTypeVariableCount,
     toDefinition keyMaxLength,
     toDefinition keyMinLength,
     toDefinition keyPreserveFieldName,
     toDefinition keyType,
     toDefinition maxInt32,
     toDefinition maxTraceDepth,
     toDefinition regexCamelCase,
     toDefinition regexNamespace,
     toDefinition regexPackageName,
     toDefinition regexPascalCase,
     toDefinition warningAutoGeneratedFile]

define :: String -> TypedTerm a -> TypedTermDefinition a
define = definitionInModule module_

defineAnnotationKey :: String -> Maybe String -> TypedTermDefinition Name
defineAnnotationKey name mdesc = define ("key" <> capitalize name) $ case mdesc of
    Nothing -> def
    Just comment -> doc comment def
  where
    def = wrap _Name $ string name
    capitalize [] = []
    capitalize (c:cs) = Char.toUpper c : cs

ignoredVariable :: TypedTermDefinition String
ignoredVariable = define "ignoredVariable" $
  doc "The name used for ignored variables" $
  string "_"

keyClasses = defineAnnotationKey "classes" $ Just "Annotation key for type classes"
keyDebugId = defineAnnotationKey "debugId" $ Just "Annotation key for debug identifiers"
keyDeprecated = defineAnnotationKey "deprecated" $ Just "Annotation key for deprecated markers"
keyDescription = defineAnnotationKey "description" $ Just "Annotation key for descriptions"
keyExclude = defineAnnotationKey "exclude" $ Just "Annotation key for exclusions"
keyFirstClassType = defineAnnotationKey "firstClassType" $
  Just "A flag which tells the language coders to encode a given encoded type as a term rather than a native type"
keyFreshTypeVariableCount = defineAnnotationKey "freshTypeVariableCount" $
  Just "A counter for generating fresh type variable names"
keyMaxLength = defineAnnotationKey "maxLength" $ Just "Annotation key for maximum length constraints"
keyMinLength = defineAnnotationKey "minLength" $ Just "Annotation key for minimum length constraints"
keyPreserveFieldName = defineAnnotationKey "preserveFieldName" $ Just "Annotation key for preserving field names during code generation"
keyType = defineAnnotationKey "type" $ Just "Annotation key for type information"

maxInt32 :: TypedTermDefinition Int
maxInt32 = define "maxInt32" $
  doc "The maximum value of a 32-bit integer" $
  int32 2147483647 -- 2^31 - 1

maxTraceDepth :: TypedTermDefinition Int
maxTraceDepth = define "maxTraceDepth" $
  doc ("A maximum depth for nested computations."
    <> " Currently, this is set very high because deep recursion is common in type inference over the Hydra kernel.") $
  int32 5000

regexCamelCase :: TypedTermDefinition String
regexCamelCase = define "regexCamelCase" $
  doc "Regex matching a camelCase identifier: starts with a lowercase letter, then any letters or digits." $
  string "^[a-z][a-zA-Z0-9]*$"

regexNamespace :: TypedTermDefinition String
regexNamespace = define "regexNamespace" $
  doc "Regex matching a Hydra namespace: dot-separated camelCase segments, each starting with a lowercase letter." $
  string "^[a-z][a-zA-Z0-9]*(\\.[a-z][a-zA-Z0-9]*)*$"

regexPackageName :: TypedTermDefinition String
regexPackageName = define "regexPackageName" $
  doc "Regex matching a Hydra package name: hyphen-separated lowercase segments, each starting with a letter." $
  string "^[a-z][a-z0-9]*(-[a-z][a-z0-9]*)*$"

regexPascalCase :: TypedTermDefinition String
regexPascalCase = define "regexPascalCase" $
  doc "Regex matching a PascalCase identifier: starts with an uppercase letter, then any letters or digits." $
  string "^[A-Z][a-zA-Z0-9]*$"

warningAutoGeneratedFile :: TypedTermDefinition String
warningAutoGeneratedFile = define "warningAutoGeneratedFile" $
  doc "A standard warning message for auto-generated files" $
  string "Note: this is an automatically generated file. Do not edit."
