(require 'cl-lib)

(require 'hydra.core)

(require 'hydra.errors)

(require 'hydra.extract.helpers)

(require 'hydra.lexical)

(require 'hydra.lib.eithers)

(require 'hydra.relational)

(defvar hydra_decode_relational_column_name (lambda (cx) (lambda (raw) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :wrap) (funcall (lambda (wrapped_term) (funcall (hydra_lib_eithers_map (lambda (b) b)) (funcall (funcall (lambda (cx2) (lambda (raw2) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped2) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :literal) (funcall (lambda (v) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :string) (funcall (lambda (s) (list :right s)) match_value)) (t (list :left "expected string literal")))) (cadr match_target))) v)) match_value)) (t (list :left "expected literal")))) (cadr match_target))) stripped2))) (funcall (hydra_lexical_strip_and_dereference_term_either cx2) raw2)))) cx) (funcall (lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) (funcall (hydra_lexical_strip_and_dereference_term_either cx) raw)))))

(defvar hydra_decode_relational_column_schema (lambda (t_) (lambda (cx) (lambda (raw) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :record) (funcall (lambda (record) (let ((field_map (hydra_extract_helpers_to_field_map record))) (funcall (hydra_lib_eithers_bind (funcall (funcall (funcall (hydra_extract_helpers_require_field "name") hydra_decode_relational_column_name) field_map) cx)) (lambda (field_name) (funcall (hydra_lib_eithers_bind (funcall (funcall (funcall (hydra_extract_helpers_require_field "domain") t_) field_map) cx)) (lambda (field_domain) (list :right (make-hydra_relational_column_schema field_name field_domain)))))))) match_value)) (t (list :left "expected record")))) (cadr match_target))) stripped))) (funcall (hydra_lexical_strip_and_dereference_term_either cx) raw))))))

(defvar hydra_decode_relational_relation_name (lambda (cx) (lambda (raw) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :wrap) (funcall (lambda (wrapped_term) (funcall (hydra_lib_eithers_map (lambda (b) b)) (funcall (funcall (lambda (cx2) (lambda (raw2) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped2) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :literal) (funcall (lambda (v) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :string) (funcall (lambda (s) (list :right s)) match_value)) (t (list :left "expected string literal")))) (cadr match_target))) v)) match_value)) (t (list :left "expected literal")))) (cadr match_target))) stripped2))) (funcall (hydra_lexical_strip_and_dereference_term_either cx2) raw2)))) cx) (funcall (lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) (funcall (hydra_lexical_strip_and_dereference_term_either cx) raw)))))

(defvar hydra_decode_relational_foreign_key (lambda (cx) (lambda (raw) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :record) (funcall (lambda (record) (let ((field_map (hydra_extract_helpers_to_field_map record))) (funcall (hydra_lib_eithers_bind (funcall (funcall (funcall (hydra_extract_helpers_require_field "foreignRelation") hydra_decode_relational_relation_name) field_map) cx)) (lambda (field_foreign_relation) (funcall (hydra_lib_eithers_bind (funcall (funcall (funcall (hydra_extract_helpers_require_field "keys") (funcall (hydra_extract_helpers_decode_map hydra_decode_relational_column_name) hydra_decode_relational_column_name)) field_map) cx)) (lambda (field_keys) (list :right (make-hydra_relational_foreign_key field_foreign_relation field_keys)))))))) match_value)) (t (list :left "expected record")))) (cadr match_target))) stripped))) (funcall (hydra_lexical_strip_and_dereference_term_either cx) raw)))))

(defvar hydra_decode_relational_primary_key (lambda (cx) (lambda (raw) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :wrap) (funcall (lambda (wrapped_term) (funcall (hydra_lib_eithers_map (lambda (b) b)) (funcall (funcall (hydra_extract_helpers_decode_list hydra_decode_relational_column_name) cx) (funcall (lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) (funcall (hydra_lexical_strip_and_dereference_term_either cx) raw)))))

(defvar hydra_decode_relational_row (lambda (v) (lambda (cx) (lambda (raw) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :wrap) (funcall (lambda (wrapped_term) (funcall (hydra_lib_eithers_map (lambda (b) b)) (funcall (funcall (hydra_extract_helpers_decode_list v) cx) (funcall (lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) (funcall (hydra_lexical_strip_and_dereference_term_either cx) raw))))))

(defvar hydra_decode_relational_relation (lambda (v) (lambda (cx) (lambda (raw) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :wrap) (funcall (lambda (wrapped_term) (funcall (hydra_lib_eithers_map (lambda (b) b)) (funcall (funcall (hydra_extract_helpers_decode_list (hydra_decode_relational_row v)) cx) (funcall (lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) (funcall (hydra_lexical_strip_and_dereference_term_either cx) raw))))))

(defvar hydra_decode_relational_relation_schema (lambda (t_) (lambda (cx) (lambda (raw) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :record) (funcall (lambda (record) (let ((field_map (hydra_extract_helpers_to_field_map record))) (funcall (hydra_lib_eithers_bind (funcall (funcall (funcall (hydra_extract_helpers_require_field "name") hydra_decode_relational_relation_name) field_map) cx)) (lambda (field_name) (funcall (hydra_lib_eithers_bind (funcall (funcall (funcall (hydra_extract_helpers_require_field "columns") (hydra_extract_helpers_decode_list (hydra_decode_relational_column_schema t_))) field_map) cx)) (lambda (field_columns) (funcall (hydra_lib_eithers_bind (funcall (funcall (funcall (hydra_extract_helpers_require_field "primaryKeys") (hydra_extract_helpers_decode_list hydra_decode_relational_primary_key)) field_map) cx)) (lambda (field_primary_keys) (funcall (hydra_lib_eithers_bind (funcall (funcall (funcall (hydra_extract_helpers_require_field "foreignKeys") (hydra_extract_helpers_decode_list hydra_decode_relational_foreign_key)) field_map) cx)) (lambda (field_foreign_keys) (list :right (make-hydra_relational_relation_schema field_name field_columns field_primary_keys field_foreign_keys)))))))))))) match_value)) (t (list :left "expected record")))) (cadr match_target))) stripped))) (funcall (hydra_lexical_strip_and_dereference_term_either cx) raw))))))

(defvar hydra_decode_relational_relationship (lambda (v) (lambda (cx) (lambda (raw) (funcall (funcall (hydra_lib_eithers_either (lambda (err) (list :left err))) (lambda (stripped) (funcall (lambda (match_target) (funcall (lambda (match_value) (cond ((equal (car match_target) :wrap) (funcall (lambda (wrapped_term) (funcall (hydra_lib_eithers_map (lambda (b) b)) (funcall (funcall (hydra_extract_helpers_decode_set (funcall (hydra_extract_helpers_decode_map hydra_decode_relational_column_name) v)) cx) (funcall (lambda (v) (hydra_core_wrapped_term-body v)) wrapped_term)))) match_value)) (t (list :left "expected wrapped type")))) (cadr match_target))) stripped))) (funcall (hydra_lexical_strip_and_dereference_term_either cx) raw))))))

(provide 'hydra.decode.relational)
