(ns hydra.decode.util
  (:require [hydra.core :refer :all] [hydra.errors :refer :all] [hydra.extract.core :refer :all] [hydra.lib.eithers :refer :all] [hydra.lib.maps :refer :all] [hydra.lib.maybes :refer :all] [hydra.lib.strings :refer :all] [hydra.util :refer :all]
))

(declare hydra_decode_util_case_convention hydra_decode_util_comparison hydra_decode_util_precision)

(def hydra_decode_util_case_convention (fn [cx] (fn [raw] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :union) ((fn [inj] (let [field ((fn [v] (:field v)) inj) fname ((fn [v] (:name v)) field) fterm ((fn [v] (:term v)) field) variant_map (hydra_lib_maps_from_list (list (list "camel" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :camel t_))) (((fn [cx2] (fn [t_] ((hydra_extract_core_decode_unit cx2) t_))) cx) input)))) (list "pascal" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :pascal t_))) (((fn [cx2] (fn [t_] ((hydra_extract_core_decode_unit cx2) t_))) cx) input)))) (list "lowerSnake" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :lower_snake t_))) (((fn [cx2] (fn [t_] ((hydra_extract_core_decode_unit cx2) t_))) cx) input)))) (list "upperSnake" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :upper_snake t_))) (((fn [cx2] (fn [t_] ((hydra_extract_core_decode_unit cx2) t_))) cx) input))))))] (((hydra_lib_maybes_maybe (fn [] (list :left (hydra_lib_strings_cat (list "no such field " ((fn [v] v) fname) " in union"))))) (fn [f] (f fterm))) ((hydra_lib_maps_lookup fname) variant_map)))) match_value) :else (list :left "expected union"))) (second match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw)))))

(def hydra_decode_util_comparison (fn [cx] (fn [raw] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :union) ((fn [inj] (let [field ((fn [v] (:field v)) inj) fname ((fn [v] (:name v)) field) fterm ((fn [v] (:term v)) field) variant_map (hydra_lib_maps_from_list (list (list "lessThan" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :less_than t_))) (((fn [cx2] (fn [t_] ((hydra_extract_core_decode_unit cx2) t_))) cx) input)))) (list "equalTo" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :equal_to t_))) (((fn [cx2] (fn [t_] ((hydra_extract_core_decode_unit cx2) t_))) cx) input)))) (list "greaterThan" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :greater_than t_))) (((fn [cx2] (fn [t_] ((hydra_extract_core_decode_unit cx2) t_))) cx) input))))))] (((hydra_lib_maybes_maybe (fn [] (list :left (hydra_lib_strings_cat (list "no such field " ((fn [v] v) fname) " in union"))))) (fn [f] (f fterm))) ((hydra_lib_maps_lookup fname) variant_map)))) match_value) :else (list :left "expected union"))) (second match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw)))))

(def hydra_decode_util_precision (fn [cx] (fn [raw] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :union) ((fn [inj] (let [field ((fn [v] (:field v)) inj) fname ((fn [v] (:name v)) field) fterm ((fn [v] (:term v)) field) variant_map (hydra_lib_maps_from_list (list (list "arbitrary" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :arbitrary t_))) (((fn [cx2] (fn [t_] ((hydra_extract_core_decode_unit cx2) t_))) cx) input)))) (list "bits" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :bits t_))) (((fn [cx2] (fn [raw2] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped2] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :literal) ((fn [v] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :integer) ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :int32) ((fn [i] (list :right i)) match_value) :else (list :left "expected int32 value"))) (second match_target))) match_value) :else (list :left "expected int32 literal"))) (second match_target))) v)) match_value) :else (list :left "expected literal"))) (second match_target))) stripped2))) ((hydra_extract_core_strip_with_decoding_error cx2) raw2)))) cx) input))))))] (((hydra_lib_maybes_maybe (fn [] (list :left (hydra_lib_strings_cat (list "no such field " ((fn [v] v) fname) " in union"))))) (fn [f] (f fterm))) ((hydra_lib_maps_lookup fname) variant_map)))) match_value) :else (list :left "expected union"))) (second match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw)))))
