(ns hydra.ext.haskell.testing
  (:require [hydra.coders :refer :all] [hydra.constants :refer :all] [hydra.context :refer :all] [hydra.core :refer :all] [hydra.decode.core :refer :all] [hydra.dependencies :refer :all] [hydra.ext.haskell.syntax :refer :all] [hydra.ext.haskell.utils :refer :all] [hydra.formatting :refer :all] [hydra.lexical :refer :all] [hydra.lib.eithers :refer :all] [hydra.lib.equality :refer :all] [hydra.lib.lists :refer :all] [hydra.lib.literals :refer :all] [hydra.lib.logic :refer :all] [hydra.lib.maps :refer :all] [hydra.lib.math :refer :all] [hydra.lib.maybes :refer :all] [hydra.lib.pairs :refer :all] [hydra.lib.sets :refer :all] [hydra.lib.strings :refer :all] [hydra.module :refer :all] [hydra.names :refer :all] [hydra.predicates :refer :all] [hydra.rewriting :refer :all] [hydra.show.errors :refer :all] [hydra.strip :refer :all] [hydra.testing :refer :all] [hydra.util :refer :all]
))

(declare hydra_ext_haskell_testing_add_namespaces_to_namespaces hydra_ext_haskell_testing_collect_test_cases hydra_ext_haskell_testing_collect_names hydra_ext_haskell_testing_extract_encoded_term_variable_names hydra_ext_haskell_testing_extract_test_terms hydra_ext_haskell_testing_build_namespaces_for_test_group hydra_ext_haskell_testing_find_haskell_imports hydra_ext_haskell_testing_namespace_to_module_name hydra_ext_haskell_testing_build_test_module hydra_ext_haskell_testing_generate_test_case hydra_ext_haskell_testing_generate_test_group_hierarchy hydra_ext_haskell_testing_generate_test_file hydra_ext_haskell_testing_generate_haskell_test_file)

(def hydra_ext_haskell_testing_add_namespaces_to_namespaces (fn [ns0] (fn [names] (let [new_namespaces (hydra_lib_sets_from_list (hydra_lib_maybes_cat ((hydra_lib_lists_map hydra_names_namespace_of) (hydra_lib_sets_to_list names)))) to_module_name (fn [namespace] (hydra_formatting_capitalize (hydra_lib_lists_last ((hydra_lib_strings_split_on ".") ((fn [v] v) namespace))))) new_mappings (hydra_lib_maps_from_list ((hydra_lib_lists_map (fn [ns_] (list ns_ (to_module_name ns_)))) (hydra_lib_sets_to_list new_namespaces)))] (->hydra_module_namespaces ((fn [v] (:focus v)) ns0) ((hydra_lib_maps_union ((fn [v] (:mapping v)) ns0)) new_mappings))))))

(def hydra_ext_haskell_testing_collect_test_cases (fn [tg] ((hydra_lib_lists_concat2 ((fn [v] (:cases v)) tg)) (hydra_lib_lists_concat ((hydra_lib_lists_map hydra_ext_haskell_testing_collect_test_cases) ((fn [v] (:subgroups v)) tg))))))

(def hydra_ext_haskell_testing_collect_names (fn [graf] (fn [names] (fn [t_] (if (hydra_predicates_is_encoded_term (hydra_strip_deannotate_term t_)) (((hydra_lib_eithers_either (fn [_] names)) (fn [decoded_term] ((hydra_lib_sets_union names) ((((hydra_dependencies_term_dependency_names true) true) true) decoded_term)))) (((hydra_lib_eithers_bimap (fn [_e] _e)) (fn [_a] _a)) ((hydra_decode_core_term graf) t_))) names)))))

(def hydra_ext_haskell_testing_extract_encoded_term_variable_names (fn [graf] (fn [term] ((((hydra_rewriting_fold_over_term (list :pre nil)) (hydra_ext_haskell_testing_collect_names graf)) hydra_lib_sets_empty) term))))

(def hydra_ext_haskell_testing_extract_test_terms (fn [tcm] (list)))

(def hydra_ext_haskell_testing_build_namespaces_for_test_group (fn [mod] (fn [tgroup] (fn [graph_] (let [test_cases_ (hydra_ext_haskell_testing_collect_test_cases tgroup) test_terms (hydra_lib_lists_concat ((hydra_lib_lists_map hydra_ext_haskell_testing_extract_test_terms) test_cases_)) test_bindings ((hydra_lib_lists_map (fn [term] (->hydra_core_binding "_test_" term (list :nothing)))) test_terms) temp_module (->hydra_module_module ((fn [v] (:namespace v)) mod) ((hydra_lib_lists_map (fn [b] (list :term (->hydra_module_term_definition ((fn [v] (:name v)) b) ((fn [v] (:term v)) b) ((fn [v] (:type v)) b))))) test_bindings) ((fn [v] (:term_dependencies v)) mod) ((fn [v] (:type_dependencies v)) mod) ((fn [v] (:description v)) mod))] ((hydra_lib_eithers_bind (((hydra_lib_eithers_bimap (fn [ic] (hydra_show_errors_error ((fn [v] (:object v)) ic)))) (fn [a] a)) (((hydra_ext_haskell_utils_namespaces_for_module temp_module) hydra_lexical_empty_context) graph_))) (fn [base_namespaces] (let [encoded_names (hydra_lib_sets_unions ((hydra_lib_lists_map (fn [t_] ((hydra_ext_haskell_testing_extract_encoded_term_variable_names graph_) t_))) test_terms))] (list :right ((hydra_ext_haskell_testing_add_namespaces_to_namespaces base_namespaces) encoded_names))))))))))

(def hydra_ext_haskell_testing_find_haskell_imports (fn [namespaces] (fn [names_] (let [mapping_ ((fn [v] (:mapping v)) namespaces) filtered ((hydra_lib_maps_filter_with_key (fn [ns_] (fn [_v] (hydra_lib_logic_not ((hydra_lib_equality_equal (hydra_lib_lists_head ((hydra_lib_strings_split_on "hydra.test.") ((fn [v] v) ns_)))) ""))))) mapping_)] ((hydra_lib_lists_map (fn [entry] (hydra_lib_strings_cat (list "import qualified " ((hydra_lib_strings_intercalate ".") ((hydra_lib_lists_map hydra_formatting_capitalize) ((hydra_lib_strings_split_on ".") ((fn [v] v) (hydra_lib_pairs_first entry))))) " as " ((fn [v] v) (hydra_lib_pairs_second entry)))))) (hydra_lib_maps_to_list filtered))))))

(def hydra_ext_haskell_testing_namespace_to_module_name (fn [ns_] ((hydra_lib_strings_intercalate ".") ((hydra_lib_lists_map hydra_formatting_capitalize) ((hydra_lib_strings_split_on ".") ((fn [v] v) ns_))))))

(def hydra_ext_haskell_testing_build_test_module (fn [test_module] (fn [test_group] (fn [test_body] (fn [namespaces] (let [domain_imports ((hydra_ext_haskell_testing_find_haskell_imports namespaces) hydra_lib_sets_empty) standard_imports (list "import Hydra.Kernel" "import qualified Test.Hspec as H" "import qualified Data.List as L" "import qualified Data.Map as M" "import qualified Data.Set as S" "import qualified Data.Maybe as Y") all_imports ((hydra_lib_lists_concat2 standard_imports) domain_imports) group_name_ ((fn [v] (:name v)) test_group) ns_ ((fn [v] (:namespace v)) test_module) spec_ns ((hydra_lib_strings_cat2 ((fn [v] v) ns_)) "Spec") module_name_string (hydra_ext_haskell_testing_namespace_to_module_name spec_ns) header ((hydra_lib_strings_intercalate "\n") (hydra_lib_lists_concat (list (list ((hydra_lib_strings_cat2 "-- ") hydra_constants_warning_auto_generated_file) "") (list "" (hydra_lib_strings_cat (list "module " module_name_string " where")) "") all_imports (list "" "spec :: H.Spec" (hydra_lib_strings_cat (list "spec = H.describe " (hydra_lib_literals_show_string group_name_) " $ do"))))))] (hydra_lib_strings_cat (list header "\n" test_body "\n"))))))))

(def hydra_ext_haskell_testing_generate_test_case (fn [depth] (fn [tcm] (let [tcase ((fn [v] (:case v)) tcm) universal ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :universal) ((fn [u] u) match_value))) (second match_target))) tcase) actual_ ((fn [v] (:actual v)) universal) expected_ ((fn [v] (:expected v)) universal) name_ ((fn [v] (:name v)) tcm)] (list :right (list (hydra_lib_strings_cat (list "H.it " (hydra_lib_literals_show_string name_) " $ H.shouldBe")) (hydra_lib_strings_cat (list "  (" actual_ ")")) (hydra_lib_strings_cat (list "  (" expected_ ")"))))))))

(def hydra_ext_haskell_testing_generate_test_group_hierarchy (fn [depth] (fn [test_group] (let [cases_ ((fn [v] (:cases v)) test_group) indent (hydra_lib_strings_from_list ((hydra_lib_lists_replicate ((hydra_lib_math_mul depth) 2)) 32)) subgroups ((fn [v] (:subgroups v)) test_group)] ((hydra_lib_eithers_bind ((hydra_lib_eithers_map_list (fn [tc] ((hydra_ext_haskell_testing_generate_test_case depth) tc))) cases_)) (fn [test_case_lines_raw] (let [test_case_lines ((hydra_lib_lists_map (fn [lines_] ((hydra_lib_lists_map (fn [line] ((hydra_lib_strings_cat2 indent) line))) lines_))) test_case_lines_raw) test_cases_str ((hydra_lib_strings_intercalate "\n") (hydra_lib_lists_concat test_case_lines))] ((hydra_lib_eithers_map (fn [subgroups_str] (hydra_lib_strings_cat (list test_cases_str (if ((hydra_lib_logic_or ((hydra_lib_equality_equal test_cases_str) "")) ((hydra_lib_equality_equal subgroups_str) "")) "" "\n") subgroups_str)))) ((hydra_lib_eithers_map (fn [blocks] ((hydra_lib_strings_intercalate "\n") blocks))) ((hydra_lib_eithers_map_list (fn [subgroup] (let [group_name_ ((fn [v] (:name v)) subgroup)] ((hydra_lib_eithers_map (fn [content] (hydra_lib_strings_cat (list indent "H.describe " (hydra_lib_literals_show_string group_name_) " $ do\n" content)))) ((hydra_ext_haskell_testing_generate_test_group_hierarchy ((hydra_lib_math_add depth) 1)) subgroup))))) subgroups))))))))))

(def hydra_ext_haskell_testing_generate_test_file (fn [test_module] (fn [test_group] (fn [namespaces] ((hydra_lib_eithers_map (fn [test_body] (let [ns_ ((fn [v] (:namespace v)) test_module) spec_ns ((hydra_lib_strings_cat2 ((fn [v] v) ns_)) "Spec") file_path (((hydra_names_namespace_to_file_path (list :pascal nil)) "hs") spec_ns) test_module_content ((((hydra_ext_haskell_testing_build_test_module test_module) test_group) test_body) namespaces)] (list file_path test_module_content)))) ((hydra_ext_haskell_testing_generate_test_group_hierarchy 1) test_group))))))

(def hydra_ext_haskell_testing_generate_haskell_test_file (fn [test_module] (fn [test_group] (fn [g] ((hydra_lib_eithers_bind (((hydra_ext_haskell_testing_build_namespaces_for_test_group test_module) test_group) g)) (fn [namespaces] (((hydra_ext_haskell_testing_generate_test_file test_module) test_group) namespaces)))))))
