// Note: this is an automatically generated file. Do not edit.

package hydra.constants;

/**
 * A module for tier-0 constants.
 */
public interface Constants {
  static Boolean debugInference() {
    return true;
  }
  
  static String ignoredVariable() {
    return "_";
  }
  
  static hydra.core.Name key_classes() {
    return new hydra.core.Name("classes");
  }
  
  static hydra.core.Name key_debugId() {
    return new hydra.core.Name("debugId");
  }
  
  static hydra.core.Name key_deprecated() {
    return new hydra.core.Name("deprecated");
  }
  
  static hydra.core.Name key_description() {
    return new hydra.core.Name("description");
  }
  
  static hydra.core.Name key_exclude() {
    return new hydra.core.Name("exclude");
  }
  
  static hydra.core.Name key_firstClassType() {
    return new hydra.core.Name("firstClassType");
  }
  
  static hydra.core.Name key_maxLength() {
    return new hydra.core.Name("maxLength");
  }
  
  static hydra.core.Name key_minLength() {
    return new hydra.core.Name("minLength");
  }
  
  static hydra.core.Name key_preserveFieldName() {
    return new hydra.core.Name("preserveFieldName");
  }
  
  static hydra.core.Name key_type() {
    return new hydra.core.Name("type");
  }
  
  static hydra.core.Name key_freshTypeVariableCount() {
    return new hydra.core.Name("freshTypeVariableCount");
  }
  
  static Integer maxInt32() {
    return 2147483647;
  }
  
  static hydra.core.Name placeholderName() {
    return new hydra.core.Name("Placeholder");
  }
  
  static Integer maxTraceDepth() {
    return 4000;
  }
  
  static String warningAutoGeneratedFile() {
    return "Note: this is an automatically generated file. Do not edit.";
  }
}
