// Note: this is an automatically generated file. Do not edit.

package hydra.constants;

/**
 * A module for tier-0 constants.
 */
public interface Constants {
  Boolean debugInference = true;
  
  String ignoredVariable = "_";
  
  hydra.core.Name key_classes = new hydra.core.Name("classes");
  
  hydra.core.Name key_debugId = new hydra.core.Name("debugId");
  
  hydra.core.Name key_deprecated = new hydra.core.Name("deprecated");
  
  hydra.core.Name key_description = new hydra.core.Name("description");
  
  hydra.core.Name key_exclude = new hydra.core.Name("exclude");
  
  hydra.core.Name key_firstClassType = new hydra.core.Name("firstClassType");
  
  hydra.core.Name key_maxLength = new hydra.core.Name("maxLength");
  
  hydra.core.Name key_minLength = new hydra.core.Name("minLength");
  
  hydra.core.Name key_preserveFieldName = new hydra.core.Name("preserveFieldName");
  
  hydra.core.Name key_type = new hydra.core.Name("type");
  
  hydra.core.Name key_freshTypeVariableCount = new hydra.core.Name("freshTypeVariableCount");
  
  Integer maxInt32 = 2147483647;
  
  hydra.core.Name placeholderName = new hydra.core.Name("Placeholder");
  
  Integer maxTraceDepth = 4000;
  
  String warningAutoGeneratedFile = "Note: this is an automatically generated file. Do not edit.";
}
