// Note: this is an automatically generated file. Do not edit.

package hydra.test.json.coder;

/**
 * Test cases for the type-directed JSON coder (Hydra Term &lt;-&gt; JSON Value)
 */
public interface Coder {
  static hydra.testing.TestGroup allTests() {
    return new hydra.testing.TestGroup("JSON coder", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), java.util.List.of(
      new hydra.testing.TestGroup("literal types", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("boolean true", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.Boolean_()), new hydra.core.Term.Literal(new hydra.core.Literal.Boolean_(true)), new hydra.json.model.Value.Boolean_(true))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("boolean false", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.Boolean_()), new hydra.core.Term.Literal(new hydra.core.Literal.Boolean_(false)), new hydra.json.model.Value.Boolean_(false))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("int32 positive", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.Integer_(new hydra.core.IntegerType.Int32())), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(42))), new hydra.json.model.Value.Number_(new java.math.BigDecimal("42.0")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("int32 negative", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.Integer_(new hydra.core.IntegerType.Int32())), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(-17))), new hydra.json.model.Value.Number_(new java.math.BigDecimal("-17.0")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("int32 zero", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.Integer_(new hydra.core.IntegerType.Int32())), new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(0))), new hydra.json.model.Value.Number_(new java.math.BigDecimal("0.0")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("float32", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.Float_(new hydra.core.FloatType.Float32())), new hydra.core.Term.Literal(new hydra.core.Literal.Float_(new hydra.core.FloatValue.Float32((float) (1.5)))), new hydra.json.model.Value.Number_(new java.math.BigDecimal("1.5")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("float64", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.Float_(new hydra.core.FloatType.Float64())), new hydra.core.Term.Literal(new hydra.core.Literal.Float_(new hydra.core.FloatValue.Float64(2.718))), new hydra.json.model.Value.Number_(new java.math.BigDecimal("2.718")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("string simple", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.String_()), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")), new hydra.json.model.Value.String_("hello"))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("string empty", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.String_()), new hydra.core.Term.Literal(new hydra.core.Literal.String_("")), new hydra.json.model.Value.String_(""))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("string with spaces", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Literal(new hydra.core.LiteralType.String_()), new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello world")), new hydra.json.model.Value.String_("hello world"))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("collection types", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("list of integers", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.List(new hydra.core.Type.Literal(new hydra.core.LiteralType.Integer_(new hydra.core.IntegerType.Int32()))), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(1))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(2))),
          new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(3))))), new hydra.json.model.Value.Array(java.util.List.of(
          new hydra.json.model.Value.Number_(new java.math.BigDecimal("1.0")),
          new hydra.json.model.Value.Number_(new java.math.BigDecimal("2.0")),
          new hydra.json.model.Value.Number_(new java.math.BigDecimal("3.0")))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("list of strings", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.List(new hydra.core.Type.Literal(new hydra.core.LiteralType.String_())), new hydra.core.Term.List(java.util.List.of(
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("a")),
          new hydra.core.Term.Literal(new hydra.core.Literal.String_("b")))), new hydra.json.model.Value.Array(java.util.List.of(
          new hydra.json.model.Value.String_("a"),
          new hydra.json.model.Value.String_("b"))))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("empty list", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.List(new hydra.core.Type.Literal(new hydra.core.LiteralType.Integer_(new hydra.core.IntegerType.Int32()))), new hydra.core.Term.List((java.util.List<hydra.core.Term>) (java.util.List.<hydra.core.Term>of())), new hydra.json.model.Value.Array((java.util.List<hydra.json.model.Value>) (java.util.List.<hydra.json.model.Value>of())))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("optional types", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), java.util.List.of(
        new hydra.testing.TestCaseWithMetadata("optional string with value", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Maybe(new hydra.core.Type.Literal(new hydra.core.LiteralType.String_())), new hydra.core.Term.Maybe(hydra.util.Maybe.just(new hydra.core.Term.Literal(new hydra.core.Literal.String_("hello")))), new hydra.json.model.Value.String_("hello"))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("optional string nothing", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Maybe(new hydra.core.Type.Literal(new hydra.core.LiteralType.String_())), new hydra.core.Term.Maybe((hydra.util.Maybe<hydra.core.Term>) (hydra.util.Maybe.<hydra.core.Term>nothing())), new hydra.json.model.Value.Null())), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("optional int with value", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Maybe(new hydra.core.Type.Literal(new hydra.core.LiteralType.Integer_(new hydra.core.IntegerType.Int32()))), new hydra.core.Term.Maybe(hydra.util.Maybe.just(new hydra.core.Term.Literal(new hydra.core.Literal.Integer_(new hydra.core.IntegerValue.Int32(42))))), new hydra.json.model.Value.Number_(new java.math.BigDecimal("42.0")))), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())),
        new hydra.testing.TestCaseWithMetadata("optional int nothing", new hydra.testing.TestCase.JsonCoder(new hydra.testing.JsonCoderTestCase(new hydra.core.Type.Maybe(new hydra.core.Type.Literal(new hydra.core.LiteralType.Integer_(new hydra.core.IntegerType.Int32()))), new hydra.core.Term.Maybe((hydra.util.Maybe<hydra.core.Term>) (hydra.util.Maybe.<hydra.core.Term>nothing())), new hydra.json.model.Value.Null())), (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.Tag>) (java.util.List.<hydra.testing.Tag>of())))),
      new hydra.testing.TestGroup("record types", (hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing()), (java.util.List<hydra.testing.TestGroup>) (java.util.List.<hydra.testing.TestGroup>of()), (java.util.List<hydra.testing.TestCaseWithMetadata>) (java.util.List.<hydra.testing.TestCaseWithMetadata>of()))), (java.util.List<hydra.testing.TestCaseWithMetadata>) (java.util.List.<hydra.testing.TestCaseWithMetadata>of()));
  }
}
