name:         hydra
version:      0.1.0
maintainer:   Joshua Shinavier <josh@fortytwo.net>
license:      Apache-2.0
license-file: LICENSE
category:     Data
synopsis:     Type-aware transformations for data and functional programs
description:  >
  Hydra is a transformation toolkit along the lines of Dragon (Uber), but open source,
  and with a more advanced type system and other new features.
  Hydra maps data and schemas between languages in a way which maintains type conformance.
  It will even map functional programs between selected languages, including parts of its own source code.
github:       CategoricalData/hydra

extra-source-files:
  - LICENSE
  - README.md
  - stack.yaml

dependencies:
  - aeson == 1.5.6.0
  - aeson-pretty == 0.8.8
  - base == 4.14.3.0
  - bytestring == 0.10.12.0
  - containers == 0.6.5.1
  - directory == 1.3.6.0
  - filepath == 1.4.2.1
  - HsYAML == 0.2.1.0
  - scientific == 0.3.7.0
  - split == 0.2.3.4
  - text == 1.2.4.1
  - unordered-containers == 0.2.14.0
  - vector == 0.12.3.0

library:
  source-dirs:
    - src/main/haskell
    - src/gen-main/haskell

tests:
  hydra-test:
    main: Spec.hs
    source-dirs: src/test/haskell
    dependencies:
      - hydra
      - hspec
      - hspec-discover
      - HUnit
      - QuickCheck
