name:         hydra
version:      0.1.0
maintainer:   josh@fortytwo.net
license:      Apache-2.0
license-file: LICENSE
category:     Data
synopsis:     An experimental framework for data integration
github:       CategoricalData/hydra
description:  A type-safe data transformation toolkit

extra-source-files:
  - LICENSE
  - README.md
  - stack.yaml

dependencies:
  - base < 4.15
  - containers

  # Hydra.Impl.Haskell dependencies
  - aeson
  - aeson-pretty
  - bytestring
  - directory
  - filepath
  - HsYAML
  - scientific
  - split
  - text
  - unordered-containers
  - vector

library:
  source-dirs:
    - src/main/haskell
    - src/gen-main/haskell
#  exposed-modules:

tests:
  hydra-test:
    main: Spec.hs
    source-dirs: src/test/haskell
    dependencies:
      - hydra
      - hspec
      - hspec-discover
      - HUnit
      - QuickCheck
