name:         hydra
version:      0.1.0
maintainer:   Joshua Shinavier <josh@fortytwo.net>
license:      Apache-2.0
license-file: LICENSE
category:     Data
synopsis:     Type-aware transformations for data and functional programs
description:  >
  Hydra is a transformation toolkit along the lines of Dragon (Uber), but open source,
  and with a more advanced type system and other new features.
  Hydra maps data and schemas between languages in a way which maintains type conformance.
  It will even map functional programs between selected languages, including parts of its own source code.
github:       CategoricalData/hydra

extra-source-files:
  - LICENSE
  - README.md
  - stack.yaml

dependencies:
  - base < 4.15
  - containers

  # Hydra.Impl.Haskell dependencies
  - aeson
  - aeson-pretty
  - bytestring
  - directory
  - filepath
  - HsYAML
  - scientific
  - split
  - text
  - unordered-containers
  - vector

library:
  source-dirs:
    - src/main/haskell
    - src/gen-main/haskell
#  exposed-modules:

tests:
  hydra-test:
    main: Spec.hs
    source-dirs: src/test/haskell
    dependencies:
      - hydra
      - hspec
      - hspec-discover
      - HUnit
      - QuickCheck
