name:         hydra
version:      0.12.0
author:       Joshua Shinavier <josh@fortytwo.net>
license:      Apache-2.0
license-file: LICENSE
category:     Data
synopsis:     Graph programming language
description:  >
  Hydra is an implementation of the LambdaGraph data model, which takes advantage of an isomorphism
  between labeled hypergraphs and typed lambda calculus:
  in Hydra, "graphs are programs, and programs are graphs".
  The language is designed to be embedded in other programming languages, transforming data, schemas,
  and functional programs into multiple other languages in a way which maintains type safety,
  Hydra is self-hosting in Haskell, i.e. it generates its own executable source code from Hydra sources.
github:       CategoricalData/hydra

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - stack.yaml

dependencies:
  - HsYAML                        >= 0.2.1 && < 0.3
  - aeson                         >= 2.2.0 && < 2.3
  - aeson-pretty                  >= 0.8.9 && < 0.9
  - base                          >= 4.20.0 && < 4.21
  - bytestring                    >= 0.12.0 && < 0.13
  - containers                    >= 0.7 && < 0.8
  - directory                     >= 1.3.6 && < 1.4
  - filepath                      >= 1.5.0 && < 1.6
  - scientific                    >= 0.3.7 && < 0.4
  - split                         >= 0.2.3 && < 0.3
  - text                          >= 2.1.0 && < 2.2
  - vector                        >= 0.12.0 && < 0.14

library:
  source-dirs:
    - src/main/haskell
    - src/gen-main/haskell

tests:
  hydra-test:
    main: Spec.hs
    source-dirs:
      - src/test/haskell
      - src/gen-test/haskell
    dependencies:
      - hydra
      - hspec
      - hspec-discover
      - HUnit
      - QuickCheck
      - mtl # For the Algorithm W reference implementation
