name:       hydra
version:    0.1.0
maintainer: josh@fortytwo.net
license:    Apache-2.0
category:   Data
synopsis:   An experimental framework for data integration
github:     CategoricalData/hydra

extra-source-files:
  - ../LICENSE  # TODO: need separate LICENSE and README in this directory
  - ../README.md
  - stack.yaml

dependencies:
  - base
  - containers

  # ext dependencies
  - HsYAML
  - bytestring
  - text

  # temporary
  - mtl

library:
  source-dirs:
    - src/main/haskell
    - src/gen-main/haskell
#  exposed-modules:

tests:
  hydra-test:
    main: Spec.hs
    source-dirs: src/test/haskell
    dependencies:
      - hydra
      - hspec
      - hspec-discover
      - HUnit
      - QuickCheck
