(ns hydra.decode.parsing
  (:require [hydra.core :refer :all] [hydra.errors :refer :all] [hydra.extract.core :refer :all] [hydra.lib.eithers :refer :all] [hydra.lib.maps :refer :all] [hydra.lib.maybes :refer :all] [hydra.lib.strings :refer :all] [hydra.parsing :refer :all]
))

(declare hydra_decode_parsing_parse_error hydra_decode_parsing_parse_success hydra_decode_parsing_parse_result)

(def hydra_decode_parsing_parse_error (fn [cx] (fn [raw] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :record) ((fn [record] (let [field_map (hydra_extract_core_to_field_map record)] ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "message") (fn [cx2] (fn [raw2] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped2] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :literal) ((fn [v] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :string) ((fn [s] (list :right s)) match_value) :else (list :left "expected string literal"))) (second match_target))) v)) match_value) :else (list :left "expected literal"))) (second match_target))) stripped2))) ((hydra_extract_core_strip_with_decoding_error cx2) raw2))))) field_map) cx)) (fn [field_message] ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "remainder") (fn [cx2] (fn [raw2] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped2] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :literal) ((fn [v] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :string) ((fn [s] (list :right s)) match_value) :else (list :left "expected string literal"))) (second match_target))) v)) match_value) :else (list :left "expected literal"))) (second match_target))) stripped2))) ((hydra_extract_core_strip_with_decoding_error cx2) raw2))))) field_map) cx)) (fn [field_remainder] (list :right (->hydra_parsing_parse_error field_message field_remainder)))))))) match_value) :else (list :left "expected record"))) (second match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw)))))

(def hydra_decode_parsing_parse_success (fn [a] (fn [cx] (fn [raw] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :record) ((fn [record] (let [field_map (hydra_extract_core_to_field_map record)] ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "value") a) field_map) cx)) (fn [field_value] ((hydra_lib_eithers_bind ((((hydra_extract_core_require_field "remainder") (fn [cx2] (fn [raw2] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped2] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :literal) ((fn [v] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :string) ((fn [s] (list :right s)) match_value) :else (list :left "expected string literal"))) (second match_target))) v)) match_value) :else (list :left "expected literal"))) (second match_target))) stripped2))) ((hydra_extract_core_strip_with_decoding_error cx2) raw2))))) field_map) cx)) (fn [field_remainder] (list :right (->hydra_parsing_parse_success field_value field_remainder)))))))) match_value) :else (list :left "expected record"))) (second match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw))))))

(def hydra_decode_parsing_parse_result (fn [a] (fn [cx] (fn [raw] (((hydra_lib_eithers_either (fn [err] (list :left err))) (fn [stripped] ((fn [match_target] ((fn [match_value] (cond (= (first match_target) :union) ((fn [inj] (let [field ((fn [v] (:field v)) inj) fname ((fn [v] (:name v)) field) fterm ((fn [v] (:term v)) field) variant_map (hydra_lib_maps_from_list (list (list "success" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :success t_))) (((hydra_decode_parsing_parse_success a) cx) input)))) (list "failure" (fn [input] ((hydra_lib_eithers_map (fn [t_] (list :failure t_))) ((hydra_decode_parsing_parse_error cx) input))))))] (((hydra_lib_maybes_maybe (fn [] (list :left (hydra_lib_strings_cat (list "no such field " ((fn [v] v) fname) " in union"))))) (fn [f] (f fterm))) ((hydra_lib_maps_lookup fname) variant_map)))) match_value) :else (list :left "expected union"))) (second match_target))) stripped))) ((hydra_extract_core_strip_with_decoding_error cx) raw))))))
