"""TypedTerm references to kernel functions used by the Python DSL sources.

These mirror the Haskell pattern where Names.qualifyName, Formatting.convertCase,
etc. are TTermDefinitions/TermVariables. In Python we expose them as TypedTerm-valued
constants (var(...)) for use inside source-DSL code.

Keep this list minimal — only add what's actually used.
"""

from hydra.dsl.meta.phantoms import var


# hydra.constants
constants_warning_auto_generated_file = var("hydra.constants.warningAutoGeneratedFile")

# hydra.formatting
formatting_convert_case = var("hydra.formatting.convertCase")
formatting_capitalize = var("hydra.formatting.capitalize")
formatting_sanitize_with_underscores = var("hydra.formatting.sanitizeWithUnderscores")

# hydra.names
names_qualify_name = var("hydra.names.qualifyName")
names_module_name_of = var("hydra.names.moduleNameOf")

# hydra.python.utils (used by coder.py)
utils_assignment_statement = var("hydra.python.utils.assignmentStatement")
utils_double_quoted_string = var("hydra.python.utils.doubleQuotedString")
utils_find_namespaces = var("hydra.python.utils.findNamespaces")
utils_function_call = var("hydra.python.utils.functionCall")
utils_indented_block = var("hydra.python.utils.indentedBlock")
utils_primary_with_expression_slices = var("hydra.python.utils.primaryWithExpressionSlices")
utils_primary_with_rhs = var("hydra.python.utils.primaryWithRhs")
utils_project_from_expression = var("hydra.python.utils.projectFromExpression")
utils_py_atom_to_py_expression = var("hydra.python.utils.pyAtomToPyExpression")
utils_py_closed_pattern_to_py_patterns = var("hydra.python.utils.pyClosedPatternToPyPatterns")
utils_py_expression_to_py_primary = var("hydra.python.utils.pyExpressionToPyPrimary")
utils_py_expression_to_py_star_named_expression = var("hydra.python.utils.pyExpressionToPyStarNamedExpression")
utils_py_expressions_to_py_args = var("hydra.python.utils.pyExpressionsToPyArgs")
utils_py_name_to_py_expression = var("hydra.python.utils.pyNameToPyExpression")
utils_py_name_to_py_type_parameter = var("hydra.python.utils.pyNameToPyTypeParameter")
utils_py_primary_to_py_expression = var("hydra.python.utils.pyPrimaryToPyExpression")
utils_py_simple_statement_to_py_statement = var("hydra.python.utils.pySimpleStatementToPyStatement")
utils_string_to_py_expression = var("hydra.python.utils.stringToPyExpression")
utils_py_list = var("hydra.python.utils.pyList")
utils_py_name_to_py_primary = var("hydra.python.utils.pyNameToPyPrimary")
utils_single_quoted_string = var("hydra.python.utils.singleQuotedString")
utils_primary_and_params = var("hydra.python.utils.primaryAndParams")
utils_primary_with_slices = var("hydra.python.utils.primaryWithSlices")
utils_py_expression_to_py_slice = var("hydra.python.utils.pyExpressionToPySlice")
utils_py_primary_to_py_slice = var("hydra.python.utils.pyPrimaryToPySlice")
utils_py_list_helper = var("hydra.python.utils.pyList")  # alias
utils_target_python_version = var("hydra.python.utils.targetPythonVersion")
utils_annotated_expression = var("hydra.python.utils.annotatedExpression")
utils_py_assignment_to_py_statement = var("hydra.python.utils.pyAssignmentToPyStatement")
utils_py_class_definition_to_py_statement = var("hydra.python.utils.pyClassDefinitionToPyStatement")
utils_py_expression_to_py_statement = var("hydra.python.utils.pyExpressionToPyStatement")
utils_triple_quoted_string = var("hydra.python.utils.tripleQuotedString")
utils_unit_variant_methods = var("hydra.python.utils.unitVariantMethods")
utils_annotated_statement = var("hydra.python.utils.annotatedStatement")
utils_dotted_assignment_statement = var("hydra.python.utils.dottedAssignmentStatement")
utils_comment_statement = var("hydra.python.utils.commentStatement")
environment_reorder_defs = var("hydra.environment.reorderDefs")
utils_or_expression = var("hydra.python.utils.orExpression")
utils_py_expression_to_bitwise_or = var("hydra.python.utils.pyExpressionToBitwiseOr")
utils_py_expression_to_disjunction = var("hydra.python.utils.pyExpressionToDisjunction")
utils_raise_assertion_error = var("hydra.python.utils.raiseAssertionError")
utils_raise_type_error = var("hydra.python.utils.raiseTypeError")
utils_return_single = var("hydra.python.utils.returnSingle")
names_local_name_of = var("hydra.names.localNameOf")
utils_name_and_params = var("hydra.python.utils.nameAndParams")
utils_py_none = var("hydra.python.utils.pyNone")
show_core_type = var("hydra.show.core.type")
names_type_variable_reference = var("hydra.python.names.typeVariableReference")
predicates_is_enum_row_type = var("hydra.predicates.isEnumRowType")
predicates_is_unit_term = var("hydra.predicates.isUnitTerm")
predicates_is_complex_term = var("hydra.predicates.isComplexTerm")
predicates_is_complex_variable = var("hydra.predicates.isComplexVariable")
arity_type_scheme_arity = var("hydra.arity.typeSchemeArity")
arity_term_arity = var("hydra.arity.termArity")
resolution_require_union_type = var("hydra.resolution.requireUnionType")
errors_error_other = var("hydra.errors.errorOther")
errors_other_error = var("hydra.errors.otherError")
analysis_gather_args = var("hydra.analysis.gatherArgs")
lexical_lookup_binding = var("hydra.lexical.lookupBinding")
graph_graph_primitives = var("hydra.graph.graphPrimitives")
arity_primitive_arity = var("hydra.arity.primitiveArity")
arity_type_arity = var("hydra.arity.typeArity")
lexical_lookup_primitive = var("hydra.lexical.lookupPrimitive")
names_term_variable_reference = var("hydra.python.names.termVariableReference")
names_encode_name_qualified = var("hydra.python.names.encodeNameQualified")
names_encode_field_name_kr = var("hydra.python.names.encodeFieldName")  # already added
core_equal_name = var("hydra.core.equalName_")
variables_is_free_variable_in_term = var("hydra.variables.isFreeVariableInTerm")
rewriting_subtypes = var("hydra.rewriting.subtypes")
annotations_has_type_description = var("hydra.annotations.hasTypeDescription")
dependencies_type_dependency_names = var("hydra.dependencies.typeDependencyNames")
analysis_add_names_to_module_names = var("hydra.analysis.addNamesToModuleNames")
analysis_is_simple_assignment = var("hydra.analysis.isSimpleAssignment")
analysis_is_self_tail_recursive = var("hydra.analysis.isSelfTailRecursive")
rewriting_fold_over_term = var("hydra.rewriting.foldOverTerm")
rewriting_fold_over_type = var("hydra.rewriting.foldOverType")
coders_traversal_order_pre = var("hydra.coders.traversalOrderPre")

# hydra.annotations
annotations_get_type_description = var("hydra.annotations.getTypeDescription")
annotations_get_term_description = var("hydra.annotations.getTermDescription")
formatting_normalize_comment = var("hydra.formatting.normalizeComment")

utils_type_alias_statement = var("hydra.python.utils.typeAliasStatement")
utils_type_alias_statement310 = var("hydra.python.utils.typeAliasStatement310")
utils_union_type_class_statements310 = var("hydra.python.utils.unionTypeClassStatements310")

# hydra.python.names (used by coder.py)
names_encode_enum_value = var("hydra.python.names.encodeEnumValue")
names_encode_field_name = var("hydra.python.names.encodeFieldName")
names_encode_name = var("hydra.python.names.encodeName")
names_encode_namespace = var("hydra.python.names.encodeNamespace")
names_encode_type_variable = var("hydra.python.names.encodeTypeVariable")
names_use_future_annotations = var("hydra.python.names.useFutureAnnotations")
names_variant_name = var("hydra.python.names.variantName")
names_encode_constant_for_type_name = var("hydra.python.names.encodeConstantForTypeName")
names_encode_constant_for_field_name = var("hydra.python.names.encodeConstantForFieldName")

# hydra.predicates (used by coder.py)
predicates_is_complex_binding = var("hydra.predicates.isComplexBinding")
predicates_is_trivial_term = var("hydra.predicates.isTrivialTerm")
predicates_is_unit_type = var("hydra.predicates.isUnitType")

# hydra.analysis
analysis_analyze_function_term_with = var("hydra.analysis.analyzeFunctionTermWith")
analysis_gather_applications = var("hydra.analysis.gatherApplications")

# hydra.environment
environment_with_lambda_context = var("hydra.environment.withLambdaContext")
environment_with_let_context = var("hydra.environment.withLetContext")
environment_with_type_lambda_context = var("hydra.environment.withTypeLambdaContext")

# hydra.scoping / hydra.strip / hydra.variables
scoping_extend_graph_for_lambda = var("hydra.scoping.extendGraphForLambda")
scoping_term_signature_to_type_scheme = var("hydra.scoping.termSignatureToTypeScheme")
reduction_alpha_convert = var("hydra.reduction.alphaConvert")
strip_deannotate_type = var("hydra.strip.deannotateType")
strip_deannotate_and_detype_term = var("hydra.strip.deannotateAndDetypeTerm")
variables_free_variables_in_type = var("hydra.variables.freeVariablesInType")

# hydra.serialization (used by serde.py)
serialization_braces_list_adaptive = var("hydra.serialization.bracesListAdaptive")
serialization_bracket_list = var("hydra.serialization.bracketList")
serialization_bracket_list_adaptive = var("hydra.serialization.bracketListAdaptive")
serialization_comma_sep = var("hydra.serialization.commaSep")
serialization_comma_sep_adaptive = var("hydra.serialization.commaSepAdaptive")
serialization_cst = var("hydra.serialization.cst")
serialization_curly_braces_list = var("hydra.serialization.curlyBracesList")
serialization_dot_sep = var("hydra.serialization.dotSep")
serialization_double_newline_sep = var("hydra.serialization.doubleNewlineSep")
serialization_half_block_style = var("hydra.serialization.halfBlockStyle")
serialization_inline_style = var("hydra.serialization.inlineStyle")
serialization_newline_sep = var("hydra.serialization.newlineSep")
serialization_no_sep = var("hydra.serialization.noSep")
serialization_paren_list_adaptive = var("hydra.serialization.parenListAdaptive")
serialization_parens = var("hydra.serialization.parens")
serialization_semicolon_sep = var("hydra.serialization.semicolonSep")
serialization_space_sep = var("hydra.serialization.spaceSep")
serialization_symbol_sep = var("hydra.serialization.symbolSep")
serialization_tab_indent_double_space = var("hydra.serialization.tabIndentDoubleSpace")

# hydra.packaging — these are DSL accessors (generated), not kernel functions.
# Re-export from hydra.dsl.packaging for symmetry with the Haskell DSL imports.
# namespaces_focus moved to hydra.dsl.util in #369 (Namespaces<n> lives in hydra.util).
from hydra.dsl.packaging import (
    qualified_name_local as packaging_qualified_name_local,
    qualified_name_module_name as packaging_qualified_name_namespace,
    un_module_name as packaging_un_module_name,
)
from hydra.dsl.util import (
    module_names_focus as packaging_namespaces_focus,
)

# hydra.util — namespaces_focus moved from hydra.packaging to hydra.util (#369 A2).
from hydra.dsl.util import (
    module_names_focus as packaging_namespaces_focus,
)

# hydra.util CaseConvention enum constants are TTerms (injects), already
# available as constants in hydra.dsl.util. Re-export here for symmetry.
from hydra.dsl.util import (
    case_convention_camel as util_case_convention_camel,
    case_convention_lower_snake as util_case_convention_lower_snake,
    case_convention_upper_snake as util_case_convention_upper_snake,
    case_convention_pascal as util_case_convention_pascal,
)
