"""TTerm references to kernel functions used by the Python DSL sources.

These mirror the Haskell pattern where Names.qualifyName, Formatting.convertCase,
etc. are TTermDefinitions/TermVariables. In Python we expose them as TTerm-valued
constants (Phantoms.var(...)) for use inside source-DSL code.

Keep this list minimal — only add what's actually used.
"""

import hydra.dsl.meta.phantoms as _P


# hydra.constants
constants_warning_auto_generated_file = _P.var("hydra.constants.warningAutoGeneratedFile")

# hydra.formatting
formatting_convert_case = _P.var("hydra.formatting.convertCase")
formatting_capitalize = _P.var("hydra.formatting.capitalize")
formatting_sanitize_with_underscores = _P.var("hydra.formatting.sanitizeWithUnderscores")

# hydra.names
names_qualify_name = _P.var("hydra.names.qualifyName")
names_namespace_of = _P.var("hydra.names.namespaceOf")

# hydra.python.utils (used by coder.py)
utils_assignment_statement = _P.var("hydra.python.utils.assignmentStatement")
utils_double_quoted_string = _P.var("hydra.python.utils.doubleQuotedString")
utils_find_namespaces = _P.var("hydra.python.utils.findNamespaces")
utils_function_call = _P.var("hydra.python.utils.functionCall")
utils_indented_block = _P.var("hydra.python.utils.indentedBlock")
utils_primary_with_expression_slices = _P.var("hydra.python.utils.primaryWithExpressionSlices")
utils_primary_with_rhs = _P.var("hydra.python.utils.primaryWithRhs")
utils_project_from_expression = _P.var("hydra.python.utils.projectFromExpression")
utils_py_atom_to_py_expression = _P.var("hydra.python.utils.pyAtomToPyExpression")
utils_py_closed_pattern_to_py_patterns = _P.var("hydra.python.utils.pyClosedPatternToPyPatterns")
utils_py_expression_to_py_primary = _P.var("hydra.python.utils.pyExpressionToPyPrimary")
utils_py_expression_to_py_star_named_expression = _P.var("hydra.python.utils.pyExpressionToPyStarNamedExpression")
utils_py_expressions_to_py_args = _P.var("hydra.python.utils.pyExpressionsToPyArgs")
utils_py_name_to_py_expression = _P.var("hydra.python.utils.pyNameToPyExpression")
utils_py_name_to_py_type_parameter = _P.var("hydra.python.utils.pyNameToPyTypeParameter")
utils_py_primary_to_py_expression = _P.var("hydra.python.utils.pyPrimaryToPyExpression")
utils_py_simple_statement_to_py_statement = _P.var("hydra.python.utils.pySimpleStatementToPyStatement")
utils_string_to_py_expression = _P.var("hydra.python.utils.stringToPyExpression")
utils_py_list = _P.var("hydra.python.utils.pyList")
utils_py_name_to_py_primary = _P.var("hydra.python.utils.pyNameToPyPrimary")
utils_single_quoted_string = _P.var("hydra.python.utils.singleQuotedString")
utils_primary_and_params = _P.var("hydra.python.utils.primaryAndParams")
utils_primary_with_slices = _P.var("hydra.python.utils.primaryWithSlices")
utils_py_expression_to_py_slice = _P.var("hydra.python.utils.pyExpressionToPySlice")
utils_py_primary_to_py_slice = _P.var("hydra.python.utils.pyPrimaryToPySlice")
utils_py_list_helper = _P.var("hydra.python.utils.pyList")  # alias
utils_target_python_version = _P.var("hydra.python.utils.targetPythonVersion")
utils_annotated_expression = _P.var("hydra.python.utils.annotatedExpression")
utils_py_assignment_to_py_statement = _P.var("hydra.python.utils.pyAssignmentToPyStatement")
utils_py_class_definition_to_py_statement = _P.var("hydra.python.utils.pyClassDefinitionToPyStatement")
utils_py_expression_to_py_statement = _P.var("hydra.python.utils.pyExpressionToPyStatement")
utils_triple_quoted_string = _P.var("hydra.python.utils.tripleQuotedString")
utils_unit_variant_methods = _P.var("hydra.python.utils.unitVariantMethods")
utils_annotated_statement = _P.var("hydra.python.utils.annotatedStatement")
utils_dotted_assignment_statement = _P.var("hydra.python.utils.dottedAssignmentStatement")
utils_comment_statement = _P.var("hydra.python.utils.commentStatement")
environment_reorder_defs = _P.var("hydra.environment.reorderDefs")
utils_or_expression = _P.var("hydra.python.utils.orExpression")
utils_py_expression_to_bitwise_or = _P.var("hydra.python.utils.pyExpressionToBitwiseOr")
utils_py_expression_to_disjunction = _P.var("hydra.python.utils.pyExpressionToDisjunction")
utils_raise_assertion_error = _P.var("hydra.python.utils.raiseAssertionError")
utils_raise_type_error = _P.var("hydra.python.utils.raiseTypeError")
utils_return_single = _P.var("hydra.python.utils.returnSingle")
names_local_name_of = _P.var("hydra.names.localNameOf")
utils_name_and_params = _P.var("hydra.python.utils.nameAndParams")
utils_py_none = _P.var("hydra.python.utils.pyNone")
show_core_type = _P.var("hydra.show.core.type")
names_type_variable_reference = _P.var("hydra.python.names.typeVariableReference")
predicates_is_enum_row_type = _P.var("hydra.predicates.isEnumRowType")
predicates_is_unit_term = _P.var("hydra.predicates.isUnitTerm")
predicates_is_complex_term = _P.var("hydra.predicates.isComplexTerm")
predicates_is_complex_variable = _P.var("hydra.predicates.isComplexVariable")
arity_type_scheme_arity = _P.var("hydra.arity.typeSchemeArity")
arity_term_arity = _P.var("hydra.arity.termArity")
resolution_require_union_type = _P.var("hydra.resolution.requireUnionType")
errors_error_other = _P.var("hydra.errors.errorOther")
errors_other_error = _P.var("hydra.errors.otherError")
analysis_gather_args = _P.var("hydra.analysis.gatherArgs")
lexical_lookup_binding = _P.var("hydra.lexical.lookupBinding")
graph_graph_primitives = _P.var("hydra.graph.graphPrimitives")
arity_primitive_arity = _P.var("hydra.arity.primitiveArity")
arity_type_arity = _P.var("hydra.arity.typeArity")
lexical_lookup_primitive = _P.var("hydra.lexical.lookupPrimitive")
names_term_variable_reference = _P.var("hydra.python.names.termVariableReference")
names_encode_name_qualified = _P.var("hydra.python.names.encodeNameQualified")
names_encode_field_name_kr = _P.var("hydra.python.names.encodeFieldName")  # already added
core_equal_name = _P.var("hydra.core.equalName_")
variables_is_free_variable_in_term = _P.var("hydra.variables.isFreeVariableInTerm")
rewriting_subtypes = _P.var("hydra.rewriting.subtypes")
annotations_has_type_description = _P.var("hydra.annotations.hasTypeDescription")
dependencies_type_dependency_names = _P.var("hydra.dependencies.typeDependencyNames")
analysis_add_names_to_namespaces = _P.var("hydra.analysis.addNamesToNamespaces")
analysis_is_simple_assignment = _P.var("hydra.analysis.isSimpleAssignment")
analysis_is_self_tail_recursive = _P.var("hydra.analysis.isSelfTailRecursive")
rewriting_fold_over_term = _P.var("hydra.rewriting.foldOverTerm")
rewriting_fold_over_type = _P.var("hydra.rewriting.foldOverType")
coders_traversal_order_pre = _P.var("hydra.coders.traversalOrderPre")

# hydra.annotations
annotations_get_type_description = _P.var("hydra.annotations.getTypeDescription")
annotations_get_term_description = _P.var("hydra.annotations.getTermDescription")
formatting_normalize_comment = _P.var("hydra.formatting.normalizeComment")

utils_type_alias_statement = _P.var("hydra.python.utils.typeAliasStatement")
utils_type_alias_statement310 = _P.var("hydra.python.utils.typeAliasStatement310")
utils_union_type_class_statements310 = _P.var("hydra.python.utils.unionTypeClassStatements310")

# hydra.python.names (used by coder.py)
names_encode_enum_value = _P.var("hydra.python.names.encodeEnumValue")
names_encode_field_name = _P.var("hydra.python.names.encodeFieldName")
names_encode_name = _P.var("hydra.python.names.encodeName")
names_encode_namespace = _P.var("hydra.python.names.encodeNamespace")
names_encode_type_variable = _P.var("hydra.python.names.encodeTypeVariable")
names_use_future_annotations = _P.var("hydra.python.names.useFutureAnnotations")
names_variant_name = _P.var("hydra.python.names.variantName")
names_encode_constant_for_type_name = _P.var("hydra.python.names.encodeConstantForTypeName")
names_encode_constant_for_field_name = _P.var("hydra.python.names.encodeConstantForFieldName")

# hydra.predicates (used by coder.py)
predicates_is_complex_binding = _P.var("hydra.predicates.isComplexBinding")
predicates_is_trivial_term = _P.var("hydra.predicates.isTrivialTerm")
predicates_is_unit_type = _P.var("hydra.predicates.isUnitType")

# hydra.analysis
analysis_analyze_function_term_with = _P.var("hydra.analysis.analyzeFunctionTermWith")
analysis_gather_applications = _P.var("hydra.analysis.gatherApplications")

# hydra.environment
environment_with_lambda_context = _P.var("hydra.environment.withLambdaContext")
environment_with_let_context = _P.var("hydra.environment.withLetContext")
environment_with_type_lambda_context = _P.var("hydra.environment.withTypeLambdaContext")

# hydra.scoping / hydra.strip / hydra.variables
scoping_extend_graph_for_lambda = _P.var("hydra.scoping.extendGraphForLambda")
reduction_alpha_convert = _P.var("hydra.reduction.alphaConvert")
strip_deannotate_type = _P.var("hydra.strip.deannotateType")
strip_deannotate_and_detype_term = _P.var("hydra.strip.deannotateAndDetypeTerm")
variables_free_variables_in_type = _P.var("hydra.variables.freeVariablesInType")

# hydra.serialization (used by serde.py)
serialization_braces_list_adaptive = _P.var("hydra.serialization.bracesListAdaptive")
serialization_bracket_list = _P.var("hydra.serialization.bracketList")
serialization_bracket_list_adaptive = _P.var("hydra.serialization.bracketListAdaptive")
serialization_comma_sep = _P.var("hydra.serialization.commaSep")
serialization_comma_sep_adaptive = _P.var("hydra.serialization.commaSepAdaptive")
serialization_cst = _P.var("hydra.serialization.cst")
serialization_curly_braces_list = _P.var("hydra.serialization.curlyBracesList")
serialization_dot_sep = _P.var("hydra.serialization.dotSep")
serialization_double_newline_sep = _P.var("hydra.serialization.doubleNewlineSep")
serialization_half_block_style = _P.var("hydra.serialization.halfBlockStyle")
serialization_inline_style = _P.var("hydra.serialization.inlineStyle")
serialization_newline_sep = _P.var("hydra.serialization.newlineSep")
serialization_no_sep = _P.var("hydra.serialization.noSep")
serialization_paren_list_adaptive = _P.var("hydra.serialization.parenListAdaptive")
serialization_parens = _P.var("hydra.serialization.parens")
serialization_semicolon_sep = _P.var("hydra.serialization.semicolonSep")
serialization_space_sep = _P.var("hydra.serialization.spaceSep")
serialization_symbol_sep = _P.var("hydra.serialization.symbolSep")
serialization_tab_indent_double_space = _P.var("hydra.serialization.tabIndentDoubleSpace")

# hydra.packaging — these are DSL accessors (generated), not kernel functions.
# Re-export from hydra.dsl.packaging for symmetry with the Haskell DSL imports.
from hydra.dsl.packaging import (
    namespaces_focus as packaging_namespaces_focus,
    qualified_name_local as packaging_qualified_name_local,
    qualified_name_namespace as packaging_qualified_name_namespace,
    un_namespace as packaging_un_namespace,
)

# hydra.util CaseConvention enum constants are TTerms (injects), already
# available as constants in hydra.dsl.util. Re-export here for symmetry.
from hydra.dsl.util import (
    case_convention_camel as util_case_convention_camel,
    case_convention_lower_snake as util_case_convention_lower_snake,
    case_convention_upper_snake as util_case_convention_upper_snake,
    case_convention_pascal as util_case_convention_pascal,
)
