// Note: this is an automatically generated file. Do not edit.

package hydra.ext.haskell.testCodec;

/**
 * Haskell test code generation codec for HSpec-based generation tests
 */
public interface TestCodec {
  static hydra.util.Either<String, String> termToHaskell(hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> namespaces, hydra.core.Term term, hydra.graph.Graph g) {
    return hydra.lib.eithers.Bimap.apply(
      (java.util.function.Function<hydra.context.InContext<hydra.error.Error_>, String>) (ic -> hydra.show.error.Error_.error(((java.util.function.Function<hydra.context.InContext<hydra.error.Error_>, hydra.error.Error_>) (projected -> projected.object)).apply(ic))),
      (java.util.function.Function<hydra.ext.haskell.ast.Expression, String>) (arg_ -> hydra.serialization.Serialization.printExpr(hydra.serialization.Serialization.parenthesize(hydra.ext.haskell.serde.Serde.expressionToExpr(arg_)))),
      hydra.ext.haskell.coder.Coder.encodeTerm(
        0,
        namespaces,
        term,
        hydra.lexical.Lexical.emptyContext(),
        g));
  }
  
  static <T0> hydra.util.Either<String, String> typeToHaskell(hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> namespaces, hydra.core.Type typ, T0 g) {
    return hydra.lib.eithers.Bimap.apply(
      (java.util.function.Function<hydra.context.InContext<hydra.error.Error_>, String>) (ic -> hydra.show.error.Error_.error(((java.util.function.Function<hydra.context.InContext<hydra.error.Error_>, hydra.error.Error_>) (projected -> projected.object)).apply(ic))),
      (java.util.function.Function<hydra.ext.haskell.ast.Type, String>) (arg_ -> hydra.serialization.Serialization.printExpr(hydra.serialization.Serialization.parenthesize(hydra.ext.haskell.serde.Serde.typeToExpr(arg_)))),
      hydra.ext.haskell.coder.Coder.<T0>encodeType(
        namespaces,
        typ,
        hydra.lexical.Lexical.emptyContext(),
        g));
  }
  
  static hydra.testing.TestCodec haskellTestCodec(hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> namespaces) {
    return new hydra.testing.TestCodec(new hydra.coders.LanguageName("haskell"), new hydra.module.FileExtension("hs"), (java.util.function.Function<hydra.core.Term, java.util.function.Function<hydra.graph.Graph, hydra.util.Either<String, String>>>) (v1 -> (java.util.function.Function<hydra.graph.Graph, hydra.util.Either<String, String>>) (v2 -> hydra.ext.haskell.testCodec.TestCodec.termToHaskell(
      namespaces,
      v1,
      v2))), (java.util.function.Function<hydra.core.Type, java.util.function.Function<hydra.graph.Graph, hydra.util.Either<String, String>>>) (v1 -> (java.util.function.Function<hydra.graph.Graph, hydra.util.Either<String, String>>) (v2 -> hydra.ext.haskell.testCodec.TestCodec.typeToHaskell(
      namespaces,
      v1,
      v2))), (java.util.function.Function<String, String>) (n -> n), hydra.ext.haskell.testCodec.TestCodec::namespaceToModuleName, hydra.ext.haskell.testCodec.TestCodec.haskellTestCaseTemplate(), hydra.ext.haskell.testCodec.TestCodec.haskellTestGroupTemplate(), hydra.ext.haskell.testCodec.TestCodec.haskellModuleTemplate(), hydra.ext.haskell.testCodec.TestCodec.haskellImportTemplate(), (java.util.function.Function<hydra.util.PersistentSet<hydra.core.Name>, hydra.util.ConsList<String>>) (v1 -> hydra.ext.haskell.testCodec.TestCodec.findHaskellImports(
      namespaces,
      v1)));
  }
  
  static String haskellTestCaseTemplate() {
    return hydra.lib.strings.Intercalate.apply(
      "\n",
      hydra.util.ConsList.of(
        "  H.it {name} $ H.shouldBe",
        "    ({input})",
        "    ({output})",
        ""));
  }
  
  static String haskellTestGroupTemplate() {
    return "spec = H.describe {groupName} $ do";
  }
  
  static String haskellModuleTemplate() {
    return hydra.lib.strings.Intercalate.apply(
      "\n",
      hydra.util.ConsList.of(
        hydra.lib.strings.Cat2.apply(
          "-- ",
          hydra.constants.Constants.warningAutoGeneratedFile()),
        "",
        "module {moduleName} where",
        "",
        "{imports}",
        "",
        "spec :: H.Spec",
        "{testGroup}",
        "{testCases}",
        ""));
  }
  
  static String haskellImportTemplate() {
    return "import qualified {namespace} as {alias}";
  }
  
  static <T0> hydra.util.ConsList<String> findHaskellImports(hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> namespaces, T0 names_) {
    hydra.util.Lazy<hydra.util.PersistentMap<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>> mapping_ = new hydra.util.Lazy<>(() -> ((java.util.function.Function<hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>, hydra.util.PersistentMap<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>>) (projected -> projected.mapping)).apply(namespaces));
    hydra.util.Lazy<hydra.util.PersistentMap<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>> filtered = new hydra.util.Lazy<>(() -> hydra.lib.maps.FilterWithKey.apply(
      (java.util.function.Function<hydra.module.Namespace, java.util.function.Function<hydra.ext.haskell.ast.ModuleName, Boolean>>) (ns_ -> (java.util.function.Function<hydra.ext.haskell.ast.ModuleName, Boolean>) (_v -> hydra.lib.logic.Not.apply(hydra.lib.equality.Equal.apply(
        hydra.lib.lists.Head.apply(hydra.lib.strings.SplitOn.apply(
          "hydra.test.",
          (ns_).value)),
        "")))),
      mapping_.get()));
    return hydra.lib.lists.Map.apply(
      (java.util.function.Function<hydra.util.Pair<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>, String>) (entry -> hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
        "import qualified ",
        hydra.lib.strings.Intercalate.apply(
          ".",
          hydra.lib.lists.Map.apply(
            hydra.formatting.Formatting::capitalize,
            hydra.lib.strings.SplitOn.apply(
              ".",
              (hydra.lib.pairs.First.apply(entry)).value))),
        " as ",
        (hydra.lib.pairs.Second.apply(entry)).value))),
      hydra.lib.maps.ToList.apply(filtered.get()));
  }
  
  static String namespaceToModuleName(hydra.module.Namespace ns_) {
    return hydra.lib.strings.Intercalate.apply(
      ".",
      hydra.lib.lists.Map.apply(
        hydra.formatting.Formatting::capitalize,
        hydra.lib.strings.SplitOn.apply(
          ".",
          (ns_).value)));
  }
  
  static hydra.util.Either<String, String> generateTestGroupHierarchy(hydra.graph.Graph g, hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> namespaces, hydra.testing.TestCodec codec, Integer depth, hydra.testing.TestGroup testGroup) {
    hydra.util.ConsList<hydra.testing.TestCaseWithMetadata> cases_ = (testGroup).cases;
    hydra.util.Lazy<String> indent = new hydra.util.Lazy<>(() -> hydra.lib.strings.FromList.apply(hydra.lib.lists.Replicate.apply(
      hydra.lib.math.Mul.apply(
        depth,
        2),
      32)));
    hydra.util.ConsList<hydra.testing.TestGroup> subgroups = (testGroup).subgroups;
    return hydra.lib.eithers.Bind.apply(
      hydra.lib.eithers.MapList.apply(
        (java.util.function.Function<hydra.testing.TestCaseWithMetadata, hydra.util.Either<String, hydra.util.ConsList<String>>>) (tc -> hydra.ext.haskell.testCodec.TestCodec.generateTestCaseWithCodec(
          g,
          namespaces,
          codec,
          depth,
          tc)),
        cases_),
      (java.util.function.Function<hydra.util.ConsList<hydra.util.ConsList<String>>, hydra.util.Either<String, String>>) (testCaseLinesRaw -> {
        hydra.util.Lazy<hydra.util.ConsList<hydra.util.ConsList<String>>> testCaseLines = new hydra.util.Lazy<>(() -> hydra.lib.lists.Map.apply(
          (java.util.function.Function<hydra.util.ConsList<String>, hydra.util.ConsList<String>>) (lines_ -> hydra.lib.lists.Map.apply(
            (java.util.function.Function<String, String>) (line -> hydra.lib.strings.Cat2.apply(
              indent.get(),
              line)),
            lines_)),
          testCaseLinesRaw));
        hydra.util.Lazy<String> testCasesStr = new hydra.util.Lazy<>(() -> hydra.lib.strings.Intercalate.apply(
          "\n",
          hydra.lib.lists.Concat.apply(testCaseLines.get())));
        return hydra.lib.eithers.Map.apply(
          (java.util.function.Function<String, String>) (subgroupsStr -> hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
            testCasesStr.get(),
            hydra.lib.logic.IfElse.lazy(
              hydra.lib.logic.Or.apply(
                hydra.lib.equality.Equal.apply(
                  testCasesStr.get(),
                  ""),
                hydra.lib.equality.Equal.apply(
                  subgroupsStr,
                  "")),
              () -> "",
              () -> "\n"),
            subgroupsStr))),
          hydra.lib.eithers.Map.apply(
            (java.util.function.Function<hydra.util.ConsList<String>, String>) (blocks -> hydra.lib.strings.Intercalate.apply(
              "\n",
              blocks)),
            hydra.lib.eithers.MapList.apply(
              (java.util.function.Function<hydra.testing.TestGroup, hydra.util.Either<String, String>>) (subgroup -> {
                String groupName_ = (subgroup).name;
                return hydra.lib.eithers.Map.apply(
                  (java.util.function.Function<String, String>) (content -> hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
                    indent.get(),
                    "H.describe ",
                    hydra.lib.literals.ShowString.apply(groupName_),
                    " $ do\n",
                    content))),
                  hydra.ext.haskell.testCodec.TestCodec.generateTestGroupHierarchy(
                    g,
                    namespaces,
                    codec,
                    hydra.lib.math.Add.apply(
                      depth,
                      1),
                    subgroup));
              }),
              subgroups)));
      }));
  }
  
  static hydra.util.Either<String, hydra.util.ConsList<String>> generateTestCaseWithCodec(hydra.graph.Graph g, hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> namespaces, hydra.testing.TestCodec codec, Integer depth, hydra.testing.TestCaseWithMetadata tcm) {
    String name_ = (tcm).name;
    hydra.testing.TestCase tcase = (tcm).case_;
    return (tcase).accept(new hydra.testing.TestCase.PartialVisitor<>() {
      @Override
      public hydra.util.Either<String, hydra.util.ConsList<String>> otherwise(hydra.testing.TestCase instance) {
        return hydra.util.Either.<String, hydra.util.ConsList<String>>right((hydra.util.ConsList<String>) (hydra.util.ConsList.<String>of()));
      }
      
      @Override
      public hydra.util.Either<String, hydra.util.ConsList<String>> visit(hydra.testing.TestCase.DelegatedEvaluation delCase) {
        Integer continuationIndent = hydra.lib.math.Add.apply(
          hydra.lib.math.Mul.apply(
            depth,
            2),
          4);
        String formattedName = ((codec).formatTestName).apply(name_);
        hydra.core.Term input_ = ((delCase).value).input;
        hydra.core.Term output_ = ((delCase).value).output;
        return hydra.lib.eithers.Bind.apply(
          (((codec).encodeTerm).apply(input_)).apply(g),
          (java.util.function.Function<String, hydra.util.Either<String, hydra.util.ConsList<String>>>) (inputCode -> hydra.lib.eithers.Bind.apply(
            (((codec).encodeTerm).apply(output_)).apply(g),
            (java.util.function.Function<String, hydra.util.Either<String, hydra.util.ConsList<String>>>) (outputCode -> hydra.lib.eithers.Bind.apply(
              hydra.ext.haskell.testCodec.TestCodec.generateTypeAnnotationFor(
                g,
                namespaces,
                input_,
                output_),
              (java.util.function.Function<hydra.util.Maybe<String>, hydra.util.Either<String, hydra.util.ConsList<String>>>) (typeAnnotation -> {
                String indentedOutputCode = hydra.ext.haskell.testCodec.TestCodec.indentContinuationLines(
                  continuationIndent,
                  outputCode);
                hydra.util.Lazy<String> finalOutputCode = new hydra.util.Lazy<>(() -> hydra.lib.maybes.Maybe.applyLazy(
                  () -> indentedOutputCode,
                  (java.util.function.Function<String, String>) (anno -> hydra.lib.strings.Cat2.apply(
                    indentedOutputCode,
                    anno)),
                  typeAnnotation));
                String indentedInputCode = hydra.ext.haskell.testCodec.TestCodec.indentContinuationLines(
                  continuationIndent,
                  inputCode);
                return hydra.util.Either.<String, hydra.util.ConsList<String>>right(hydra.util.ConsList.of(
                  hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
                    "H.it ",
                    hydra.lib.literals.ShowString.apply(formattedName),
                    " $ H.shouldBe")),
                  hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
                    "  (",
                    indentedInputCode,
                    ")")),
                  hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
                    "  (",
                    finalOutputCode.get(),
                    ")"))));
              }))))));
      }
    });
  }
  
  static String indentContinuationLines(Integer n, String s) {
    return hydra.lib.strings.Intercalate.apply(
      hydra.lib.strings.Cat2.apply(
        "\n",
        hydra.lib.strings.FromList.apply(hydra.lib.lists.Replicate.apply(
          n,
          32))),
      hydra.lib.strings.SplitOn.apply(
        "\n",
        s));
  }
  
  static hydra.util.Either<String, hydra.util.Maybe<String>> generateTypeAnnotationFor(hydra.graph.Graph g, hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> namespaces, hydra.core.Term inputTerm, hydra.core.Term outputTerm) {
    return hydra.lib.logic.IfElse.lazy(
      hydra.lib.logic.Not.apply(hydra.ext.haskell.testCodec.TestCodec.containsTriviallyPolymorphic(outputTerm)),
      () -> hydra.util.Either.<String, hydra.util.Maybe<String>>right((hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing())),
      () -> hydra.lib.maybes.Maybe.applyLazy(
        () -> hydra.util.Either.<String, hydra.util.Maybe<String>>right((hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing())),
        (java.util.function.Function<hydra.util.Pair<hydra.core.Term, hydra.core.TypeScheme>, hydra.util.Either<String, hydra.util.Maybe<String>>>) (result -> {
          hydra.util.Lazy<hydra.util.PersistentSet<hydra.core.Name>> schemaVars = new hydra.util.Lazy<>(() -> hydra.lib.sets.FromList.apply(hydra.lib.maps.Keys.apply((g).schemaTypes)));
          hydra.util.Lazy<hydra.core.TypeScheme> typeScheme = new hydra.util.Lazy<>(() -> hydra.lib.pairs.Second.apply(result));
          hydra.core.Type typ = (typeScheme.get()).type;
          hydra.util.Lazy<hydra.util.ConsList<hydra.core.Name>> freeVars = new hydra.util.Lazy<>(() -> hydra.lib.sets.ToList.apply(hydra.lib.sets.Difference.apply(
            hydra.rewriting.Rewriting.freeVariablesInType(typ),
            schemaVars.get())));
          Boolean isEither = (hydra.rewriting.Rewriting.deannotateTerm(outputTerm)).accept(new hydra.core.Term.PartialVisitor<>() {
            @Override
            public Boolean otherwise(hydra.core.Term instance) {
              return false;
            }
            
            @Override
            public Boolean visit(hydra.core.Term.Either ignored) {
              return true;
            }
          });
          return hydra.lib.logic.IfElse.lazy(
            hydra.lib.logic.Or.apply(
              isEither,
              hydra.lib.logic.Not.apply(hydra.lib.lists.Null.apply(freeVars.get()))),
            () -> ((java.util.function.Supplier<hydra.util.Either<String, hydra.util.Maybe<String>>>) (() -> {
              hydra.core.Type int32Type = new hydra.core.Type.Literal(new hydra.core.LiteralType.Integer_(new hydra.core.IntegerType.Int32()));
              hydra.util.Lazy<hydra.typing.TypeSubst> subst = new hydra.util.Lazy<>(() -> new hydra.typing.TypeSubst(hydra.lib.maps.FromList.apply(hydra.lib.lists.Map.apply(
                (java.util.function.Function<hydra.core.Name, hydra.util.Pair<hydra.core.Name, hydra.core.Type>>) (v -> (hydra.util.Pair<hydra.core.Name, hydra.core.Type>) ((hydra.util.Pair<hydra.core.Name, hydra.core.Type>) (new hydra.util.Pair<hydra.core.Name, hydra.core.Type>(v, int32Type)))),
                freeVars.get()))));
              hydra.core.Type groundedType = hydra.substitution.Substitution.substInType(
                subst.get(),
                typ);
              return hydra.lib.eithers.Map.apply(
                (java.util.function.Function<String, hydra.util.Maybe<String>>) (typeStr -> hydra.util.Maybe.just(hydra.lib.strings.Cat2.apply(
                  " :: ",
                  typeStr))),
                hydra.ext.haskell.testCodec.TestCodec.typeToHaskell(
                  namespaces,
                  groundedType,
                  g));
            })).get(),
            () -> hydra.util.Either.<String, hydra.util.Maybe<String>>right((hydra.util.Maybe<String>) (hydra.util.Maybe.<String>nothing())));
        }),
        hydra.ext.haskell.testCodec.TestCodec.tryInferTypeOf(
          g,
          inputTerm)));
  }
  
  static hydra.util.Maybe<hydra.util.Pair<hydra.core.Term, hydra.core.TypeScheme>> tryInferTypeOf(hydra.graph.Graph g, hydra.core.Term term) {
    return hydra.lib.eithers.Either.apply(
      (java.util.function.Function<hydra.context.InContext<hydra.error.Error_>, hydra.util.Maybe<hydra.util.Pair<hydra.core.Term, hydra.core.TypeScheme>>>) (ignored -> (hydra.util.Maybe<hydra.util.Pair<hydra.core.Term, hydra.core.TypeScheme>>) (hydra.util.Maybe.<hydra.util.Pair<hydra.core.Term, hydra.core.TypeScheme>>nothing())),
      (java.util.function.Function<hydra.util.Pair<hydra.util.Pair<hydra.core.Term, hydra.core.TypeScheme>, hydra.context.Context>, hydra.util.Maybe<hydra.util.Pair<hydra.core.Term, hydra.core.TypeScheme>>>) (result -> hydra.util.Maybe.just(hydra.lib.pairs.First.apply(result))),
      hydra.inference.Inference.inferTypeOf(
        hydra.lexical.Lexical.emptyContext(),
        g,
        term));
  }
  
  static Boolean containsTriviallyPolymorphic(hydra.core.Term term) {
    return (term).accept(new hydra.core.Term.PartialVisitor<>() {
      @Override
      public Boolean otherwise(hydra.core.Term instance) {
        return false;
      }
      
      @Override
      public Boolean visit(hydra.core.Term.List xs) {
        return hydra.lib.logic.Or.apply(
          hydra.lib.lists.Null.apply((xs).value),
          hydra.lib.lists.Foldl.apply(
            (java.util.function.Function<Boolean, java.util.function.Function<Boolean, Boolean>>) (p0 -> p1 -> hydra.lib.logic.Or.apply(
              p0,
              p1)),
            false,
            hydra.lib.lists.Map.apply(
              hydra.ext.haskell.testCodec.TestCodec::containsTriviallyPolymorphic,
              (xs).value)));
      }
      
      @Override
      public Boolean visit(hydra.core.Term.Set s) {
        return hydra.lib.logic.Or.apply(
          hydra.lib.sets.Null.apply((s).value),
          hydra.lib.lists.Foldl.apply(
            (java.util.function.Function<Boolean, java.util.function.Function<Boolean, Boolean>>) (p0 -> p1 -> hydra.lib.logic.Or.apply(
              p0,
              p1)),
            false,
            hydra.lib.lists.Map.apply(
              hydra.ext.haskell.testCodec.TestCodec::containsTriviallyPolymorphic,
              hydra.lib.sets.ToList.apply((s).value))));
      }
      
      @Override
      public Boolean visit(hydra.core.Term.Map m) {
        return hydra.lib.logic.Or.apply(
          hydra.lib.maps.Null.apply((m).value),
          hydra.lib.logic.Or.apply(
            hydra.lib.lists.Foldl.apply(
              (java.util.function.Function<Boolean, java.util.function.Function<Boolean, Boolean>>) (p0 -> p1 -> hydra.lib.logic.Or.apply(
                p0,
                p1)),
              false,
              hydra.lib.lists.Map.apply(
                hydra.ext.haskell.testCodec.TestCodec::containsTriviallyPolymorphic,
                hydra.lib.maps.Keys.apply((m).value))),
            hydra.lib.lists.Foldl.apply(
              (java.util.function.Function<Boolean, java.util.function.Function<Boolean, Boolean>>) (p0 -> p1 -> hydra.lib.logic.Or.apply(
                p0,
                p1)),
              false,
              hydra.lib.lists.Map.apply(
                hydra.ext.haskell.testCodec.TestCodec::containsTriviallyPolymorphic,
                hydra.lib.lists.Map.apply(
                  (java.util.function.Function<hydra.util.Pair<hydra.core.Term, hydra.core.Term>, hydra.core.Term>) (p -> hydra.lib.pairs.Second.apply(p)),
                  hydra.lib.maps.ToList.apply((m).value))))));
      }
      
      @Override
      public Boolean visit(hydra.core.Term.Maybe mx) {
        return hydra.lib.maybes.Maybe.applyLazy(
          () -> true,
          hydra.ext.haskell.testCodec.TestCodec::containsTriviallyPolymorphic,
          (mx).value);
      }
      
      @Override
      public Boolean visit(hydra.core.Term.Either ignored) {
        return true;
      }
      
      @Override
      public Boolean visit(hydra.core.Term.Union inj) {
        return hydra.ext.haskell.testCodec.TestCodec.containsTriviallyPolymorphic((((inj).value).field).term);
      }
      
      @Override
      public Boolean visit(hydra.core.Term.Pair p) {
        return hydra.lib.logic.Or.apply(
          hydra.ext.haskell.testCodec.TestCodec.containsTriviallyPolymorphic(hydra.lib.pairs.First.apply((p).value)),
          hydra.ext.haskell.testCodec.TestCodec.containsTriviallyPolymorphic(hydra.lib.pairs.Second.apply((p).value)));
      }
      
      @Override
      public Boolean visit(hydra.core.Term.Record rec) {
        return hydra.lib.lists.Foldl.apply(
          (java.util.function.Function<Boolean, java.util.function.Function<Boolean, Boolean>>) (p0 -> p1 -> hydra.lib.logic.Or.apply(
            p0,
            p1)),
          false,
          hydra.lib.lists.Map.apply(
            (java.util.function.Function<hydra.core.Field, Boolean>) (f -> hydra.ext.haskell.testCodec.TestCodec.containsTriviallyPolymorphic((f).term)),
            ((rec).value).fields));
      }
      
      @Override
      public Boolean visit(hydra.core.Term.Application app) {
        return hydra.lib.logic.Or.apply(
          hydra.ext.haskell.testCodec.TestCodec.containsTriviallyPolymorphic(((app).value).function),
          hydra.ext.haskell.testCodec.TestCodec.containsTriviallyPolymorphic(((app).value).argument));
      }
    });
  }
  
  static <T0> String buildTestModuleWithCodec(hydra.testing.TestCodec codec, hydra.module.Module testModule, hydra.testing.TestGroup testGroup, String testBody, T0 namespaces) {
    hydra.util.Lazy<hydra.util.ConsList<String>> domainImports = new hydra.util.Lazy<>(() -> ((codec).findImports).apply((hydra.util.PersistentSet<hydra.core.Name>) (hydra.lib.sets.Empty.<hydra.core.Name>apply())));
    hydra.util.ConsList<String> standardImports = hydra.util.ConsList.of(
      "import Hydra.Kernel",
      "import qualified Test.Hspec as H",
      "import qualified Data.List as L",
      "import qualified Data.Map as M",
      "import qualified Data.Set as S",
      "import qualified Data.Maybe as Y");
    hydra.util.Lazy<hydra.util.ConsList<String>> allImports = new hydra.util.Lazy<>(() -> hydra.lib.lists.Concat2.apply(
      standardImports,
      domainImports.get()));
    hydra.util.ConsList<String> debugComments = hydra.util.ConsList.of(
      "-- DEBUG: Focus namespace = (see generated module)",
      "-- DEBUG: Namespace mappings: (see generated module)");
    String groupName_ = (testGroup).name;
    hydra.module.Namespace ns_ = (testModule).namespace;
    hydra.module.Namespace specNs = new hydra.module.Namespace(hydra.lib.strings.Cat2.apply(
      (ns_).value,
      "Spec"));
    String moduleNameString = ((codec).formatModuleName).apply(specNs);
    hydra.util.Lazy<String> header = new hydra.util.Lazy<>(() -> hydra.lib.strings.Intercalate.apply(
      "\n",
      hydra.lib.lists.Concat.apply(hydra.util.ConsList.of(
        hydra.util.ConsList.of(
          hydra.lib.strings.Cat2.apply(
            "-- ",
            hydra.constants.Constants.warningAutoGeneratedFile()),
          ""),
        debugComments,
        hydra.util.ConsList.of(
          "",
          hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
            "module ",
            moduleNameString,
            " where")),
          ""),
        allImports.get(),
        hydra.util.ConsList.of(
          "",
          "spec :: H.Spec",
          hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
            "spec = H.describe ",
            hydra.lib.literals.ShowString.apply(groupName_),
            " $ do")))))));
    return hydra.lib.strings.Cat.apply(hydra.util.ConsList.of(
      header.get(),
      "\n",
      testBody,
      "\n"));
  }
  
  static hydra.util.Either<String, hydra.util.Pair<String, String>> generateTestFileWithCodec(hydra.testing.TestCodec codec, hydra.module.Module testModule, hydra.testing.TestGroup testGroup, hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> namespaces, hydra.graph.Graph g) {
    return hydra.lib.eithers.Map.apply(
      (java.util.function.Function<String, hydra.util.Pair<String, String>>) (testBody -> {
        String ext = ((codec).fileExtension).value;
        hydra.module.Namespace ns_ = (testModule).namespace;
        hydra.module.Namespace specNs = new hydra.module.Namespace(hydra.lib.strings.Cat2.apply(
          (ns_).value,
          "Spec"));
        String filePath = hydra.names.Names.namespaceToFilePath(
          new hydra.util.CaseConvention.Pascal(),
          new hydra.module.FileExtension(ext),
          specNs);
        hydra.util.Lazy<String> testModuleContent = new hydra.util.Lazy<>(() -> hydra.ext.haskell.testCodec.TestCodec.buildTestModuleWithCodec(
          codec,
          testModule,
          testGroup,
          testBody,
          namespaces));
        return (hydra.util.Pair<String, String>) ((hydra.util.Pair<String, String>) (new hydra.util.Pair<String, String>(filePath, testModuleContent.get())));
      }),
      hydra.ext.haskell.testCodec.TestCodec.generateTestGroupHierarchy(
        g,
        namespaces,
        codec,
        1,
        testGroup));
  }
  
  static hydra.util.PersistentSet<hydra.core.Name> extractEncodedTermVariableNames(hydra.graph.Graph graf, hydra.core.Term term) {
    return hydra.rewriting.Rewriting.foldOverTerm(
      new hydra.coders.TraversalOrder.Pre(),
      (java.util.function.Function<hydra.util.PersistentSet<hydra.core.Name>, java.util.function.Function<hydra.core.Term, hydra.util.PersistentSet<hydra.core.Name>>>) (v1 -> (java.util.function.Function<hydra.core.Term, hydra.util.PersistentSet<hydra.core.Name>>) (v2 -> hydra.ext.haskell.testCodec.TestCodec.collectNames(
        graf,
        v1,
        v2))),
      (hydra.util.PersistentSet<hydra.core.Name>) (hydra.lib.sets.Empty.<hydra.core.Name>apply()),
      term);
  }
  
  static hydra.util.PersistentSet<hydra.core.Name> collectNames(hydra.graph.Graph graf, hydra.util.PersistentSet<hydra.core.Name> names, hydra.core.Term t) {
    return hydra.lib.logic.IfElse.lazy(
      hydra.schemas.Schemas.isEncodedTerm(hydra.rewriting.Rewriting.deannotateTerm(t)),
      () -> hydra.lib.eithers.Either.apply(
        (java.util.function.Function<hydra.error.DecodingError, hydra.util.PersistentSet<hydra.core.Name>>) (ignored -> names),
        (java.util.function.Function<hydra.core.Term, hydra.util.PersistentSet<hydra.core.Name>>) (decodedTerm -> hydra.lib.sets.Union.apply(
          names,
          hydra.rewriting.Rewriting.termDependencyNames(
            true,
            true,
            true,
            decodedTerm))),
        hydra.lib.eithers.Bimap.apply(
          (java.util.function.Function<hydra.error.DecodingError, hydra.error.DecodingError>) (_e -> _e),
          (java.util.function.Function<hydra.core.Term, hydra.core.Term>) (_a -> _a),
          hydra.decode.core.Core.term(
            graf,
            t))),
      () -> names);
  }
  
  static hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> addNamespacesToNamespaces(hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName> ns0, hydra.util.PersistentSet<hydra.core.Name> names) {
    hydra.util.Lazy<hydra.util.PersistentSet<hydra.module.Namespace>> newNamespaces = new hydra.util.Lazy<>(() -> hydra.lib.sets.FromList.apply(hydra.lib.maybes.Cat.apply(hydra.lib.lists.Map.apply(
      hydra.names.Names::namespaceOf,
      hydra.lib.sets.ToList.apply(names)))));
    java.util.function.Function<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName> toModuleName = (java.util.function.Function<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>) (namespace -> new hydra.ext.haskell.ast.ModuleName(hydra.formatting.Formatting.capitalize(hydra.lib.lists.Last.apply(hydra.lib.strings.SplitOn.apply(
      ".",
      (namespace).value)))));
    hydra.util.Lazy<hydra.util.PersistentMap<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>> newMappings = new hydra.util.Lazy<>(() -> hydra.lib.maps.FromList.apply(hydra.lib.lists.Map.apply(
      (java.util.function.Function<hydra.module.Namespace, hydra.util.Pair<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>>) (ns_ -> (hydra.util.Pair<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>) ((hydra.util.Pair<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>) (new hydra.util.Pair<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>(ns_, (toModuleName).apply(ns_))))),
      hydra.lib.sets.ToList.apply(newNamespaces.get()))));
    return (hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>) (new hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>(((java.util.function.Function<hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>, hydra.util.Pair<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>>) (projected -> projected.focus)).apply(ns0), hydra.lib.maps.Union.apply(
      ((java.util.function.Function<hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>, hydra.util.PersistentMap<hydra.module.Namespace, hydra.ext.haskell.ast.ModuleName>>) (projected -> projected.mapping)).apply(ns0),
      newMappings.get())));
  }
  
  static hydra.util.Either<String, hydra.util.Pair<String, String>> generateHaskellTestFile(hydra.module.Module testModule, hydra.testing.TestGroup testGroup, hydra.graph.Graph g) {
    return hydra.lib.eithers.Bind.apply(
      hydra.ext.haskell.testCodec.TestCodec.buildNamespacesForTestGroup(
        testModule,
        testGroup,
        g),
      (java.util.function.Function<hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>, hydra.util.Either<String, hydra.util.Pair<String, String>>>) (namespaces -> hydra.ext.haskell.testCodec.TestCodec.generateTestFileWithCodec(
        hydra.ext.haskell.testCodec.TestCodec.haskellTestCodec(namespaces),
        testModule,
        testGroup,
        namespaces,
        g)));
  }
  
  static hydra.util.Either<String, hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>> buildNamespacesForTestGroup(hydra.module.Module mod, hydra.testing.TestGroup tgroup, hydra.graph.Graph graph_) {
    hydra.util.ConsList<hydra.testing.TestCaseWithMetadata> testCases_ = hydra.ext.haskell.testCodec.TestCodec.collectTestCases(tgroup);
    hydra.util.Lazy<hydra.util.ConsList<hydra.core.Term>> testTerms = new hydra.util.Lazy<>(() -> hydra.lib.lists.Concat.apply(hydra.lib.lists.Map.apply(
      hydra.ext.haskell.testCodec.TestCodec::extractTestTerms,
      testCases_)));
    hydra.util.Lazy<hydra.util.ConsList<hydra.core.Binding>> testBindings = new hydra.util.Lazy<>(() -> hydra.lib.lists.Map.apply(
      (java.util.function.Function<hydra.core.Term, hydra.core.Binding>) (term -> new hydra.core.Binding(new hydra.core.Name("_test_"), term, (hydra.util.Maybe<hydra.core.TypeScheme>) (hydra.util.Maybe.<hydra.core.TypeScheme>nothing()))),
      testTerms.get()));
    hydra.module.Module tempModule = new hydra.module.Module((mod).namespace, testBindings.get(), (mod).termDependencies, (mod).typeDependencies, (mod).description);
    return hydra.lib.eithers.Bind.apply(
      hydra.lib.eithers.Bimap.apply(
        (java.util.function.Function<hydra.context.InContext<hydra.error.Error_>, String>) (ic -> hydra.show.error.Error_.error(((java.util.function.Function<hydra.context.InContext<hydra.error.Error_>, hydra.error.Error_>) (projected -> projected.object)).apply(ic))),
        (java.util.function.Function<hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>, hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>>) (a -> a),
        hydra.ext.haskell.utils.Utils.namespacesForModule(
          tempModule,
          hydra.lexical.Lexical.emptyContext(),
          graph_)),
      (java.util.function.Function<hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>, hydra.util.Either<String, hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>>>) (baseNamespaces -> {
        hydra.util.Lazy<hydra.util.PersistentSet<hydra.core.Name>> encodedNames = new hydra.util.Lazy<>(() -> hydra.lib.sets.Unions.apply(hydra.lib.lists.Map.apply(
          (java.util.function.Function<hydra.core.Term, hydra.util.PersistentSet<hydra.core.Name>>) (t -> hydra.ext.haskell.testCodec.TestCodec.extractEncodedTermVariableNames(
            graph_,
            t)),
          testTerms.get())));
        return hydra.util.Either.<String, hydra.module.Namespaces<hydra.ext.haskell.ast.ModuleName>>right(hydra.ext.haskell.testCodec.TestCodec.addNamespacesToNamespaces(
          baseNamespaces,
          encodedNames.get()));
      }));
  }
  
  static hydra.util.ConsList<hydra.testing.TestCaseWithMetadata> collectTestCases(hydra.testing.TestGroup tg) {
    return hydra.lib.lists.Concat2.apply(
      (tg).cases,
      hydra.lib.lists.Concat.apply(hydra.lib.lists.Map.apply(
        hydra.ext.haskell.testCodec.TestCodec::collectTestCases,
        (tg).subgroups)));
  }
  
  static hydra.util.ConsList<hydra.core.Term> extractTestTerms(hydra.testing.TestCaseWithMetadata tcm) {
    return ((tcm).case_).accept(new hydra.testing.TestCase.PartialVisitor<>() {
      @Override
      public hydra.util.ConsList<hydra.core.Term> otherwise(hydra.testing.TestCase instance) {
        return (hydra.util.ConsList<hydra.core.Term>) (hydra.util.ConsList.<hydra.core.Term>of());
      }
      
      @Override
      public hydra.util.ConsList<hydra.core.Term> visit(hydra.testing.TestCase.DelegatedEvaluation delCase) {
        return hydra.util.ConsList.of(
          ((delCase).value).input,
          ((delCase).value).output);
      }
    });
  }
}
