name:       hydra-ext
version:    0.9.0
author:     josh@fortytwo.net
license:    Apache-2.0
category:   Data
synopsis:   Built-in extensions to Hydra, including models, coders, and utilities
github:     CategoricalData/hydra

extra-source-files:
  - LICENSE
  - README.md
  - stack.yaml

dependencies: # copied from ../hydra-haskell
  - HsYAML                        >= 0.2.1 && < 0.3
  - aeson                         >= 2.0.0 && < 2.2
  - aeson-pretty                  >= 0.8.9 && < 0.9
  - base                          >= 4.18.0 && < 4.19
  - bytestring                    >= 0.11.3 && < 0.12
  - containers                    >= 0.6.5 && < 0.7
  - directory                     >= 1.3.6 && < 1.4
  - filepath                      >= 1.4.2 && < 1.5
  - scientific                    >= 0.3.7 && < 0.4
  - split                         >= 0.2.3 && < 0.3
  - text                          >= 2.0.2 && < 2.1
  - vector                        >= 0.12.0 && < 0.14
  - mtl # Temporary, for the Algorithm W implementation

library:
  source-dirs:
    - src/main/haskell
    - src/gen-main/haskell
    - ../hydra-haskell/src/main/haskell
    - ../hydra-haskell/src/gen-main/haskell
