name:       hydra-ext
version:    0.12.0
author:     josh@fortytwo.net
license:    Apache-2.0
category:   Data
synopsis:   Built-in extensions to Hydra, including models, coders, and utilities
github:     CategoricalData/hydra

extra-source-files:
  - LICENSE
  - README.md
  - stack.yaml

dependencies: # copied from ../hydra-haskell/package.yaml
  - HsYAML                        >= 0.2.1 && < 0.3
  - aeson                         >= 2.2.0 && < 2.3
  - aeson-pretty                  >= 0.8.9 && < 0.9
  - base                          >= 4.20.0 && < 4.21
  - base64-bytestring             >= 1.2.1 && < 1.3
  - bytestring                    >= 0.12.0 && < 0.13
  - containers                    >= 0.7 && < 0.8
  - directory                     >= 1.3.6 && < 1.4
  - filepath                      >= 1.5.0 && < 1.6
  - scientific                    >= 0.3.7 && < 0.4
  - split                         >= 0.2.3 && < 0.3
  - text                          >= 2.1.0 && < 2.2
  - vector                        >= 0.12.0 && < 0.14

library:
  source-dirs:
    - src/main/haskell
    - src/gen-main/haskell
    - ../hydra-haskell/src/main/haskell
    - ../hydra-haskell/src/gen-main/haskell
  ghc-options: [-rtsopts]

executables:
  update-java-kernel:
    main: Main.hs
    source-dirs:
      - src/exec/update-java-kernel
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-java-kernel-types:
    main: Main.hs
    source-dirs:
      - src/exec/update-java-kernel-types
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-java-kernel-tests:
    main: Main.hs
    source-dirs:
      - src/exec/update-java-kernel-tests
      - ../hydra-haskell/src/gen-test/haskell
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext
      - hspec

  update-java-generation-tests:
    main: Main.hs
    source-dirs:
      - src/exec/update-java-generation-tests
      - ../hydra-haskell/src/gen-test/haskell
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext
      - hspec

  update-java-eval-lib:
    main: Main.hs
    source-dirs:
      - src/exec/update-java-eval-lib
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-java-kernel-sources:
    main: Main.hs
    source-dirs:
      - src/exec/update-java-kernel-sources
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-python-kernel:
    main: Main.hs
    source-dirs:
      - src/exec/update-python-kernel
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-python-eval-lib:
    main: Main.hs
    source-dirs:
      - src/exec/update-python-eval-lib
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-python-kernel-tests:
    main: Main.hs
    source-dirs:
      - src/exec/update-python-kernel-tests
      - ../hydra-haskell/src/gen-test/haskell
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext
      - hspec

  update-python-generation-tests:
    main: Main.hs
    source-dirs:
      - src/exec/update-python-generation-tests
      - ../hydra-haskell/src/gen-test/haskell
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext
      - hspec

  test-java-modules:
    main: Main.hs
    source-dirs:
      - src/exec/test-java-modules
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext

  update-python-kernel-sources:
    main: Main.hs
    source-dirs:
      - src/exec/update-python-kernel-sources
    ghc-options: [-rtsopts]
    dependencies:
      - hydra-ext